import { escapeHTML, lower } from '../core/core.js';
export const KEYWORDS='DefBool DefByte DefInt DefLng DefCur DefSng DefDbl DefDate DefStr DefObj DefVar Implements Option Explicit Base Compare Text Binary Private Public Global Friend Static Dim ReDim Preserve Const As New Set Let Call Sub Function Property Get End Exit If Then Else ElseIf For Each To Step Next Do Loop While Until Wend Select Case Is With WithEvents GoTo GoSub Return On Error Resume Stop And Or Xor Not Eqv Imp Mod Like True False Nothing Null Empty ByVal ByRef Optional ParamArray Type TypeOf LSet RSet Enum Implements RaiseEvent Event Open Close Print Write Input Line Append Output Random Binary Access Read Shared Lock Unlock Integer Long Single Double Currency Decimal Byte Boolean String Date Object Variant Me Debug Load Unload'.split(' ');
export const BUILTINS='Abs Array Asc AscW Atn Beep CVErr CallByName IsMissing CBool CByte CCur CDate CDbl CInt CLng CSng CStr CVar Chr ChrW Collection Cos CreateObject Date DateAdd DateDiff DatePart DateSerial DateValue Day Dir DoEvents Environ EOF Erase Err Exp FileLen Fix Format FormatCurrency FormatDateTime FormatNumber FormatPercent FreeFile GetAttr GetSetting Hex Hour IIf InStr InStrRev Int IsArray IsDate IsEmpty IsError IsNull IsNumeric IsObject Join LBound LCase Left Len LoadPicture LoadResString LoadResData LoadResPicture Log LTrim Mid Minute Month MonthName MsgBox InputBox Now Oct Replace RGB Right Rnd Round RTrim SaveSetting Second Sgn Sin Space Split Sqr Str StrComp StrConv String Switch Tan Time Timer TimeSerial TimeValue Trim TypeName UBound UCase Val VarType Weekday WeekdayName Year'.split(' ');
export const MEMBERS='Name Caption WindowState ActiveForm MDIChild Arrange Text Value Left Top Width Height Enabled Visible TabIndex TabStop Tag ToolTipText BackColor ForeColor FontName FontSize FontBold FontItalic List ListIndex ListCount AddItem RemoveItem ItemData Selected Clear SetFocus Move Refresh ZOrder Show Hide Cls Print Line Circle PSet ScaleMode ScaleWidth ScaleHeight CurrentX CurrentY Rows Cols Row Col TextMatrix ColWidth Clip FixedRows FixedCols FormatString Nodes ListItems ColumnHeaders Panels Tabs Buttons Item Count Add Remove Key Index Parent Children Child Expanded SelectedItem SelectedNode EnsureVisible SelStart SelLength SelText SelBold SelColor Min Max Interval Path Pattern ConnectionString Provider CommandText CommandType CommandTimeout ActiveConnection Execute OpenSchema BeginTrans CommitTrans RollbackTrans Parameters CreateParameter Append Requery Cancel CancelUpdate DataEnvironment1 DataMember DataField Recordset DataSource Fields RecordCount EOF BOF AddNew Update Delete MoveFirst MoveLast MoveNext MovePrevious Sort Filter Open Close ShowOpen ShowSave FileName DialogTitle CancelError'.split(' ');
const keywordSet=new Set(KEYWORDS.map(lower));
export function highlightLine(line,selectionStart=-1,selectionEnd=-1,executionStart=-1,executionEnd=-1){
  let out='',i=0;
  const emit=(text,start,kind='')=>{
    if((selectionEnd<=start||selectionStart>=start+text.length)&&(executionEnd<=start||executionStart>=start+text.length)){const html=escapeHTML(text);return kind?'<span class="syn-'+kind+'">'+html+'</span>':html;}
    const bound=n=>Math.max(0,Math.min(text.length,n-start));
    const cuts=[...new Set([0,text.length,bound(selectionStart),bound(selectionEnd),bound(executionStart),bound(executionEnd)])].sort((a,b)=>a-b);
    let html='';for(let j=0;j<cuts.length-1;j++){const a=cuts[j],b=cuts[j+1];if(a===b)continue;const classes=[];
      if(start+a>=selectionStart&&start+a<selectionEnd)classes.push('code-selection');
      if(start+a>=executionStart&&start+a<executionEnd)classes.push('code-execution');
      const value=escapeHTML(text.slice(a,b));html+=classes.length?'<span class="'+classes.join(' ')+'">'+value+'</span>':value;
    }
    return kind?'<span class="syn-'+kind+'">'+html+'</span>':html;
  };
  while(i<line.length){const c=line[i];if(c==="'"||/^Rem(?:\s|$)/i.test(line.slice(i))&&(i===0||/[\s:]/.test(line[i-1]))){out+=emit(line.slice(i),i,'comment');break;}if(c==='"'){let j=i+1;for(;j<line.length;j++){if(line[j]==='"'){if(line[j+1]==='"'){j++;continue;}j++;break;}}out+=emit(line.slice(i,j),i,'string');i=j;continue;}const word=line.slice(i).match(/^[A-Za-z_][A-Za-z0-9_]*[$%&!#@]?/);if(word){out+=emit(word[0],i,keywordSet.has(lower(word[0]))?'keyword':'');i+=word[0].length;continue;}const number=line.slice(i).match(/^(?:&H[0-9a-f]+|\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)/i);if(number){out+=emit(number[0],i,'number');i+=number[0].length;continue;}out+=emit(c,i);i++;}
  if(selectionStart<=line.length&&selectionEnd>line.length)out+='<span class="code-selection"> </span>';return out||' ';
}
export function procedures(code){const result=[];String(code).split('\n').forEach((line,index)=>{const m=line.match(/^\s*(?:(?:Public|Private|Friend|Static)\s+)*(Sub|Function|Property\s+(?:Get|Let|Set))\s+(\w+)/i);if(m)result.push({name:m[2],kind:m[1],line:index+1});});return result;}
export function renameSymbol(code,oldName,newName,{events=true}={}){const target=lower(oldName);return String(code).split('\n').map(line=>{let result='',i=0;while(i<line.length){if(line[i]==="'"||/^Rem(?:\s|$)/i.test(line.slice(i))&&(i===0||/[\s:]/.test(line[i-1]))){result+=line.slice(i);break;}if(line[i]==='"'){let j=i+1;while(j<line.length){if(line[j++]==='"'){if(line[j]==='"'){j++;continue;}break;}}result+=line.slice(i,j);i=j;continue;}const m=line.slice(i).match(/^[A-Za-z_][A-Za-z0-9_]*/);if(m){const word=m[0],key=lower(word);result+=key===target?newName:events&&key.startsWith(target+'_')?newName+word.slice(oldName.length):word;i+=word.length;}else result+=line[i++];}return result;}).join('\n');}
export function formatCode(code,tabWidth=4){
  const stack=[];return String(code).split('\n').map(line=>{const text=line.trim();if(!text)return '';let depth=stack.length;
    const closing=text.match(/^(End\s+(Sub|Function|Property|If|Select|With|Type|Enum)|Next\b|Loop\b|Wend\b)/i);
    if(closing){if(/^End\s+Select/i.test(text)&&stack.at(-1)==='case')stack.pop();stack.pop();depth=stack.length;}
    else if(/^Case\b/i.test(text)){if(stack.at(-1)==='case')stack.pop();depth=stack.length;stack.push('case');}
    else if(/^(Else\b|ElseIf\b)/i.test(text))depth=Math.max(0,stack.length-1);
    else if(/^(?:(?:Public|Private|Friend|Static)\s+)*(?:Sub|Function|Property\s+(?:Get|Let|Set)|Type|Enum)\b/i.test(text)||/^(?:For\b|Do(?:\s|$)|While\b|With\b|Select\s+Case\b)/i.test(text)||/^If\b.*\bThen\s*(?:'.*)?$/i.test(text))stack.push(/^Select/i.test(text)?'select':'block');
    return ' '.repeat(Math.min(Math.max(depth,0),40)*tabWidth)+text;
  }).join('\n');
}
export function defaultEventSignature(type,event){if(event==='KeyDown'||event==='KeyUp')return 'KeyCode As Integer, Shift As Integer';if(event==='KeyPress')return 'KeyAscii As Integer';if(['MouseDown','MouseMove','MouseUp'].includes(event))return 'Button As Integer, Shift As Integer, X As Single, Y As Single';if(event==='QueryUnload')return 'Cancel As Integer, UnloadMode As Integer';if(event==='Unload')return 'Cancel As Integer';if(event==='NodeClick')return 'ByVal Node As Object';if(event==='ItemClick')return 'ByVal Item As Object';if(event==='ButtonClick')return 'ByVal Button As Object';if(event==='DateClick')return 'ByVal DateClicked As Date';return '';}
