import {Win32Error,integer,unsigned} from './core.js';
/** App-private registry: no machine registry is read or modified. */
export function installRegistry(w){
  const m=w.memory,h=w.handles,roots=new Map([[0x80000000,'HKCR'],[0x80000001,'HKCU'],[0x80000002,'HKLM'],[0x80000003,'HKU'],[0x80000005,'HKCC']]);
  const store=w.registry=new Map([...roots.values()].map(name=>[name,{name,values:new Map()}]));
  const allowed=0xf003f; // KEY_ALL_ACCESS excluding WOW64 view selectors.
  const keyOf=(handle,access=0)=>{handle=unsigned(handle);if(roots.has(handle))return roots.get(handle);const e=h.get(handle,'registry');if((e.access&access)!==access)throw new Win32Error('Registry handle access denied',5);if(!store.has(e.path))throw new Win32Error('Registry key was deleted',1018);return e.path;};
  const sub=(base,name)=>{const parts=String(name).replace(/\//g,'\\').split('\\').filter(Boolean);if(parts.some(p=>p==='.'||p==='..'))throw new Win32Error('Invalid registry key');return base+(parts.length?'\\'+parts.join('\\').toLowerCase():'');};
  const save=()=>w.options.onRegistryChange?.(w.registrySnapshot());
  const add=(name,arity,fn)=>w.register('advapi32',name,fn,{arity,statusError:true,mode:'emulated',notes:'Isolated application registry, not the operating-system registry.'});
  const aw=(name,arity,fn)=>{for(const wide of [false,true])add(name+(wide?'W':'A'),arity,(...a)=>fn(wide,...a));};
  const accessOf=access=>{access=unsigned(access);if(access&~allowed)throw new Win32Error('Unsupported registry access flags',50);return access;};
  aw('RegCreateKeyEx',9,(wide,root,name,reserved,klass,options,access,security,result,disposition)=>{if(reserved||klass||options||security)throw new Win32Error('Registry security/classes/options are not supported',50);access=accessOf(access);m.view(result,4);if(disposition)m.view(disposition,4);const base=keyOf(root,4),path=sub(base,m.string(name,wide)),existed=store.has(path),parts=path.split('\\');for(let i=1;i<=parts.length;i++){const p=parts.slice(0,i).join('\\');if(!store.has(p))store.set(p,{name:parts[i-1],values:new Map()});}const handle=h.add('registry',{path,access});m.writeU32(result,handle);if(disposition)m.writeU32(disposition,existed?2:1);save();return 0;});
  aw('RegOpenKeyEx',5,(wide,root,name,options,access,result)=>{if(options)throw new Win32Error('Registry options unsupported',50);access=accessOf(access);m.view(result,4);const path=sub(keyOf(root),m.string(name,wide));if(!store.has(path))return 2;m.writeU32(result,h.add('registry',{path,access}));return 0;});
  add('RegCloseKey',1,handle=>{if(!roots.has(unsigned(handle)))h.close(handle,'registry');return 0;});
  aw('RegSetValueEx',6,(wide,handle,name,reserved,type,data,size)=>{if(reserved)throw new Win32Error('Reserved must be zero');type=unsigned(type);if(![1,2,3,4,7,11].includes(type))throw new Win32Error('Registry type not implemented',50);size=integer(size,0,w.maxFileBytes);const path=keyOf(handle,2),bytes=size?m.bytes(data,size):new Uint8Array();if(type===4&&size!==4||type===11&&size!==8)throw new Win32Error('Invalid registry integer size');if(wide&&[1,2,7].includes(type)&&size%2)throw new Win32Error('Invalid Unicode registry value');const value=[1,2,7].includes(type)?m.decode(bytes,wide):Array.from(bytes);store.get(path).values.set(m.string(name,wide).toLowerCase(),{name:m.string(name,wide),type,value});save();return 0;});
  aw('RegQueryValueEx',6,(wide,handle,name,reserved,typeOut,data,sizeOut)=>{if(reserved||data&&!sizeOut)throw new Win32Error('Invalid registry query arguments');const path=keyOf(handle,1),entry=store.get(path).values.get(m.string(name,wide).toLowerCase());if(!entry)return 2;const bytes=typeof entry.value==='string'?m.stringBytes(entry.value,wide):Uint8Array.from(entry.value);if(typeOut)m.view(typeOut,4);let capacity=sizeOut?m.readU32(sizeOut):0;if(data)m.bytes(data,capacity);if(typeOut)m.writeU32(typeOut,entry.type);if(sizeOut)m.writeU32(sizeOut,bytes.length);if(!data)return 0;if(capacity<bytes.length)return 234;m.bytes(data,bytes.length).set(bytes);return 0;});
  aw('RegDeleteValue',2,(wide,handle,name)=>{const path=keyOf(handle,2);if(!store.get(path).values.delete(m.string(name,wide).toLowerCase()))return 2;save();return 0;});
  aw('RegDeleteKey',2,(wide,handle,name)=>{const path=sub(keyOf(handle,4),m.string(name,wide));if(roots.has(unsigned(handle))&&!m.string(name,wide))return 5;if(!store.has(path))return 2;if([...store.keys()].some(k=>k.startsWith(path+'\\')))return 5;store.delete(path);save();return 0;});
  aw('RegEnumKeyEx',8,(wide,handle,index,name,size,reserved,klass,classSize,time)=>{if(reserved||klass||classSize||time)throw new Win32Error('Registry class/timestamp enumeration is not implemented',50);const path=keyOf(handle,8),children=[...store].filter(([k])=>k.startsWith(path+'\\')&&!k.slice(path.length+1).includes('\\')),entry=children[integer(index)]?.[1];if(!entry)return 259;const capacity=m.readU32(size),n=m.stringBytes(entry.name,wide).length/(wide?2:1);if(capacity<=n)return 234;m.putString(name,entry.name,capacity,wide);m.writeU32(size,n);return 0;});
}
