import {Win32Error,integer,unsigned} from './core.js';
export function colorRef(value){const n=unsigned(value);return '#'+[n&255,n>>>8&255,n>>>16&255].map(v=>v.toString(16).padStart(2,'0')).join('');}
export function installGDI(w){
  const h=w.handles,m=w.memory,add=(name,arity,fn,options={})=>w.register('gdi32',name,fn,{arity,mode:'browser',...options});
  const stocks=new Map(),stock=(index,type,value)=>stocks.set(index,h.add(type,{...value,stock:true}));
  stock(0,'brush',{color:0xffffff});stock(4,'brush',{color:0});stock(5,'brush',{null:true});stock(6,'pen',{color:0xffffff,width:1});stock(7,'pen',{color:0,width:1});stock(8,'pen',{null:true,width:1});
  add('GetStockObject',1,index=>{if(!stocks.has(Number(index)))throw new Win32Error('Stock object is not implemented',50);return stocks.get(Number(index));});
  add('CreateSolidBrush',1,color=>h.add('brush',{color:unsigned(color)}));
  add('CreatePen',3,(style,width,color)=>{if(![0,5].includes(Number(style)))throw new Win32Error('Only solid and null pens are supported',50);return h.add('pen',{null:Number(style)===5,width:Math.max(1,integer(width,0,4096)),color:unsigned(color)});});
  const dc=handle=>h.get(handle,'dc');
  const draw=(state,operation,args)=>{const style={pen:h.get(state.pen,'pen'),brush:h.get(state.brush,'brush'),textColor:state.textColor,backgroundColor:state.backgroundColor,backgroundMode:state.backgroundMode};if(state.window.draw)return state.window.draw(operation,args,style);const ctx=state.window.context||state.window.node?.getContext?.('2d');if(!ctx)throw new Win32Error('No drawing adapter or Canvas2D context',50);ctx.save();try{ctx.strokeStyle=colorRef(style.pen.color||0);ctx.lineWidth=style.pen.width||1;ctx.fillStyle=colorRef(style.brush.color||0);switch(operation){case 'line':ctx.beginPath();ctx.moveTo(args[0],args[1]);ctx.lineTo(args[2],args[3]);if(!style.pen.null)ctx.stroke();break;case 'rect':if(!style.brush.null)ctx.fillRect(args[0],args[1],args[2]-args[0],args[3]-args[1]);if(!style.pen.null)ctx.strokeRect(args[0],args[1],args[2]-args[0],args[3]-args[1]);break;case 'ellipse':ctx.beginPath();ctx.ellipse((args[0]+args[2])/2,(args[1]+args[3])/2,Math.abs(args[2]-args[0])/2,Math.abs(args[3]-args[1])/2,0,0,Math.PI*2);if(!style.brush.null)ctx.fill();if(!style.pen.null)ctx.stroke();break;case 'pixel':ctx.fillStyle=colorRef(args[2]);ctx.fillRect(args[0],args[1],1,1);break;case 'text':ctx.font='12px Arial';ctx.textBaseline='top';if(style.backgroundMode===2){ctx.fillStyle=colorRef(style.backgroundColor);ctx.fillRect(args[0],args[1],ctx.measureText(args[2]).width,14);}ctx.fillStyle=colorRef(style.textColor);ctx.fillText(args[2],args[0],args[1]);break;default:throw new Win32Error('Unsupported drawing operation',50);}}finally{ctx.restore();}};
  w.register('user32','GetDC',handle=>{const window=h.get(handle,'window');if(!window.draw&&!window.context&&!window.node?.getContext)throw new Win32Error('No drawing adapter',50);return h.add('dc',{window,handle:Number(handle),pen:stocks.get(7),brush:stocks.get(0),x:0,y:0,textColor:0,backgroundColor:0xffffff,backgroundMode:2});},{arity:1,mode:'browser'});
  w.register('user32','ReleaseDC',(handle,hdc)=>{const state=dc(hdc);if(state.handle!==Number(handle))throw new Win32Error('DC does not belong to window',6);h.close(hdc,'dc');return 1;},{arity:2,mode:'browser'});
  add('SelectObject',2,(handle,object)=>{const state=dc(handle),entry=h.entries.get(Number(object));if(!entry||!['pen','brush'].includes(entry.type))throw new Win32Error('Invalid pen or brush',6);const old=state[entry.type];state[entry.type]=Number(object);return old;});
  add('DeleteObject',1,object=>{const entry=h.entries.get(Number(object));if(!entry||!['pen','brush'].includes(entry.type))throw new Win32Error('Invalid GDI object',6);if(entry.value.stock)return 1;if([...h.entries.values()].some(e=>e.type==='dc'&&(e.value.pen===Number(object)||e.value.brush===Number(object))))return 0;h.close(object,entry.type);return 1;});
  add('MoveToEx',4,(handle,x,y,old)=>{const state=dc(handle);if(old){m.writeI32(old,state.x);m.writeI32(old+4,state.y);}state.x=Number(x);state.y=Number(y);return 1;});
  add('LineTo',3,(handle,x,y)=>{const state=dc(handle);draw(state,'line',[state.x,state.y,Number(x),Number(y)]);state.x=Number(x);state.y=Number(y);return 1;});
  for(const [name,operation]of [['Rectangle','rect'],['Ellipse','ellipse']])add(name,5,(handle,l,t,r,b)=>{draw(dc(handle),operation,[l,t,r,b].map(Number));return 1;});
  add('SetPixel',4,(handle,x,y,color)=>{draw(dc(handle),'pixel',[Number(x),Number(y),unsigned(color)]);return unsigned(color)&0xffffff;},{failure:0xffffffff});
  for(const [name,field]of [['SetTextColor','textColor'],['SetBkColor','backgroundColor']])add(name,2,(handle,color)=>{const state=dc(handle),old=state[field];state[field]=unsigned(color)&0xffffff;return old;},{failure:0xffffffff});
  add('SetBkMode',2,(handle,mode)=>{integer(mode,1,2);const state=dc(handle),old=state.backgroundMode;state.backgroundMode=Number(mode);return old;});
  for(const wide of [false,true])add('TextOut'+(wide?'W':'A'),5,(handle,x,y,p,n)=>{n=integer(n,0,m.maxBytes/(wide?2:1));const text=typeof p==='string'?p.slice(0,n):m.decode(m.bytes(p,n*(wide?2:1)),wide);draw(dc(handle),'text',[Number(x),Number(y),text]);return 1;},{notes:'Browser font metrics and rasterization, not pixel-identical GDI.'});
  add('GetDeviceCaps',2,(handle,index)=>{const state=dc(handle),r=state.window.getClientRect?.(),n=state.window.node;const values={8:r?.width??n?.clientWidth??0,10:r?.height??n?.clientHeight??0,12:32,14:1,88:96,90:96};if(!(index in values))throw new Win32Error('Device capability not implemented',50);return values[index];});
}
