import test from 'node:test';
import assert from 'node:assert/strict';
import {createWin32,RegionStore,WIN32_CONSTANTS as C} from '../src/index.js';
const g=(w,n,...a)=>w.invoke('gdi32',n,a),u=(w,n,...a)=>w.invoke('user32',n,a);
function context(t,options){const w=createWin32(options);t.after(()=>w.dispose());return w;}
function pts(w,points){const p=w.memory.alloc(points.length*8),v=w.memory.view(p,points.length*8);points.forEach(([x,y],i)=>{v.setInt32(i*8,x,true);v.setInt32(i*8+4,y,true);});return p;}
function xf(w,a){const p=w.memory.alloc(24),v=w.memory.view(p,24);a.forEach((n,i)=>v.setFloat32(i*4,n,true));return p;}
function surface(w,width=32,height=32){const dc=g(w,'CreateCompatibleDC',0),bitmap=g(w,'CreateBitmap',width,height,1,32,0),old=g(w,'SelectObject',dc,bitmap);assert.ok(dc&&bitmap&&old);return {dc,bitmap,old};}
function rgn(w,points,mode=1){return g(w,'CreatePolygonRgn',pts(w,points),points.length,mode);}
const shape=(w,id)=>w.handles.get(id,'region').shape;
const bounds=(w,id)=>shape(w,id).bounds;
const bytes=(w,id)=>w.memory.bytes(w.handles.get(id,'bitmap').ptr,w.handles.get(id,'bitmap').size);
function window(w){const data=new Uint8ClampedArray(32*32*4),descriptor={allowVirtualRegion:true,getClientRect:()=>({width:32,height:32}),readPixels:(x,y,width,height)=>{const out=new Uint8ClampedArray(width*height*4);for(let j=0;j<height;j++)out.set(data.subarray(((j+y)*32+x)*4,((j+y)*32+x+width)*4),j*width*4);return {width,height,data:out};},writePixels:(x,y,image)=>{for(let j=0;j<image.height;j++)data.set(image.data.subarray(j*image.width*4,(j+1)*image.width*4),((j+y)*32+x)*4);}};return {id:w.registerWindow(descriptor),descriptor,data};}

test('polygon constructors preserve half-open edges and alternating/winding differences',t=>{const w=context(t),points=[[0,0],[8,0],[0,8]],r=rgn(w,points);assert.deepEqual(bounds(w,r),[0,0,8,8]);assert.equal(g(w,'PtInRegion',r,7,0),1);assert.equal(g(w,'PtInRegion',r,7,1),0);const loop=[[0,0],[6,0],[6,6],[0,6]],twice=[...loop,...loop];assert.equal(shape(w,rgn(w,twice,1)).count,0);assert.equal(shape(w,rgn(w,twice,2)).count,1);});
test('polygon clockwise/counterclockwise inputs, negatives and repeated endpoints are stable',()=>{const s=new RegionStore(),p=[[-6,-4],[5,-2],[2,5],[-6,-4]];assert.ok(s.equal(s.polygons([p],2),s.polygons([[...p].reverse()],2)));});
test('multipolygon contours create holes and validate all POINT buffers before allocating',t=>{const w=context(t),p=pts(w,[[0,0],[12,0],[12,12],[0,12],[3,3],[9,3],[9,9],[3,9]]),counts=w.memory.alloc(8);w.memory.writeI32(counts,4);w.memory.writeI32(counts+4,4);const r=g(w,'CreatePolyPolygonRgn',p,counts,2,1);assert.ok(r);assert.equal(g(w,'PtInRegion',r,4,4),0);const before=w.handles.entries.size;w.memory.writeI32(counts+4,100);assert.equal(g(w,'CreatePolyPolygonRgn',p,counts,2,1),0);assert.equal(w.handles.entries.size,before);});
for(const name of ['CreateEllipticRgn','CreateRoundRectRgn'])test(name+' creates bounded curved geometry with excluded corner pixels',t=>{const w=context(t),r=g(w,name,...(name==='CreateEllipticRgn'?[0,0,24,18]:[0,0,24,18,8,8]));assert.ok(r);assert.equal(g(w,'PtInRegion',r,12,9),1);assert.equal(g(w,'PtInRegion',r,0,0),0);assert.equal(g(w,'PtInRegion',r,24,9),0);assert.equal(g(w,'DeleteObject',r),1);});
test('curved constructor checks reject excessive scan conversion without allocating a handle',t=>{const w=context(t,{maxRegionWork:64}),n=w.handles.entries.size;assert.equal(g(w,'CreateEllipticRgn',0,0,100,10000),0);assert.equal(w.lastError,8);assert.equal(w.handles.entries.size,n);});
test('ellipse indirect equals direct and region geometry survives input buffer reuse',t=>{const w=context(t),p=pts(w,[[0,0],[24,18]]),a=g(w,'CreateEllipticRgnIndirect',p),b=g(w,'CreateEllipticRgn',0,0,24,18);w.memory.bytes(p,16).fill(0);assert.equal(g(w,'EqualRgn',a,b),1);});
test('FrameRgn handles outer and hole borders without modifying the original HRGN',t=>{const w=context(t),s=surface(w),r=g(w,'CreateRectRgn',0,0,20,20),hole=g(w,'CreateRectRgn',6,6,14,14);g(w,'CombineRgn',r,r,hole,4);const before=shape(w,r),brush=g(w,'CreateSolidBrush',255);assert.equal(g(w,'FrameRgn',s.dc,r,brush,2,2),1);assert.equal(g(w,'GetPixel',s.dc,0,0),255);assert.equal(g(w,'GetPixel',s.dc,3,3),0);assert.equal(g(w,'GetPixel',s.dc,5,8),255);assert.equal(g(w,'GetPixel',s.dc,8,8),0);assert.equal(shape(w,r),before);});
test('world transforms require advanced mode and restore atomically with SaveDC',t=>{const w=context(t),s=surface(w),a=xf(w,[2,0,0,3,4,5]),out=w.memory.alloc(24);assert.equal(g(w,'SetWorldTransform',s.dc,a),0);assert.equal(g(w,'SetGraphicsMode',s.dc,2),1);assert.equal(g(w,'SetWorldTransform',s.dc,a),1);assert.equal(g(w,'SetGraphicsMode',s.dc,1),0);g(w,'SaveDC',s.dc);g(w,'ModifyWorldTransform',s.dc,0,1);assert.equal(g(w,'SetGraphicsMode',s.dc,1),2);g(w,'RestoreDC',s.dc,-1);g(w,'GetWorldTransform',s.dc,out);assert.deepEqual([...new Float32Array(w.memory.bytes(out,24).slice().buffer)],[2,0,0,3,4,5]);});
test('LPtoDP/DPtoLP combine world transform, window origin, extents and viewport',t=>{const w=context(t),s=surface(w),p=pts(w,[[1,2],[3,4]]);g(w,'SetMapMode',s.dc,8);g(w,'SetWindowExtEx',s.dc,2,2,0);g(w,'SetViewportExtEx',s.dc,4,6,0);g(w,'SetWindowOrgEx',s.dc,1,1,0);g(w,'SetViewportOrgEx',s.dc,5,7,0);g(w,'LPtoDP',s.dc,p,2);assert.deepEqual([w.memory.readI32(p),w.memory.readI32(p+4)],[5,10]);g(w,'DPtoLP',s.dc,p,2);assert.deepEqual([w.memory.readI32(p),w.memory.readI32(p+4),w.memory.readI32(p+8),w.memory.readI32(p+12)],[1,2,3,4]);});
test('singular and nonfinite transforms do not replace existing coordinate mapping',t=>{const w=context(t),s=surface(w);g(w,'SetGraphicsMode',s.dc,2);const initial=w.handles.get(s.dc,'dc').world;for(const a of [[1,2,2,4,0,0],[NaN,0,0,1,0,0]]){assert.equal(g(w,'SetWorldTransform',s.dc,xf(w,a)),0);assert.equal(w.handles.get(s.dc,'dc').world,initial);}});
test('affine region transforms support rotation, reflection, shear and fractional translations',()=>{const r=new RegionStore(),a=r.rectangle(1,2,5,6);for(const matrix of [[0,1,-1,0,12,0],[-1,0,0,1,12,0],[1,0,1,1,.5,.5]]){const transformed=r.transform(a,matrix);assert.ok(transformed.count);assert.ok(transformed.bands.every(b=>b.spans.every(Number.isInteger)));}assert.deepEqual(r.transform(a,[0,1,-1,0,12,0]).bounds,[6,1,10,5]);});
test('transformed bitmap copies sample source pixels and preserve destination outside parallelogram',t=>{const w=context(t),a=surface(w,4,4),b=surface(w);g(w,'SelectObject',a.dc,g(w,'CreateSolidBrush',255));g(w,'PatBlt',a.dc,0,0,4,4,C.PATCOPY);g(w,'SetGraphicsMode',b.dc,2);g(w,'SetWorldTransform',b.dc,xf(w,[1,0,1,1,5,5]));assert.equal(g(w,'BitBlt',b.dc,0,0,4,4,a.dc,0,0,C.SRCCOPY),1);g(w,'ModifyWorldTransform',b.dc,0,1);assert.equal(g(w,'GetPixel',b.dc,7,6),255);assert.equal(g(w,'GetPixel',b.dc,5,8),0);});
test('path conversion preserves device geometry and consumes the path only on success',t=>{const w=context(t),s=surface(w);g(w,'BeginPath',s.dc);g(w,'MoveToEx',s.dc,1,1,0);g(w,'LineTo',s.dc,12,1);g(w,'LineTo',s.dc,1,12);g(w,'CloseFigure',s.dc);g(w,'EndPath',s.dc);assert.equal(g(w,'GetPath',s.dc,0,0,0),3);const r=g(w,'PathToRegion',s.dc);assert.ok(r);assert.equal(g(w,'PtInRegion',r,2,2),1);assert.equal(g(w,'GetPath',s.dc,0,0,0),-1);});
test('GetPath returns inverse-current-transform logical points and flags',t=>{const w=context(t),s=surface(w);g(w,'BeginPath',s.dc);g(w,'MoveToEx',s.dc,4,6,0);g(w,'LineTo',s.dc,10,12);g(w,'EndPath',s.dc);g(w,'SetViewportOrgEx',s.dc,2,3,0);const p=w.memory.alloc(16),flags=w.memory.alloc(2);assert.equal(g(w,'GetPath',s.dc,p,flags,2),2);assert.deepEqual([w.memory.readI32(p),w.memory.readI32(p+4)],[2,3]);assert.deepEqual([...w.memory.bytes(flags,2)],[6,2]);});
test('Bezier paths flatten with bounded precision and never publish half a path on quota error',t=>{const w=context(t,{maxPathPoints:16}),s=surface(w),p=pts(w,[[0,0],[0,24],[24,24],[24,0]]);g(w,'BeginPath',s.dc);g(w,'PolyBezier',s.dc,p,4);g(w,'EndPath',s.dc);const before=w.handles.get(s.dc,'dc').path;const result=g(w,'FlattenPath',s.dc);if(!result){assert.equal(w.lastError,8);assert.equal(w.handles.get(s.dc,'dc').path,before);}else assert.ok(g(w,'GetPath',s.dc,0,0,0)<=16);});
test('path point quota leaves path and current position unchanged',t=>{const w=context(t,{maxPathPoints:4}),s=surface(w);g(w,'BeginPath',s.dc);g(w,'MoveToEx',s.dc,1,1,0);for(let i=0;i<3;i++)g(w,'LineTo',s.dc,i,5);const before=w.handles.get(s.dc,'dc').path;assert.equal(g(w,'LineTo',s.dc,9,9),0);assert.equal(w.lastError,8);assert.equal(w.handles.get(s.dc,'dc').path,before);assert.equal(w.handles.get(s.dc,'dc').x,2);});
test('filled paths and path clipping affect real bitmap pixels',t=>{const w=context(t),s=surface(w);g(w,'SelectObject',s.dc,g(w,'CreateSolidBrush',0x123456));g(w,'BeginPath',s.dc);g(w,'Rectangle',s.dc,2,2,12,12);g(w,'EndPath',s.dc);assert.equal(g(w,'FillPath',s.dc),1);assert.equal(g(w,'GetPixel',s.dc,4,4),0x123456);g(w,'BeginPath',s.dc);g(w,'Rectangle',s.dc,4,4,8,8);g(w,'EndPath',s.dc);assert.equal(g(w,'SelectClipPath',s.dc,5),1);assert.equal(g(w,'PtVisible',s.dc,3,3),0);assert.equal(g(w,'PtVisible',s.dc,5,5),1);});
test('path operations enforce open/closed lifecycle independently of SaveDC',t=>{const w=context(t),s=surface(w);assert.equal(g(w,'EndPath',s.dc),0);g(w,'BeginPath',s.dc);g(w,'MoveToEx',s.dc,0,0,0);g(w,'SaveDC',s.dc);g(w,'LineTo',s.dc,4,4);g(w,'RestoreDC',s.dc,-1);g(w,'EndPath',s.dc);assert.equal(g(w,'GetPath',s.dc,0,0,0),2);g(w,'AbortPath',s.dc);assert.equal(g(w,'FillPath',s.dc),0);});
test('stock font handles are lazy and process startup remains valid at the original quota',t=>{const w=context(t,{maxHandles:6});assert.equal(w.handles.entries.size,6);assert.equal(g(w,'GetStockObject',13),0);assert.equal(w.lastError,8);});
test('LOGFONT ANSI/Unicode creation, GetObject, selection and saved font lifetime',t=>{const w=context(t),s=surface(w),p=w.memory.alloc(92);w.memory.writeI32(p,-18);w.memory.writeI32(p+16,700);w.memory.bytes(p+20,1)[0]=1;w.memory.putString(p+28,'Test Ω',32,true);const f=g(w,'CreateFontIndirectW',p),old=g(w,'SelectObject',s.dc,f);assert.ok(f&&old);assert.equal(g(w,'GetObjectType',f),6);assert.equal(g(w,'GetObjectW',f,0,0),92);g(w,'SaveDC',s.dc);g(w,'SelectObject',s.dc,old);assert.equal(g(w,'DeleteObject',f),0);g(w,'RestoreDC',s.dc,-1);g(w,'SelectObject',s.dc,old);assert.equal(g(w,'DeleteObject',f),1);});
test('font buffer validation and text option errors are explicit, without fake glyph output',t=>{const w=context(t),s=surface(w);assert.equal(g(w,'CreateFontIndirectW',w.memory.alloc(8)),0);const before=bytes(w,s.bitmap).slice();assert.equal(g(w,'ExtTextOutW',s.dc,0,0,16,0,0,0,0),0);assert.equal(w.lastError,50);assert.deepEqual(bytes(w,s.bitmap),before);});
test('font metrics require an actual font backend in a headless pure Node process',t=>{const w=context(t),s=surface(w),p=w.memory.alloc(60);assert.equal(g(w,'GetTextMetricsW',s.dc,p),0);assert.equal(w.lastError,50);});
test('SetWindowRgn transfers ownership, preserves copies and frees replaced regions',t=>{const w=context(t),win=window(w),r=g(w,'CreateRectRgn',1,1,20,20),copy=g(w,'CreateRectRgn',0,0,0,0);assert.equal(u(w,'SetWindowRgn',win.id,r,0),1);assert.equal(g(w,'DeleteObject',r),0);assert.equal(w.lastError,5);assert.equal(g(w,'SetRectRgn',r,0,0,1,1),0);assert.equal(u(w,'GetWindowRgn',win.id,copy),2);assert.deepEqual(bounds(w,copy),[1,1,20,20]);assert.equal(u(w,'SetWindowRgn',win.id,0,0),1);assert.equal(w.handles.has(r),false);});
test('window shape failure retains caller ownership and previously installed shape',t=>{const w=context(t),id=w.registerWindow({}),r=g(w,'CreateRectRgn',0,0,3,3);assert.equal(u(w,'SetWindowRgn',id,r,0),0);assert.equal(w.lastError,50);assert.equal(g(w,'DeleteObject',r),1);});
test('window shape becomes a mandatory drawing clip that application clipping cannot remove',t=>{const w=context(t),win=window(w),r=g(w,'CreateRectRgn',4,4,12,12);u(w,'SetWindowRgn',win.id,r,0);const d=u(w,'GetDC',win.id);g(w,'SelectObject',d,g(w,'CreateSolidBrush',255));g(w,'PatBlt',d,0,0,32,32,C.PATCOPY);assert.equal(win.data[(5*32+5)*4],255);assert.equal(win.data[0],0);g(w,'SelectClipRgn',d,0);assert.equal(g(w,'PtVisible',d,0,0),0);});
test('window unregister cancels callbacks and cleans owned regions and DCs',t=>{const w=context(t),win=window(w),r=g(w,'CreateRectRgn',1,1,8,8);u(w,'SetWindowRgn',win.id,r,0);const d=u(w,'GetDC',win.id);w.unregisterWindow(win.id);assert.equal(w.handles.has(r),false);assert.equal(w.handles.has(d),false);});
test('invalidate/validate union and subtract complex update geometry',t=>{const w=context(t),win=window(w),r=g(w,'CreateRectRgn',4,4,12,12),out=g(w,'CreateRectRgn',0,0,0,0);u(w,'InvalidateRect',win.id,0,1);u(w,'ValidateRgn',win.id,r);assert.equal(u(w,'GetUpdateRgn',win.id,out,0),3);assert.equal(g(w,'PtInRegion',out,5,5),0);assert.equal(g(w,'PtInRegion',out,0,0),1);});
test('BeginPaint snapshots the update region and EndPaint preserves later invalidations',t=>{const w=context(t),win=window(w),ps=w.memory.alloc(64),p=pts(w,[[2,3],[12,13]]);u(w,'InvalidateRect',win.id,p,1);const d=u(w,'BeginPaint',win.id,ps);assert.ok(d);assert.equal(w.memory.readU32(ps),d);assert.deepEqual([8,12,16,20].map(o=>w.memory.readI32(ps+o)),[2,3,12,13]);assert.equal(g(w,'PtVisible',d,1,1),0);assert.equal(g(w,'PtVisible',d,3,4),1);u(w,'InvalidateRect',win.id,0,0);assert.equal(u(w,'ReleaseDC',win.id,d),0);assert.equal(u(w,'EndPaint',win.id,ps),1);assert.equal(u(w,'GetUpdateRect',win.id,0,0),1);assert.equal(w.handles.has(d),false);});
test('bad paint buffers and nested BeginPaint fail without consuming pending geometry',t=>{const w=context(t),win=window(w);u(w,'InvalidateRect',win.id,0,1);assert.equal(u(w,'BeginPaint',win.id,w.memory.alloc(4)),0);assert.equal(u(w,'GetUpdateRect',win.id,0,0),1);const p=w.memory.alloc(64);assert.ok(u(w,'BeginPaint',win.id,p));const before=w.handles.entries.size;assert.equal(u(w,'BeginPaint',win.id,p),0);assert.equal(w.handles.entries.size,before);assert.equal(u(w,'EndPaint',win.id,p),1);});
test('UpdateWindow dispatches only pending paints and prevents recursive notification',async t=>{const w=context(t),win=window(w);let calls=0;win.descriptor.requestPaint=async()=>{calls++;await u(w,'UpdateWindow',win.id);u(w,'ValidateRect',win.id,0);};assert.equal(await u(w,'UpdateWindow',win.id),1);assert.equal(calls,0);u(w,'InvalidateRect',win.id,0,0);assert.equal(await u(w,'UpdateWindow',win.id),1);assert.equal(calls,1);});
test('GetDCEx copies and consumes its region with explicit unsupported flag diagnostics',t=>{const w=context(t),win=window(w),r=g(w,'CreateRectRgn',2,2,8,8),d=u(w,'GetDCEx',win.id,r,128);assert.ok(d);assert.equal(w.handles.has(r),false);assert.equal(g(w,'PtVisible',d,3,3),1);assert.equal(g(w,'PtVisible',d,0,0),0);assert.equal(u(w,'GetDCEx',win.id,0,0x100000),0);assert.equal(w.lastError,50);});

test('PolylineTo and PolyBezierTo continue an existing open path without inserting MoveTo',t=>{const w=context(t),s=surface(w);g(w,'BeginPath',s.dc);g(w,'MoveToEx',s.dc,1,1,0);g(w,'PolylineTo',s.dc,pts(w,[[4,1],[4,4]]),2);g(w,'PolyBezierTo',s.dc,pts(w,[[4,8],[1,8],[1,4]]),3);g(w,'CloseFigure',s.dc);g(w,'EndPath',s.dc);const entries=w.handles.get(s.dc,'dc').path.entries;assert.deepEqual(entries.map(e=>e.type),[6,2,2,4,4,5]);assert.ok(g(w,'PathToRegion',s.dc));});
test('polygon path closes exactly its last vertex and fills all sides',t=>{const w=context(t),s=surface(w);g(w,'BeginPath',s.dc);assert.equal(g(w,'Polygon',s.dc,pts(w,[[1,1],[10,1],[10,10],[1,10]]),4),1);g(w,'EndPath',s.dc);assert.deepEqual(w.handles.get(s.dc,'dc').path.entries.map(e=>e.type),[6,2,2,3]);assert.ok(g(w,'PathToRegion',s.dc));});
test('StrokePath and WidenPath render nonempty bounded strokes with no temporary handles',t=>{const w=context(t),s=surface(w),pen=g(w,'CreatePen',0,4,255);g(w,'SelectObject',s.dc,pen);for(const op of ['StrokePath','WidenPath']){g(w,'BeginPath',s.dc);g(w,'MoveToEx',s.dc,4,4,0);g(w,'LineTo',s.dc,20,4);g(w,'EndPath',s.dc);const count=w.handles.entries.size;assert.equal(g(w,op,s.dc),1);assert.equal(w.handles.entries.size,count);if(op==='WidenPath'){const r=g(w,'PathToRegion',s.dc);assert.equal(g(w,'PtInRegion',r,10,4),1);g(w,'DeleteObject',r);}}assert.equal(g(w,'GetPixel',s.dc,10,4),255);});
test('BeginPaint preserves re-invalidation issued by an erase callback',t=>{const w=context(t),win=window(w),ps=w.memory.alloc(64);win.descriptor.eraseBackground=()=>{assert.equal(u(w,'BeginPaint',win.id,w.memory.alloc(64)),0);u(w,'InvalidateRect',win.id,0,1);return true;};u(w,'InvalidateRect',win.id,0,1);assert.ok(u(w,'BeginPaint',win.id,ps));assert.equal(u(w,'GetUpdateRect',win.id,0,0),1);assert.equal(w.memory.readI32(ps+4),0);u(w,'EndPaint',win.id,ps);assert.equal(win.descriptor.gdiPaint.erase,true);});
test('RedrawWindow rejects unsupported nonclient presentation before invalidation',async t=>{const w=context(t),win=window(w);assert.equal(await u(w,'RedrawWindow',win.id,0,0,1|1024),0);assert.equal(w.lastError,50);assert.equal(u(w,'GetUpdateRect',win.id,0,0),0);});
test('RedrawWindow dispatches internal and nonclient paints and honors cancellation flags',async t=>{const w=context(t),win=window(w);let n=0,p=0;win.descriptor.requestNonClientPaint=()=>{n++;};win.descriptor.requestPaint=()=>{p++;u(w,'ValidateRect',win.id,0);};assert.equal(await u(w,'RedrawWindow',win.id,0,0,2|256),1);assert.equal(p,1);assert.equal(await u(w,'RedrawWindow',win.id,0,0,1|1024|256),1);assert.equal(n,1);assert.equal(p,2);await u(w,'RedrawWindow',win.id,0,0,2);await u(w,'RedrawWindow',win.id,0,0,16);await new Promise(r=>setTimeout(r,5));assert.equal(p,2);});
test('RedrawWindow clips translated updates recursively across owned descendants',async t=>{const w=context(t),a=window(w),b=window(w),c=window(w),p=pts(w,[[10,10],[20,20]]),r=g(w,'CreateRectRgn',0,0,0,0);a.descriptor.clientOrigin=()=>[0,0];b.descriptor.parent=a.id;b.descriptor.clientOrigin=()=>[5,5];c.descriptor.parent=b.id;c.descriptor.clientOrigin=()=>[8,8];await u(w,'RedrawWindow',a.id,p,0,1|128);u(w,'GetUpdateRgn',c.id,r,0);assert.deepEqual(bounds(w,r),[2,2,12,12]);});
test('window paint callbacks are cancelled on process disposal',async()=>{const w=createWin32(),win=window(w);let count=0;win.descriptor.requestPaint=()=>count++;u(w,'InvalidateRect',win.id,0,1);w.dispose();await new Promise(r=>setTimeout(r,5));assert.equal(count,0);assert.equal(w.handles.entries.size,0);});

test('GetTextFace counts the terminating NUL, including truncated buffers',t=>{const w=context(t),s=surface(w),p=w.memory.alloc(64);const required=g(w,'GetTextFaceW',s.dc,0,0);for(const [n,result]of [[0,0],[1,1],[2,2],[32,required]]){assert.equal(g(w,'GetTextFaceW',s.dc,n,p),result);if(n)assert.equal(w.memory.view(p,64).getUint16((result-1)*2,true),0);}assert.equal(g(w,'GetTextFaceA',s.dc,32,p),required);});
test('GetUpdateRect erase preserves invalidations queued inside the erase callback',t=>{const w=context(t),win=window(w);win.descriptor.eraseBackground=()=>{u(w,'InvalidateRect',win.id,0,1);return true;};u(w,'InvalidateRect',win.id,0,1);assert.equal(u(w,'GetUpdateRect',win.id,0,1),1);assert.equal(win.descriptor.gdiPaint.erase,true);});
test('RDW_ERASENOW preserves a new erase request received while erasing',async t=>{const w=context(t),win=window(w);win.descriptor.eraseBackground=()=>{u(w,'InvalidateRect',win.id,0,1);return true;};u(w,'InvalidateRect',win.id,0,1);assert.equal(await u(w,'RedrawWindow',win.id,0,0,512),1);assert.equal(win.descriptor.gdiPaint.erase,true);});
