import {arrangeFormEdit} from '../layout/model.js';
import {layoutEnabled} from '../layout/contract.js';
import {renderAnchorGuides} from '../layout/designer-tools.js';
import { Signal, el, clone, lower } from '../core/core.js';
import { createControl, newId, uniqueName } from '../project/model.js';
import { BrowserForm } from '../controls/controls.js';
import { GraphicsSurface } from '../graphics/surface.js';
import {applyTheme} from '../theme/theme.js';

export class FormDesigner extends Signal {
  constructor(container,options={}){super();this.container=container;this.options=options;this.selection=new Set();this.tool='Pointer';this.zoom=1;this.clipboard=[];this.showTabOrder=false;this.tabOrderIndex=0;this.root=el('div',{class:'designer-scroll',tabindex:0,'aria-label':'Form designer'});this.plane=el('div',{class:'designer-plane'});this.root.append(this.plane);container.append(this.root);this.root.addEventListener('pointerdown',e=>this.pointerDown(e));this.root.addEventListener('keydown',e=>this.keydown(e));this.root.addEventListener('dblclick',e=>{const node=e.target.closest('[data-control-id]');const control=this.module?.form.controls.find(c=>c.id===node?.dataset.controlId);this.emit('event',{control:control||this.selected()[0]||null});});this.root.addEventListener('contextmenu',e=>{e.preventDefault();this.emit('contextmenu',{x:e.clientX,y:e.clientY,event:e});});this.resizeObserver=new ResizeObserver(()=>this.scheduleSelection());this.resizeObserver.observe(this.root);}
  setDocument(module,project){this.module=module;this.project=project;this.settings=project.settings||{};applyTheme(this.root,this.settings.theme);const ids=new Set(module.form.controls.map(c=>c.id));this.selection=new Set([...this.selection].filter(id=>ids.has(id)));this.render();}
  render(){this.formView?.dispose();this.grid?.dispose();this.plane.replaceChildren();if(!this.module?.form)return;this.formView=new BrowserForm(this.module.form,{controlRegistry:this.options.controlRegistry,design:true,anchoring:layoutEnabled(this.project),assets:this.project.assets||{},backend:this.settings.renderer||'auto',onBackend:value=>this.emit('backend',value)});this.formView.node.classList.add('designer-form');this.formView.node.style.left='8px';this.formView.node.style.top='8px';this.formView.node.style.zIndex='1';this.plane.append(this.formView.node);this.formView.node.style.transform=`scale(${this.zoom})`;this.formView.node.style.transformOrigin='top left';this.grid=new GraphicsSurface(this.formView.content,{background:this.module.form.properties.BackColor,backend:this.settings.renderer||'auto',onBackend:value=>this.emit('backend',value)});if(this.settings.showGrid!==false)this.grid.setGrid((this.settings.gridSize||120)/15);this.grid.canvas.style.zIndex='0';this.formView.controls.forEach((c,i)=>{c.node.style.zIndex=String(i+1);c.node.style.pointerEvents='auto';});this.overlay=el('div',{class:'designer-overlay'});this.formView.content.append(this.overlay);this.formSelection=el('div',{class:'designer-form-selection'});this.plane.append(this.formSelection);this.formView.titleBar.style.pointerEvents='none';this.formView.menuBar.style.pointerEvents='none';this.plane.style.minWidth=Number(this.module.form.properties.ClientWidth)/15*this.zoom+30+'px';this.plane.style.minHeight=(Number(this.module.form.properties.ClientHeight)/15+50)*this.zoom+'px';this.root.classList.toggle('drawing-control',this.tool!=='Pointer');this.renderSelection();}
  setTool(type){this.tool=type;this.root.classList.toggle('drawing-control',type!=='Pointer');this.emit('tool',type);}
  selected(){return this.module?.form.controls.filter(c=>this.selection.has(c.id))||[];}
  select(ids){this.selection=new Set(Array.isArray(ids)?ids:ids?[ids]:[]);this.primaryId=[...this.selection].at(-1)||null;this.renderSelection();this.emit('selection',{controls:this.selected(),form:this.module.form});}
  controlRect(control){const view=this.formView.controls.find(v=>v.model.id===control.id);if(!view)return null;const rect=view.node.getBoundingClientRect(),parent=this.formView.content.getBoundingClientRect();return {x:(rect.left-parent.left)/this.zoom,y:(rect.top-parent.top)/this.zoom,width:rect.width/this.zoom,height:rect.height/this.zoom};}
  renderSelection(){if(!this.overlay||!this.module)return;this.overlay.replaceChildren();const items=this.selected();this.formSelection?.replaceChildren();if(!items.length&&this.formSelection){const w=this.formView.node.offsetWidth*this.zoom,h=this.formView.node.offsetHeight*this.zoom;for(const [edge,x,y] of [['nw',0,0],['n',w/2,0],['ne',w,0],['w',0,h/2],['e',w,h/2],['sw',0,h],['s',w/2,h],['se',w,h]]){const enabled=['e','s','se'].includes(edge);this.formSelection.append(el('div',{class:'designer-form-handle'+(enabled?'':' disabled'),title:enabled?'Resize form':'Form sizing handle','data-resize-form':edge,style:{left:Math.round(8+x-3)+'px',top:Math.round(8+y-3)+'px'}}));}}for(const control of items){const r=this.controlRect(control);if(!r)continue;const box=el('div',{class:'selection-outline'+(control.id===this.primaryId?' primary-selection':''),style:{left:r.x+'px',top:r.y+'px',width:r.width+'px',height:r.height+'px'}});for(const handle of ['nw','n','ne','e','se','s','sw','w'])box.append(el('i',{class:'selection-handle '+handle,'data-handle':handle,'data-id':control.id}));this.overlay.append(box);}if(this.showTabOrder){for(const control of this.module.form.controls){const r=this.controlRect(control);if(r)this.overlay.append(el('button',{class:'tab-order-marker','data-order-id':control.id,style:{left:r.x+'px',top:r.y+'px'},text:control.properties.TabIndex||0}));}}renderAnchorGuides(this);}
  reflow(before,edited=[]){if(!layoutEnabled(this.project))return;arrangeFormEdit(before,this.module.form,edited);this.refreshControlPositions();}
  position(event){const rect=this.formView.content.getBoundingClientRect();return {x:(event.clientX-rect.left)/this.zoom,y:(event.clientY-rect.top)/this.zoom};}
  snap(value){const grid=this.settings.snapToGrid===false?15:Number(this.settings.gridSize)||120;return Math.round(value/grid)*grid;}
  transaction(label,fn){const before=clone(this.module.form);fn();if(layoutEnabled(this.project)){const old=new Map(before.controls.map(c=>[c.id,c]));const edited=this.module.form.controls.filter(c=>{const b=old.get(c.id);return !b||['Left','Top','Width','Height','Anchor','Dock'].some(k=>b.properties[k]!==c.properties[k]);}).map(c=>c.id);this.reflow(before,edited);}this.emit('change',{label,before,after:clone(this.module.form)});this.renderSelection();this.emit('selection',{controls:this.selected(),form:this.module.form});}
  pointerDown(event){if(event.button!==0||!this.module?.form)return;const content=this.formView.content;if(!this.formView.node.contains(event.target)&&!event.target.closest('[data-resize-form]')){if(this.tool==='Pointer')this.select([]);return;}this.root.focus({preventScroll:true});event.preventDefault();const marker=event.target.closest('[data-order-id]');if(marker){const c=this.module.form.controls.find(c=>c.id===marker.dataset.orderId);this.transaction('Set tab order',()=>c.properties.TabIndex=this.tabOrderIndex++);return;}
    const point=this.position(event),target=event.target.closest('[data-control-id]'),control=this.module.form.controls.find(c=>c.id===target?.dataset.controlId),handle=event.target.closest('[data-handle]'),formHandle=event.target.closest('[data-resize-form]');
    if(!content.contains(event.target)&&!formHandle){this.select([]);return;}
    const before=clone(this.module.form);let mode,origin,ghost,parent=null;
    if(formHandle){mode='formResize';origin={w:this.module.form.properties.ClientWidth,h:this.module.form.properties.ClientHeight};}
    else if(this.tool!=='Pointer'){mode='draw';ghost=el('div',{class:'designer-rubberband'});this.overlay.append(ghost);if(control&&['Frame','PictureBox','TabStrip','SSTab'].includes(control.type))parent=control;}
    else if(handle){mode='resize';origin=this.selected().map(c=>({c,left:c.properties.Left,top:c.properties.Top,width:c.properties.Width,height:c.properties.Height}));}
    else if(control){if(event.ctrlKey||event.metaKey){const next=new Set(this.selection);if(next.has(control.id))next.delete(control.id);else next.add(control.id);this.select([...next]);}else if(!this.selection.has(control.id))this.select([control.id]);if(this.locked)return;mode='move';origin=this.selected().map(c=>({c,left:c.properties.Left,top:c.properties.Top,width:c.properties.Width,height:c.properties.Height}));}
    else {mode='rubber';if(!event.shiftKey)this.select([]);ghost=el('div',{class:'designer-rubberband'});this.overlay.append(ghost);}
    if(!mode)return;let moved=false;this.root.setPointerCapture(event.pointerId);
    const move=e=>{const now=this.position(e),dx=(now.x-point.x)*15,dy=(now.y-point.y)*15;if(Math.abs(dx)+Math.abs(dy)>30)moved=true;
      if(mode==='move'){for(const item of origin){item.c.properties.Left=this.snap(item.left+dx);item.c.properties.Top=this.snap(item.top+dy);}this.refreshControlPositions();}
      if(mode==='resize'){const h=handle.dataset.handle;for(const item of origin){let {left,top,width,height}=item;if(h.includes('e'))width=this.snap(item.width+dx);if(h.includes('s'))height=this.snap(item.height+dy);if(h.includes('w')){left=this.snap(item.left+dx);width=item.width+item.left-left;}if(h.includes('n')){top=this.snap(item.top+dy);height=item.height+item.top-top;}Object.assign(item.c.properties,{Left:left,Top:top,Width:Math.max(120,width),Height:Math.max(120,height)});}this.reflow(before,origin.map(i=>i.c.id));this.refreshControlPositions();}
      if(mode==='formResize'){const edge=formHandle.dataset.resizeForm;if(edge.includes('e'))this.module.form.properties.ClientWidth=Math.max(900,this.snap(origin.w+dx));if(edge.includes('s'))this.module.form.properties.ClientHeight=Math.max(600,this.snap(origin.h+dy));this.reflow(before);this.formView.props.ClientWidth=this.module.form.properties.ClientWidth;this.formView.props.ClientHeight=this.module.form.properties.ClientHeight;this.formView.refresh();this.formView.node.style.left='8px';this.formView.node.style.top='8px';this.renderSelection();}
      if(ghost){const rect={left:Math.min(point.x,now.x),top:Math.min(point.y,now.y),width:Math.abs(now.x-point.x),height:Math.abs(now.y-point.y)};Object.assign(ghost.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px'});}this.emit('position',{x:Math.round(now.x*15),y:Math.round(now.y*15)});
    };
    const up=e=>{this.root.removeEventListener('pointermove',move);this.root.removeEventListener('pointerup',up);this.root.removeEventListener('pointercancel',cancel);ghost?.remove();const end=this.position(e);
      if(mode==='draw'){const type=this.tool,name=uniqueName(this.project,type,this.module),model=createControl(type,name,this.snap(Math.min(point.x,end.x)*15),this.snap(Math.min(point.y,end.y)*15));if(moved){model.properties.Width=Math.max(120,this.snap(Math.abs(end.x-point.x)*15));model.properties.Height=Math.max(120,this.snap(Math.abs(end.y-point.y)*15));}if(parent){const rect=this.controlRect(parent);model.parent=parent.name;model.properties.Left=this.snap(model.properties.Left-rect.x*15);model.properties.Top=this.snap(model.properties.Top-rect.y*15);}model.properties.TabIndex=this.module.form.controls.reduce((n,c)=>Math.max(n,Number(c.properties.TabIndex)||0),-1)+1;this.module.form.controls.push(model);this.selection=new Set([model.id]);this.setTool('Pointer');this.render();}
      if(mode==='rubber'){const left=Math.min(point.x,end.x),top=Math.min(point.y,end.y),right=Math.max(point.x,end.x),bottom=Math.max(point.y,end.y),next=new Set(this.selection);for(const c of this.module.form.controls){const r=this.controlRect(c);if(r&&r.x>=left&&r.y>=top&&r.x+r.width<=right&&r.y+r.height<=bottom)next.add(c.id);}this.select([...next]);}
      if(mode==='formResize')this.render();
      if(mode!=='rubber'&&(moved||mode==='draw'))this.emit('change',{label:{move:'Move controls',resize:'Resize controls',formResize:'Resize form',draw:'Add control'}[mode],before,after:clone(this.module.form)});
      this.renderSelection();this.emit('selection',{controls:this.selected(),form:this.module.form});
    };
    const cancel=()=>{this.root.removeEventListener('pointermove',move);this.root.removeEventListener('pointerup',up);this.root.removeEventListener('pointercancel',cancel);this.module.form=before;this.render();};
    this.root.addEventListener('pointermove',move);this.root.addEventListener('pointerup',up);this.root.addEventListener('pointercancel',cancel);
  }
  refreshControlPositions(){const models=new Map(this.module.form.controls.map(c=>[c.id,c]));for(const view of this.formView.controls){const model=models.get(view.model.id);if(model){Object.assign(view.props,model.properties);view.refresh();}}this.renderSelection();}
  applyProperty(key,value){this.transaction('Set '+key,()=>{const targets=this.selected().length?this.selected():[this.module.form];for(const c of targets)c.properties[key]=value;});this.render();}
  deleteSelected(){if(!this.selection.size)return;this.transaction('Delete controls',()=>{const names=new Set(this.selected().map(c=>c.name));let changed=true;while(changed){changed=false;for(const c of this.module.form.controls)if(c.parent&&names.has(c.parent)&&!names.has(c.name)){names.add(c.name);changed=true;}}this.module.form.controls=this.module.form.controls.filter(c=>!names.has(c.name));this.selection.clear();});this.render();}
  copy(){let selected=this.selected();const names=new Set(selected.map(c=>c.name));for(const c of this.module.form.controls)if(c.parent&&names.has(c.parent)){selected.push(c);names.add(c.name);}this.clipboard=clone(selected);this.emit('clipboard',this.clipboard.length);}
  cut(){this.copy();this.deleteSelected();}
  paste(){if(!this.clipboard.length)return;this.transaction('Paste controls',()=>{const nameMap=new Map(),created=[];for(const item of this.clipboard){const c=clone(item);c.id=newId();const base=c.name.replace(/\d+$/,'')||c.type;let index=1,name;do{name=base+index++;}while(this.module.form.controls.some(c=>lower(c.name)===lower(name))||created.some(c=>lower(c.name)===lower(name)));nameMap.set(c.name,name);c.name=name;c.properties.Name=name;c.properties.Left+=240;c.properties.Top+=240;created.push(c);}for(const c of created){if(c.parent)c.parent=nameMap.get(c.parent)||c.parent;this.module.form.controls.push(c);}this.selection=new Set(created.map(c=>c.id));});this.render();}
  align(command){const controls=this.selected();if(!controls.length)return;this.transaction(command,()=>{const first=(controls.find(c=>c.id===this.primaryId)||controls[0]).properties;if(command==='front'||command==='back'){const rest=this.module.form.controls.filter(c=>!this.selection.has(c.id));this.module.form.controls=command==='front'?[...rest,...controls]:[...controls,...rest];return;}if(command==='distributeHorizontal'||command==='distributeVertical'){if(controls.length<3)return;const horizontal=command==='distributeHorizontal',key=horizontal?'Left':'Top';const sorted=[...controls].sort((a,b)=>a.properties[key]-b.properties[key]),min=sorted[0].properties[key],max=sorted.at(-1).properties[key];sorted.forEach((c,i)=>c.properties[key]=Math.round(min+(max-min)*i/(sorted.length-1)));return;}for(const c of controls){const p=c.properties;switch(command){case 'left':p.Left=first.Left;break;case 'right':p.Left=first.Left+first.Width-p.Width;break;case 'top':p.Top=first.Top;break;case 'bottom':p.Top=first.Top+first.Height-p.Height;break;case 'centerHorizontal':p.Left=first.Left+(first.Width-p.Width)/2;break;case 'centerVertical':p.Top=first.Top+(first.Height-p.Height)/2;break;case 'sameWidth':p.Width=first.Width;break;case 'sameHeight':p.Height=first.Height;break;case 'sameSize':p.Width=first.Width;p.Height=first.Height;break;case 'centerInForm':p.Left=(this.module.form.properties.ClientWidth-p.Width)/2;break;case 'snap':p.Left=this.snap(p.Left);p.Top=this.snap(p.Top);break;}}});this.render();}
  keydown(event){if(event.key==='Delete'){event.preventDefault();this.deleteSelected();}if(event.key==='Escape'){this.setTool('Pointer');this.showTabOrder=false;this.renderSelection();}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='a'){event.preventDefault();this.select(this.module.form.controls.map(c=>c.id));}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='c'){event.preventDefault();this.copy();}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='x'){event.preventDefault();this.cut();}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='v'){event.preventDefault();this.paste();}const moves={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(moves[event.key]&&this.selection.size&&!this.locked){event.preventDefault();const [dx,dy]=moves[event.key],step=event.ctrlKey?15:this.settings.gridSize||120;this.transaction(event.shiftKey?'Resize controls':'Move controls',()=>{for(const c of this.selected()){if(event.shiftKey){c.properties.Width=Math.max(120,c.properties.Width+dx*step);c.properties.Height=Math.max(120,c.properties.Height+dy*step);}else{c.properties.Left+=dx*step;c.properties.Top+=dy*step;}}});this.refreshControlPositions();}}
  setZoom(zoom){this.zoom=Math.max(.25,Math.min(2,Number(zoom)));this.render();}
  scheduleSelection(){
    if(this.disposed||this.selectionFrame)return;
    this.selectionWindow=this.root.ownerDocument.defaultView;
    this.selectionFrame=this.selectionWindow.requestAnimationFrame(()=>{this.selectionFrame=0;if(!this.disposed)this.renderSelection();});
  }
  transferDocument(){
    this.selectionWindow?.cancelAnimationFrame(this.selectionFrame);this.selectionFrame=0;this.resizeObserver.disconnect();this.resizeObserver=new this.root.ownerDocument.defaultView.ResizeObserver(()=>this.scheduleSelection());this.resizeObserver.observe(this.root);this.renderSelection();}
  dispose(){this.disposed=true;this.selectionWindow?.cancelAnimationFrame(this.selectionFrame);this.formView?.dispose();this.grid?.dispose();this.resizeObserver.disconnect();this.root.remove();}
}
