import {createWin32,Win32Browser,WIN32_CONSTANTS} from '../../packages/win32-browser/src/index.js';
import {AutomationRegistry} from './automation.js';
import {ControlAdapterRegistry} from '../controls/adapters.js';
import {DataContext} from '../data/context.js';
import {ADOConnection,ADOCommand} from '../data/connection.js';
import {ConnectedRecordset} from '../data/connected-recordset.js';
import {DATA_CONSTANTS} from '../data/common.js';
import {FINANCIAL_FUNCTIONS} from './financial.js';
import {installNativeHost} from './native-windows.js';
import {ResourceStore} from './resources.js';
import {readRES,writeRES,setResource,setResourceString} from '../project/res.js';
import {THEMES,applyTheme,colorValue} from '../theme/theme.js';
import {MemoryRecordset} from './library.js';
import {RichTextDocument,parseRTF,writeRTF} from '../controls/rtf.js';
import { ApplicationHost } from './host.js';
import { VirtualMachine } from './vm.js';
import { compileProject, compileModule } from '../language/compiler.js';
import { parseExpression } from '../language/expression.js';
import { NOTHING, MISSING, VBErrorValue, Cell, Ref, VBArray, VBCollection, VBDictionary, VBCurrency,VBDecimal } from './values.js';
import {asDate,dateAdd,dateDiff,datePart,dateSerial,timeSerial,dateToSerial,serialToDate} from './calendar.js';
import { VirtualFileSystem } from './filesystem.js';
import { BrowserControl, BrowserForm } from '../controls/controls.js';
import { GraphicsSurface } from '../graphics/surface.js';
export async function mountApplication(project,container=document.body,options={}){const host=new ApplicationHost(project,container,options);if(options.nativeWindows!==false)installNativeHost(host);await host.start();return host;}
export const RuntimeAPI={AutomationRegistry,ControlAdapterRegistry,createWin32,Win32Browser,WIN32_CONSTANTS,DataContext,ADOConnection,ADOCommand,ConnectedRecordset,DATA_CONSTANTS,installNativeHost,ResourceStore,readRES,writeRES,setResource,setResourceString,THEMES,applyTheme,colorValue,NOTHING,MISSING,VBErrorValue,asDate,dateAdd,dateDiff,datePart,dateSerial,timeSerial,serialToDate,dateToSerial,Cell,Ref,MemoryRecordset,RichTextDocument,parseRTF,writeRTF,ApplicationHost,VirtualMachine,compileProject,compileModule,parseExpression,VBArray,VBCollection,VBDictionary,VBCurrency,VBDecimal,FINANCIAL_FUNCTIONS,VirtualFileSystem,BrowserControl,BrowserForm,GraphicsSurface};
