import {RuntimeAgentControl} from './agent-control.js';
import {RuntimeMDI} from './mdi.js';
import {runtimeDialog,messageBoxOptions} from '../controls/dialog.js';
import { applyTheme, themeId } from '../theme/theme.js';
import { icon } from '../theme/icons.js';
import {rasterDataURL} from '../project/frx.js';
import { el, download, lower, clone } from '../core/core.js';
import { compileProject } from '../language/compiler.js';
import { VirtualMachine } from './vm.js';
import { VirtualFileSystem } from './filesystem.js';
import { describe } from './values.js';
import { BrowserForm } from '../controls/controls.js';

export class ApplicationHost {
  constructor(project,container=document.body,options={}){this.project=clone(project);this.container=container;this.options=options;applyTheme(container,options.theme||project.settings?.theme);this.theme=themeId(options.theme||project.settings?.theme);this.forms=[];this.mdi=new RuntimeMDI(this);this.dialogs=[];this.backend='DOM / Canvas2D';this.disposed=false;this.storageKey='vb6-app:'+project.id;this.stage=el('div',{class:'vb-app-stage',style:{position:'absolute',inset:'0',overflow:'auto',background:options.background||'var(--vb-desktop)'}});container.append(this.stage);this.console=el('pre',{class:'vb-runtime-console',style:{position:'absolute',inset:'16px',padding:'16px',margin:'0',background:'var(--vb-window)',color:'var(--vb-window-text)',border:'2px inset var(--vb-face)',overflow:'auto',font:'14px/1.5 monospace',whiteSpace:'pre-wrap'}});this.stage.append(this.console);let stored=null;try{if(options.persist!==false)stored=JSON.parse(localStorage.getItem(this.storageKey)||'null');}catch{}this.fs=new VirtualFileSystem(stored?.vfs||project.vfs||{});this.settings=stored?.settings||project.appSettings||{};this.resizeObserver=new ResizeObserver(()=>this.layoutForms());this.resizeObserver.observe(container);this.messageHandler=e=>this.onBridgeMessage(e);if(options.bridgeToken)window.addEventListener('message',this.messageHandler);}
  send(type,data={}){this.options.onMessage?.({type,...data});if(this.options.bridgeToken&&window.parent!==window)window.parent.postMessage({channel:'vb6-runtime',token:this.options.bridgeToken,type,...data},'*');}
  async createForm(model,instance,vm){const form=new BrowserForm(model,{vm,instance,assets:this.project.assets||{},backend:this.project.settings?.renderer||'auto',onBackend:backend=>{this.backend=backend;this.send('backend',{backend});}});this.forms.push(form);this.console.hidden=true;this.stage.append(form.node);this.mdi.register(form);this.layoutForms();return form;}
  beginModal(form){this.modalForms ||= [];this.modalForms.push(form);const update=()=>{const top=this.modalForms.at(-1);for(const f of this.forms){f.node.inert=!!top&&f!==top;f.node.setAttribute('aria-modal',String(f===top));if(f===top)f.node.style.zIndex=String(200000+this.modalForms.length);}};update();return()=>{this.modalForms=this.modalForms.filter(f=>f!==form);update();};}
  layoutForms(){const width=this.container.clientWidth||innerWidth,height=this.container.clientHeight||innerHeight;this.forms.forEach((form,index)=>{if(form.movedByUser||form.mdiChild)return;const naturalWidth=Number(form.props.ClientWidth??form.props.Width)/15+8,naturalHeight=Number(form.props.ClientHeight??form.props.Height)/15+32,scale=Math.min(1,(width-16)/naturalWidth,(height-16)/naturalHeight);if(width<640||height<480){form.node.style.transform=`scale(${Math.max(.3,scale)})`;form.node.style.transformOrigin='top left';form.props.Left=Math.max(4,(width-naturalWidth*scale)/2)*15;form.props.Top=Math.max(4,(height-naturalHeight*scale)/2)*15;}else{form.node.style.transform='';if(Number(form.props.StartUpPosition)!==0){form.props.Left=Math.max(8,(width-naturalWidth)/2+index*20)*15;form.props.Top=Math.max(8,(height-naturalHeight)/2+index*20)*15;}}form.refresh();});this.mdi.layout();}
  async start(){const compiled=compileProject(this.project);this.vm=new VirtualMachine(compiled,{fs:this.fs,settings:this.settings,createForm:(...args)=>this.createForm(...args),beginModal:form=>this.beginModal(form),print:(text,newline)=>{this.console.append(document.createTextNode(text+(newline?'\n':'')));this.console.scrollTop=this.console.scrollHeight;this.send('output',{text,newline});},error:error=>this.showError(error),msgBox:(...args)=>this.msgBox(...args),inputBox:(...args)=>this.inputBox(...args),openFile:props=>this.openFile(props),saveFile:(name,data)=>this.saveFile(name,data),persist:()=>this.persist(),stop:()=>{this.forms.forEach(f=>f.Hide());this.persist();},beep:()=>this.beep(),clipboardWrite:text=>navigator.clipboard?.writeText(text).catch(()=>{})},{instructionLimit:this.options.instructionLimit||5000000});
    this.vm.on('evaluation',data=>this.send('evaluation',data));this.vm.on('state',state=>this.send('state',{state}));this.vm.on('pause',e=>{this.send('pause',{source:e.instruction.source,line:e.instruction.line,procedure:e.instruction.procedure,reason:e.reason,pauseId:this.vm.debugPauseId,locals:this.vm.debugLocals(),stack:e.stack.map((f,index)=>({index,module:f.module.name,procedure:f.proc.name,line:f.proc.code[Math.min(f.pc,f.proc.code.length-1)]?.line||0,depth:f.depth}))});});this.vm.on('stop',()=>this.send('stopped'));this.vm.on('error',error=>this.send('error',{error}));
    for(const bp of this.options.breakpoints||[])this.vm.setBreakpoint(bp.module,bp.line,bp.condition||'');
    this.vm.library.set('loadpicture',path=>{if(!path)return '';const key=Object.keys(this.project.assets||{}).find(k=>k.toLowerCase()===String(path).replace(/\\/g,'/').toLowerCase());if(key)return key;if(this.fs.exists(path)){const bytes=this.fs.readBytes(path),image=rasterDataURL(bytes);if(image)return image;const text=this.fs.read(path);if(/^data:image\//.test(text))return text;}throw new Error('Image not found or not a supported raster: '+path);});
    try{await this.vm.start({breakOnEntry:!!this.options.breakOnEntry});this.layoutForms();this.send('ready',{name:this.project.name,backend:this.backend,instructions:this.vm.instructionCount});this.autosave=setInterval(()=>{if(this.fs.dirty){this.persist();this.fs.dirty=false;}},1000);return this.vm;}catch(error){this.send('error',{error:{message:error.message,number:error.number,source:error.source,line:error.line}});return this.vm;}
  }
  persist(){if(this.options.persist===false)return;try{localStorage.setItem(this.storageKey,JSON.stringify({vfs:this.fs.snapshot(),settings:this.settings}));}catch{this.send('storage',{message:'Persistent storage is unavailable. This session still works in memory.'});}}
  async onBridgeMessage(event){const data=event.data;if(event.source!==window.parent||data?.channel!=='vb6-ide'||data.token!==this.options.bridgeToken)return;const vm=this.vm;if(!vm)return;try{if(data.agentGuard){if(data.agentGuard.state!==vm.state&&!(data.agentGuard.state==='running'&&vm.state==='idle'))throw new Error('Runtime state changed before the command.');if(data.agentGuard.state==='paused'&&data.agentGuard.pauseId!==vm.debugPauseId)throw new Error('Stale debugger pause.');}switch(data.command){
      case 'agentInspect':this.agentControl ||= new RuntimeAgentControl(this);this.send('commandResult',{id:data.id,ok:true,result:this.agentControl.inspect(data)});break;
      case 'agentInteract':this.agentControl ||= new RuntimeAgentControl(this);this.send('commandResult',{id:data.id,ok:true,result:this.agentControl.interact(data)});break;
      case 'agentSnapshot':this.send('commandResult',{id:data.id,ok:true,result:{vfs:this.fs.snapshot(),settings:clone(this.settings)}});break;
      case 'agentImmediate':{const value=await vm.immediate(String(data.text),{frameIndex:data.frameIndex??null,pauseId:data.pauseId});this.send('commandResult',{id:data.id,ok:true,result:{value:describe(value),locals:vm.debugLocals({frameIndex:data.frameIndex??null})}});break;}
      case 'debugEvaluate':{const value=await vm.evaluateExplicit(String(data.expression),{frameIndex:data.frameIndex??null,pauseId:data.pauseId,instructionLimit:data.instructionLimit??100000,timeLimit:data.timeLimit??5000});this.send('commandResult',{id:data.id,ok:true,result:{value:describe(value),locals:vm.debugLocals({frameIndex:data.frameIndex??null}),pauseId:vm.debugPauseId}});break;}
      case 'cancelEvaluation':this.send('commandResult',{id:data.id,ok:true,result:vm.cancelEvaluation()});break;
      case 'debugInspect':this.send('commandResult',{id:data.id,ok:true,result:vm.inspectDebug(String(data.expression),{frameIndex:data.frameIndex??null,offset:data.offset,limit:data.limit})});break;
      case 'debugLocals':this.send('commandResult',{id:data.id,ok:true,result:{locals:vm.debugLocals({frameIndex:data.frameIndex??null}),pauseId:vm.debugPauseId}});break;
      case 'debugAssign':this.send('commandResult',{id:data.id,ok:true,result:{entry:vm.assignDebug(String(data.expression),String(data.value),{frameIndex:data.frameIndex??null,pauseId:data.pauseId}),locals:vm.debugLocals({frameIndex:data.frameIndex??null})}});break;
      case 'runToCursor':this.send('commandResult',{id:data.id,ok:true,result:vm.runToCursor(String(data.module),Number(data.line))});break;
      case 'watchpoints':vm.setWatchpoints(data.watches||[]);break;
      case 'applyEdits':{const result=vm.applyEdits(data.project);this.project=clone(data.project);this.send('commandResult',{id:data.id,ok:true,result});break;}case 'setNextStatement':{const result=vm.setNextStatement(data.module,Number(data.line));this.send('commandResult',{id:data.id,ok:true,result});break;}case 'pause':vm.pause();break;case 'resume':vm.resume(data.mode||'continue');break;case 'stop':vm.stop();break;case 'breakpoints':vm.breakpoints.clear();for(const bp of data.breakpoints||[])vm.setBreakpoint(bp.module,bp.line,bp.condition||'');break;case 'immediate':{const value=await vm.immediate(String(data.text),{frameIndex:data.frameIndex??null,pauseId:data.pauseId});this.send('immediate',{id:data.id,value:describe(value),locals:vm.locals()});break;}case 'watch':{const values=[];for(const text of (data.expressions||[]).slice(0,100)){try{const result=vm.inspectDebug(text,{frameIndex:data.frameIndex??null,limit:1});values.push({...result,expression:text});}catch(error){values.push({expression:text,value:'<'+error.message+'>'});}}this.send('watches',{values});break;}case 'snapshot':this.send('snapshot',{vfs:this.fs.snapshot(),settings:this.settings});break;}}catch(error){if(data.command==='immediate')this.send('output',{text:'Error: '+error.message,newline:true});else if(data.id)this.send('commandResult',{id:data.id,ok:false,error:{message:error.message,number:error.number,source:error.source,line:error.line}});else this.send('output',{text:'Error: '+error.message,newline:true});}}
  modal(title,body,buttons=[{caption:'OK',value:1}],input=null,options={}){const result=runtimeDialog(this,title,body,buttons,input,options),dialog=this.dialogs.at(-1);if(this.vm?.debugEvaluation&&dialog)this.vm.debugEvaluation.dialogs.add(dialog);return result;}
  msgBox(text,style=0,title=this.project.name){const options=messageBoxOptions(style);return this.modal(title,text,options.buttons,null,options);}
  inputBox(text,title=this.project.name,def=''){return this.modal(title,text,[{caption:'OK',value:1},{caption:'Cancel',value:''}],String(def));}
  showError(error){this.send('output',{text:`Run-time error '${error.number||5}': ${error.message}\n${error.source||''}, line ${error.line||0}`,newline:true});this.modal(this.project.name,`Run-time error '${error.number||5}':\n\n${error.message}\n\n${error.source||''}, line ${error.line||0}`);}
  saveFile(name,data){return download(name,data,typeof data==='string'?'text/plain':'application/octet-stream');}
  openFile(props={}){return new Promise((resolve,reject)=>{const input=el('input',{type:'file',style:{display:'none'}});const filter=String(props.Filter||'').split('|').filter((_,i)=>i%2).join(';').split(';').map(s=>s.trim().replace(/^\*/, '')).filter(s=>/^\.\w+$/.test(s));if(filter.length)input.accept=filter.join(',');this.container.append(input);let done=false;const finish=value=>{if(done)return;done=true;input.remove();resolve(value);};input.addEventListener('change',async()=>{try{const file=input.files[0];if(file&&file.size>20*1024*1024)throw new Error('File exceeds 20 MiB');finish(file?{name:file.name,bytes:new Uint8Array(await file.arrayBuffer())}:null);}catch(error){input.remove();done=true;reject(error);}});input.addEventListener('cancel',()=>finish(null));input.click();});}
  beep(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;const audio=new Audio(),osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.frequency.value=880;gain.gain.value=.04;osc.start();osc.stop(audio.currentTime+.12);osc.onended=()=>audio.close();}catch{}}
  dispose(){this.disposed=true;this.vm?.stop();clearInterval(this.autosave);this.resizeObserver.disconnect();this.mdi.dispose();window.removeEventListener('message',this.messageHandler);for(const form of this.forms)form.dispose();for(const dialog of [...this.dialogs].reverse())dialog.vbFinish?.();this.stage.remove();}
}
