import {readFileSync} from 'node:fs';
import {tokenize} from '../src/language/lexer.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {DataContext} from '../src/data/context.js';
import {DAOEngine} from '../src/data/dao.js';
import {compileCriteria} from '../src/data/criteria.js';
import {parameterPlan,simpleSelect} from '../src/data/sql-parameters.js';
import {VBDecimal,VBCurrency} from '../src/runtime/values.js';
import {fieldValue} from '../src/data/recordset.js';
import {compileProject} from '../src/language/compiler.js';
import {VirtualMachine} from '../src/runtime/vm.js';
import {normalizeProject} from '../src/project/model.js';
const number=n=>e=>e.number===n;
async function fixture(t){const context=new DataContext(),engine=new DAOEngine(context);t.after(()=>context.close());const db=await engine.OpenDatabase('/dao.db');await db.Execute('CREATE TABLE people(id INTEGER PRIMARY KEY, name TEXT, age INTEGER, extra TEXT)');await db.Execute("INSERT INTO people VALUES(1,'Ada',30,'original'),(2,'Bob',20,'untouched'),(3,NULL,40,'third')");await db.TableDefs.Refresh();return {context,engine,db};}
const scalar=async(db,sql)=>(await db.connection.query(sql)).values[0][0];
test('DAO default table cursor, snapshot and forward-only options report truthful capabilities',async t=>{const {db}=await fixture(t);const table=await db.OpenRecordset('people');assert.equal(table.Type,1);const dyn=await db.OpenRecordset('SELECT * FROM people');assert.equal(dyn.Type,2);assert.equal(dyn.Updatable,-1);const snapshot=await db.OpenRecordset('people',4);assert.equal(snapshot.Updatable,0);assert.throws(()=>snapshot.Edit(),number(3027));const forward=await db.OpenRecordset('people',8);assert.equal(forward.Bookmarkable,0);assert.throws(()=>forward.MoveFirst(),number(3219));forward.MoveNext();assert.equal(forward.Item('id'),2);assert.throws(()=>forward.Clone(),number(3251));await assert.rejects(()=>db.OpenRecordset('people',2,0,2),number(3251));assert.equal((await db.OpenRecordset('people',2,0,4)).Updatable,0);});
test('DAO field assignment requires Edit, copy buffer is private and MoveNext discards it',async t=>{const {db}=await fixture(t),rs=await db.OpenRecordset('people',2),clone=rs.Clone();assert.throws(()=>rs.setItem('name','Wrong'),number(3020));rs.Edit();rs.setItem('name','Pending');assert.equal(rs.Item('name'),'Pending');assert.equal(clone.Item('name'),'Ada');assert.equal(await scalar(db,'SELECT name FROM people WHERE id=1'),'Ada');rs.MoveNext();assert.equal(rs.EditMode,0);rs.MoveFirst();assert.equal(rs.Item('name'),'Ada');});
test('DAO Update, CancelUpdate, bookmarks and Close preserve original vs committed edits',async t=>{const {db}=await fixture(t),rs=await db.OpenRecordset('people',2);const mark=rs.Bookmark;rs.Edit();rs.setItem('name','Saved');await rs.Update();assert.equal(rs.LastModified,mark);assert.equal(await scalar(db,'SELECT name FROM people WHERE id=1'),'Saved');rs.Edit();rs.setItem('name','Discard');rs.CancelUpdate();assert.equal(rs.Item('name'),'Saved');rs.Edit();rs.setItem('name','On close');const clone=rs.Clone();await rs.Close();assert.equal(clone.Item('name'),'Saved');assert.equal(clone.State,1);await assert.rejects(()=>rs.Close(),number(3420));});
test('DAO AddNew keeps original position until LastModified bookmark is assigned',async t=>{const {db}=await fixture(t),rs=await db.OpenRecordset('people',2);const mark=rs.Bookmark;rs.AddNew();rs.setItem('name','New');rs.setItem('age',50);assert.equal(rs.RecordCount,3);await rs.Update();assert.equal(rs.Bookmark,mark);assert.equal(rs.RecordCount,4);rs.Bookmark=rs.LastModified;assert.equal(rs.Item('name'),'New');assert.equal(rs.Item('id'),4);});
test('DAO abandoned AddNew creates no phantom rows and a deleted current row cannot be read',async t=>{const {db}=await fixture(t),rs=await db.OpenRecordset('people',2);rs.AddNew();rs.setItem('name','Discard');rs.MoveFirst();assert.equal(rs.RecordCount,3);await rs.Delete();assert.throws(()=>rs.Item('id'),number(3167));rs.MoveNext();assert.equal(rs.Item('id'),2);});
test('DAO optimistic conflict retains the copy buffer without corrupting a shared clone',async t=>{const {db}=await fixture(t),rs=await db.OpenRecordset('people',2),clone=rs.Clone();rs.Edit();rs.setItem('name','First');clone.Edit();clone.setItem('name','Other');await clone.Update();await assert.rejects(()=>rs.Update(),number(3197));assert.equal(rs.EditMode,1);assert.equal(rs.Item('name'),'First');assert.equal(clone.Item('name'),'Other');rs.CancelUpdate();assert.equal(rs.Item('name'),'Other');});
test('DAO direct SELECT projections update only selected columns and require every key',async t=>{const {db}=await fixture(t),rs=await db.OpenRecordset('SELECT id,name FROM people WHERE id=1');assert.equal(rs.Updatable,-1);await db.Execute("UPDATE people SET extra='external' WHERE id=1");rs.Edit();rs.setItem('name','Projection');await rs.Update();assert.equal(await scalar(db,"SELECT extra FROM people WHERE id=1"),'external');assert.equal((await db.OpenRecordset('SELECT name FROM people')).Updatable,0);assert.equal((await db.OpenRecordset('SELECT p.id,p.name FROM people p')).Updatable,0);assert.equal((await db.OpenRecordset('SELECT count(*) FROM people')).Updatable,0);});
test('DAO Find supports compound/null/LIKE/IN/BETWEEN criteria and moves independently',async t=>{const {db}=await fixture(t),rs=await db.OpenRecordset('people',2);rs.FindFirst("(age BETWEEN 20 AND 35 AND name LIKE 'A?*') OR name IS NULL");assert.equal(rs.Item('id'),1);rs.FindNext('name IS NULL');assert.equal(rs.Item('id'),3);rs.FindPrevious("name IN ('Bob','Ada') AND NOT age < 25");assert.equal(rs.Item('id'),1);rs.FindLast('age >= 20');assert.equal(rs.Item('id'),3);rs.FindNext('age >= 20');assert.equal(rs.NoMatch,-1);rs.MoveFirst();assert.equal(rs.NoMatch,0);});
test('DAO Filter and Sort apply to subsequently opened cursors without changing the original view',async t=>{const {db}=await fixture(t),rs=await db.OpenRecordset('people',2);rs.Filter='age >= 30';rs.Sort='age DESC';assert.equal(rs.RecordCount,3);assert.equal(rs.Item('id'),1);const child=rs.OpenRecordset(4);assert.equal(child.RecordCount,2);assert.equal(child.Item('id'),3);assert.equal(child.Updatable,0);await rs.Close();assert.equal(child.Item('age'),40);});
test('DAO Index and Seek use actual primary/index metadata and support both search directions',async t=>{const {db}=await fixture(t),rs=await db.OpenRecordset('people');rs.Index='PrimaryKey';rs.Seek('>=',2);assert.equal(rs.Item('id'),2);rs.Seek('<',3);assert.equal(rs.Item('id'),2);rs.Seek('=',99);assert.equal(rs.NoMatch,-1);assert.throws(()=>rs.Seek('<>',1),number(3001));assert.throws(()=>rs.FindFirst('id=1'),number(3251));});
test('DAO GetRows advances and AbsolutePosition is zero-based on dynasets',async t=>{const {db}=await fixture(t),rs=await db.OpenRecordset('people',2);rs.AbsolutePosition=1;assert.equal(rs.Item('name'),'Bob');const rows=rs.GetRows(1);assert.equal(rows.get(0,0),2);assert.equal(rs.AbsolutePosition,2);rs.MoveNext();assert.equal(rs.EOF,-1);assert.throws(()=>rs.MoveNext(),number(3021));});
test('DAO typed PARAMETERS are positional, repeat names and never substitute inside strings/comments',async t=>{const {db}=await fixture(t);const q=db.CreateQueryDef('',"PARAMETERS [key value] Long; SELECT id,name FROM people WHERE id=[key value] OR id=[key value] -- [key value]\n");assert.equal(q.Parameters.Count,1);q.Parameters.Item('KEY VALUE').Value=2;const rs=await q.OpenRecordset();assert.equal(rs.Item('name'),'Bob');assert.throws(()=>{q.Parameters.Item(0).Value='bad';},number(13));const plan=parameterPlan("PARAMETERS p Text(20); SELECT 'p', people.p FROM people WHERE name=p /* p */");assert.deepEqual(plan.bindings,[0]);assert(plan.text.includes('people.p'));assert(plan.text.includes("'p'"));});
test('DAO bound query parameters are data, not SQL text',async t=>{const {db}=await fixture(t),q=db.CreateQueryDef('',"PARAMETERS n Text(200); SELECT * FROM people WHERE name=n");q.Parameters.Item('n').Value="' OR 1=1 --";assert.equal((await q.OpenRecordset()).RecordCount,0);q.SQL='SELECT id,name FROM people WHERE id = :id OR id = :id';q.Parameters.Item('id').Value=1;assert.equal((await q.OpenRecordset()).RecordCount,1);});
test('DAO named QueryDefs survive database close, VFS snapshots and reopening',async t=>{const {db,context}=await fixture(t),q=db.CreateQueryDef('Adults','PARAMETERS a Long; SELECT * FROM people WHERE age >= a');q.Parameters.Item(0).Value=30;assert.equal((await db.OpenRecordset('Adults')).RecordCount,2);q.Close();const again=db.QueryDefs.Item('Adults');assert.notEqual(again,q);again.Parameters.Item(0).Value=40;assert.equal((await again.OpenRecordset()).RecordCount,1);await db.Close();const reloaded=new DataContext({vfs:context.fs.snapshot()});t.after(()=>reloaded.close());const other=await new DAOEngine(reloaded).OpenDatabase('/dao.db');assert.equal(other.QueryDefs.Count,1);assert(!other.TableDefs.items.some(t=>t.Name==='__vb6_dao_querydefs'));other.QueryDefs.Item('Adults').Parameters.Item(0).Value=20;assert.equal((await other.OpenRecordset('Adults')).RecordCount,3);});
test('DAO SQL updates persist and action queries report RecordsAffected',async t=>{const {db}=await fixture(t),q=db.CreateQueryDef('Rename','PARAMETERS n Text(20), k Long; UPDATE people SET name=n WHERE id=k');q.Parameters.Item('n').Value='Updated';q.Parameters.Item('k').Value=1;await q.Execute(128);assert.equal(q.RecordsAffected,1);q.SQL='UPDATE people SET age=age+1 WHERE id=2';await db.Execute('Rename',128);assert.equal(db.RecordsAffected,1);await db.QueryDefs.Refresh();assert.equal(db.QueryDefs.Item('Rename').SQL,q.SQL);db.QueryDefs.Delete('Rename');assert.equal(db.QueryDefs.Count,0);});
test('DAO QueryDef validates limits before executing and has per-query timeout inheritance',async t=>{const {db}=await fixture(t);assert.equal(db.QueryTimeout,60);const q=db.CreateQueryDef('','SELECT * FROM people');assert.equal(q.ODBCTimeout,-1);db.QueryTimeout=41;q.MaxRecords=1;assert.equal((await q.OpenRecordset()).RecordCount,1);assert.equal(db.connection.adapter.timeout,41);q.ODBCTimeout=2;await q.OpenRecordset();assert.equal(db.connection.adapter.timeout,2);assert.equal(db.QueryTimeout,41);q.MaxRecords=-1;await assert.rejects(()=>q.OpenRecordset(),number(5));q.MaxRecords=0;q.Connect='not a server profile';await assert.rejects(()=>q.OpenRecordset(),number(3251));});
test('DAO schema objects create actual tables, defaults, typed columns and indexes',async t=>{const {db}=await fixture(t),table=db.CreateTableDef('New People'),id=table.CreateField('Id',4),name=table.CreateField('Name',10,20),age=table.CreateField('Age',3);id.Attributes=16;name.Required=true;name.AllowZeroLength=false;name.DefaultValue='"Unknown"';age.DefaultValue=18;table.Fields.Append(id);table.Fields.Append(name);table.Fields.Append(age);const index=table.CreateIndex('UniqueName');index.Unique=true;index.Fields.Append(index.CreateField('Name'));table.Indexes.Append(index);db.TableDefs.Append(table);const rs=await db.OpenRecordset('New People');rs.AddNew();await rs.Update();rs.Bookmark=rs.LastModified;assert.equal(rs.Item('Name'),'Unknown');assert.equal(rs.Item('Age'),18);assert.equal(rs.Item('Id'),1);rs.Edit();assert.throws(()=>rs.setItem('Name',''),number(3315));rs.CancelUpdate();assert(table.Indexes.items.some(i=>i.Primary));await db.TableDefs.Refresh();assert.equal(db.TableDefs.Item('New People').Fields.Item('Age').Type,3);});
test('DAO catalog failure rolls back its savepoint without aborting an existing workspace transaction',async t=>{const {db,engine}=await fixture(t);await engine.BeginTrans();await db.Execute("UPDATE people SET name='Outer' WHERE id=1");const table=db.CreateTableDef('Invalid');table.Fields.Append(table.CreateField('id',4));const index=table.CreateIndex('bad');index.Fields.Append(index.CreateField('missing'));table.Indexes.Append(index);assert.throws(()=>db.TableDefs.Append(table),number(3265));assert.equal(await scalar(db,'SELECT name FROM people WHERE id=1'),'Outer');assert.equal(await scalar(db,"SELECT count(*) FROM sqlite_master WHERE name='Invalid'"),0);await engine.CommitTrans();});
test('DAO workspace handles to the same resource share nested transactions',async t=>{const {db,engine}=await fixture(t),other=await engine.OpenDatabase('/dao.db');assert.equal(db.connection,other.connection);assert.equal(engine.Databases.Count,2);await engine.BeginTrans();await db.Execute("UPDATE people SET name='Outer' WHERE id=1");await other.BeginTrans();await other.Execute("UPDATE people SET name='Inner' WHERE id=2");await db.CommitTrans();assert.equal(await scalar(other,'SELECT name FROM people WHERE id=1'),'Outer');await engine.Rollback();assert.equal(await scalar(db,'SELECT name FROM people WHERE id=1'),'Ada');assert.equal(await scalar(db,'SELECT name FROM people WHERE id=2'),'Bob');await other.Close();assert.equal(db.Updatable,-1);});
test('DAO different workspaces do not share active transactions or silently enlist another database',async t=>{const {db,engine}=await fixture(t),workspace=engine.CreateWorkspace('Other');engine.Workspaces.Append(workspace);const other=await workspace.OpenDatabase('/dao.db');await db.BeginTrans();await assert.rejects(()=>other.OpenRecordset('people'),number(3197));await assert.rejects(()=>engine.OpenDatabase('/new.db'),number(3251));await db.Rollback();assert.equal((await other.OpenRecordset('people')).RecordCount,3);await engine.OpenDatabase('/different.db');await assert.rejects(()=>engine.BeginTrans(),number(3251));});
test('DAO workspace rollback refreshes persisted catalog state',async t=>{const {db,engine}=await fixture(t);await engine.BeginTrans();db.CreateQueryDef('Temporary','SELECT * FROM people');await engine.Rollback();assert.equal(db.QueryDefs.Count,0);assert.equal(await scalar(db,"SELECT count(*) FROM sqlite_master WHERE name='__vb6_dao_querydefs'"),0);});
test('DAO closing a database discards copy buffers and rolls back its workspace transaction',async t=>{const {db,engine}=await fixture(t),rs=await db.OpenRecordset('people',2);await db.BeginTrans();await db.Execute("UPDATE people SET age=999 WHERE id=1");rs.Edit();rs.setItem('name','discard');await db.Close();assert.equal(rs.State,0);const reopened=await engine.OpenDatabase('/dao.db');assert.equal(await scalar(reopened,'SELECT age FROM people WHERE id=1'),30);assert.equal(await scalar(reopened,'SELECT name FROM people WHERE id=1'),'Ada');});
test('DAO read-only handles cannot execute SQL or catalog writes',async t=>{const {db,engine}=await fixture(t),ro=await engine.OpenDatabase('/dao.db',false,true);assert.equal(ro.Updatable,0);assert.equal((await ro.OpenRecordset('people')).Updatable,0);await assert.rejects(()=>ro.Execute("DELETE FROM people"),number(3027));assert.throws(()=>ro.CreateQueryDef('No','SELECT * FROM people'),number(3027));assert.equal((await ro.CreateQueryDef('','SELECT * FROM people').OpenRecordset()).RecordCount,3);});
test('DAO CreateDatabase and CompactDatabase produce real independent SQLite files',async t=>{const context=new DataContext();t.after(()=>context.close());const engine=new DAOEngine(context),db=await engine.CreateDatabase('/created.sqlite');assert(context.fs.exists('/created.sqlite'));await db.Execute('CREATE TABLE x(id INTEGER PRIMARY KEY, v TEXT)');await db.Execute("INSERT INTO x VALUES(1,'durable')");await assert.rejects(()=>engine.CompactDatabase('/created.sqlite','/copy.sqlite'),number(3356));await db.Close();await engine.CompactDatabase('/created.sqlite','/copy.sqlite');assert.equal(new TextDecoder().decode(context.fs.readBytes('/copy.sqlite').slice(0,15)),'SQLite format 3');const copy=await engine.OpenDatabase('/copy.sqlite');assert.equal(await scalar(copy,'SELECT v FROM x'),'durable');await assert.rejects(()=>engine.CreateDatabase('/copy.sqlite'),number(3204));await assert.rejects(()=>engine.CreateDatabase('/fake.mdb'),number(3706));});
test('DAO schema defaults cannot inject SQL or silently request Jet security/replication',async t=>{const {db,engine}=await fixture(t),table=db.CreateTableDef('Unsafe'),f=table.CreateField('x',10);f.DefaultValue="0); DROP TABLE people; --";table.Fields.Append(f);assert.throws(()=>db.TableDefs.Append(table),number(3251));assert.equal((await db.OpenRecordset('people')).RecordCount,3);assert.throws(()=>engine.CreateWorkspace('Secure','Admin','secret'),number(3251));await assert.rejects(()=>engine.OpenDatabase('archive.mdb'),number(3706));});
test('DAO Requery reevaluates current parameter values and updates field accessors',async t=>{const {db}=await fixture(t),q=db.CreateQueryDef('','PARAMETERS k Long; SELECT id,name FROM people WHERE id=k');q.Parameters.Item('k').Value=1;const rs=await q.OpenRecordset();q.Parameters.Item('k').Value=2;await rs.Requery();assert.equal(rs.Item('name'),'Bob');assert.equal(rs.Fields.Count,2);assert.equal(db.Recordsets.Count,1);});
test('criteria parser implements SQL Null logic and bounded LIKE without code evaluation',()=>{const cols=['x','s','d'].map(Name=>({Name}));assert(compileCriteria("NOT (x=1) OR s IS NULL",cols)({x:null,s:null}));assert(!compileCriteria("NOT x=1",cols)({x:null}));assert(compileCriteria("s LIKE '[A-C]#?*'",cols)({s:'b7text'}));assert(!compileCriteria("s LIKE '[!A-C]*'",cols)({s:'b7text'}));assert(compileCriteria('d >= #1/1/2020#',cols)({d:new Date('2021-01-01')}));assert.throws(()=>compileCriteria('x=1;globalThis.bad=1',cols));assert.throws(()=>compileCriteria('('.repeat(65)+'x=1'+')'.repeat(65),cols),number(7));const evil=compileCriteria("s LIKE '"+'*a'.repeat(200)+"b'",cols);assert.equal(evil({s:'a'.repeat(10000)+'c'}),false);});
test('query parser refuses malformed declarations and unsafe writer projections',()=>{assert.throws(()=>parameterPlan('PARAMETERS x Long, X Text; SELECT x'));assert.throws(()=>parameterPlan('PARAMETERS x Bogus; SELECT x'),number(3251));assert.throws(()=>parameterPlan('PARAMETERS x Text(-1); SELECT x'));for(const sql of ['SELECT id AS name FROM x','SELECT DISTINCT id FROM x','SELECT id FROM x UNION SELECT id FROM y','SELECT id FROM x JOIN y','SELECT * FROM x; DELETE FROM x'])assert.equal(simpleSelect(sql),null,sql);assert.deepEqual(simpleSelect('SELECT [id], [name] FROM [people] WHERE id=?'),{table:'people',columns:['id','name']});});
test('data fields validate exact decimals, GUIDs and dates without impersonating native defaults',()=>{assert.equal(fieldValue({Type:14},'12345678901234567890.123').toString(),'12345678901234567890.123');assert.equal(fieldValue({Type:72},'12345678-abcd-ABCD-abcd-1234567890ab'),'{12345678-ABCD-ABCD-ABCD-1234567890AB}');assert.throws(()=>fieldValue({Type:72},'bad'),number(13));assert(fieldValue({Type:135},'2020-01-01') instanceof Date);});
test('VB DAO QueryDefs, bang/index assignments and Field/Parameter default members execute end to end',async()=>{
 const code=readFileSync(new URL('./fixtures/dao-compat.bas',import.meta.url),'utf8');
 const project=normalizeProject({schema:1,name:'DaoProgram',startup:'Sub Main',modules:[{name:'MainModule',kind:'module',code}]});const compiled=compileProject(project);assert.deepEqual(compiled.diagnostics,[]);const output=[],vm=new VirtualMachine(compiled,{print:s=>output.push(s)});try{await vm.start();assert.deepEqual(output,['2','Original','Changed','Changed','Changed']);}finally{await vm.data.close();}
});

test('DAO attached QueryDef rename is persistent, duplicate-safe and CopyQueryDef is independent',async t=>{const {db,engine}=await fixture(t),q=db.CreateQueryDef('Before','PARAMETERS k Long; SELECT * FROM people WHERE id=k');q.Parameters.Item(0).Value=1;const rs=await q.OpenRecordset(),copy=rs.CopyQueryDef();copy.Parameters.Item(0).Value=2;assert.equal((await copy.OpenRecordset()).Item('name'),'Bob');assert.equal(q.Parameters.Item(0).Value,1);q.Name='After';assert.equal(db.QueryDefs.Item('After'),q);assert.throws(()=>db.QueryDefs.Item('Before'),number(3265));db.CreateQueryDef('Taken','SELECT * FROM people');assert.throws(()=>{q.Name='Taken';},number(3012));await db.Close();const reopened=await engine.OpenDatabase('/dao.db');assert.equal(reopened.QueryDefs.Item('After').SQL,q.SQL);});
test('DAO concurrent workspace opens share one resource and default workspace Close is a no-op',async t=>{const context=new DataContext();t.after(()=>context.close());const engine=new DAOEngine(context),workspace=engine.Workspaces.Item(0);const [a,b]=await Promise.all([workspace.OpenDatabase('/concurrent.db'),workspace.OpenDatabase('/concurrent.db')]);assert.equal(a.connection,b.connection);assert.equal(context.connections.size,1);await a.Execute('CREATE TABLE t(id INTEGER)');await workspace.Close();assert.equal(engine.Workspaces.Count,1);await workspace.BeginTrans();await b.Execute('INSERT INTO t VALUES(7)');await workspace.Rollback();assert.equal(await scalar(a,'SELECT count(*) FROM t'),0);});
test('DAO empty binary/GUID/Decimal field values are typed after SQLite inserts and reopen',async t=>{const {db}=await fixture(t);const td=db.CreateTableDef('Typed');for(const [name,type] of [['id',4],['amount',20],['guid',15],['bits',11]]){const f=td.CreateField(name,type);if(name==='id')f.Attributes=16;td.Fields.Append(f);}db.TableDefs.Append(td);const rs=await db.OpenRecordset('Typed');rs.AddNew();rs.setItem('amount','12345678901234567890.123');rs.setItem('guid','12345678-abcd-abcd-abcd-1234567890ab');rs.setItem('bits',new Uint8Array());await rs.Update();rs.Bookmark=rs.LastModified;assert.equal(rs.Item('amount').toString(),'12345678901234567890.123');assert.equal(rs.Item('guid'),'{12345678-ABCD-ABCD-ABCD-1234567890AB}');const reopened=await db.OpenRecordset('Typed');assert(reopened.Item('amount') instanceof VBDecimal);assert.equal(reopened.Item('amount').toString(),'12345678901234567890.123');assert.equal(reopened.Item('bits').length,0);});

test('bang field syntax remains distinct from Single type suffixes and preserves offsets',()=>{for(const name of ['name','[spaced name]']){const tokens=tokenize('rs!'+name);assert.equal(tokens[0].value,'rs');assert.equal(tokens[1].value,'!');assert.equal(tokens[0].end,2);assert.equal(tokens[1].start,2);}assert.equal(tokenize('amount! + 1')[0].value,'amount!');assert.equal(tokenize('1! + 2')[0].value,1);});
