import test from 'node:test';import assert from 'node:assert/strict';
import {MemoryRecordset} from '../src/runtime/library.js';
import {VBArray,VBCurrency} from '../src/runtime/values.js';
import {compileProject} from '../src/language/compiler.js';import {VirtualMachine} from '../src/runtime/vm.js';
function rs(){const r=new MemoryRecordset();r.Fields.Append('ID',3);r.Fields.Append('Customer Name',202,40);r.Fields.Append('Total',6);r.Open();for(const values of [[1,'Ada','1.23'],[2,"O'Malley",'7.5'],[3,'Grace','0']])r.AddNew(VBArray.from(['ID','Customer Name','Total']),VBArray.from(values));r.MoveFirst();return r;}
const number=n=>e=>e.number===n;
test('disconnected field schemas enforce supported types, size and case-insensitive uniqueness',()=>{const r=new MemoryRecordset();r.Fields.Append('Name',202,4);assert.throws(()=>r.Fields.Append('name'),number(3191));assert.throws(()=>r.Fields.Append('X',9999),number(3251));r.Open();assert.throws(()=>r.Fields.Append('Y'),number(3219));r.AddNew();assert.throws(()=>r.Fields.Item('NAME').Value='12345',number(372));assert.equal(r.Fields.Item(0).Value,null);r.Fields.Item(0).Value='abc';assert.equal(r.Fields.Item('Name').Value,'abc');});
test('open, close and state transitions reject unsupported providers and cursor types',()=>{const r=new MemoryRecordset();assert.throws(()=>r.RecordCount,number(3704));assert.throws(()=>r.Open('SELECT 1'),number(3251));assert.throws(()=>r.CursorType=0,number(3251));assert.throws(()=>r.Open(),number(3265));r.Fields.Append('X',3);r.Open();assert.throws(()=>r.Open(),number(3705));r.Close();assert.equal(r.State,0);assert.throws(()=>r.MoveNext(),number(3704));r.Open();assert.equal(r.RecordCount,0);});
test('typed numeric, Currency, Boolean and Date fields coerce and reject overflow atomically',()=>{const r=new MemoryRecordset();for(const [n,t]of [['B',17],['I',2],['L',3],['C',6],['T',11],['D',7]])r.Fields.Append(n,t);r.Open();r.AddNew();r.Update(VBArray.from(['B','I','L','C','T','D']),VBArray.from([255,-32768,2147483647,'922337203685477.5807',true,new Date(2020,0,1)]));assert.equal(r.Fields.Item('C').Value.raw,9223372036854775807n);assert.equal(r.Fields.Item('T').Value,-1);for(const [n,v]of [['B',256],['I',32768],['L',2147483648],['C','922337203685477.5808']])assert.throws(()=>r.Fields.Item(n).Value=v,number(6));const date=r.Fields.Item('D').Value;date.setFullYear(1990);assert.equal(r.Fields.Item('D').Value.getFullYear(),2020);});
test('field edits are cancellable before Update and preserve OriginalValue',()=>{const r=rs();r.Fields.Item('ID').Value=10;assert.equal(r.EditMode,1);assert.equal(r.Fields.Item('ID').OriginalValue,1);r.CancelUpdate();assert.equal(r.Fields.Item('ID').Value,1);assert.equal(r.EditMode,0);r.Fields.Item('ID').Value=20;r.Update();r.CancelUpdate();assert.equal(r.Fields.Item('ID').Value,20);});
test('CancelUpdate discards a new row and restores the previous current row',()=>{const r=rs();r.MoveLast();const b=r.Bookmark;r.AddNew();r.Fields.Item('ID').Value=99;assert.equal(r.EditMode,2);assert.equal(r.RecordCount,4);r.CancelUpdate();assert.equal(r.RecordCount,3);assert.equal(r.Bookmark,b);});
test('navigation commits pending edits and handles BOF/EOF without unbounded positions',()=>{const r=rs();r.Fields.Item('ID').Value=9;r.MoveNext();assert.equal(r.EditMode,0);r.MovePrevious();assert.equal(r.Fields.Item('ID').Value,9);r.MovePrevious();assert.equal(r.BOF,-1);assert.equal(r.AbsolutePosition,-2);r.MoveNext();assert.equal(r.AbsolutePosition,1);r.MoveLast();r.MoveNext();r.MoveNext();assert.equal(r.EOF,-1);assert.equal(r.AbsolutePosition,-3);assert.throws(()=>r.Fields.Item(0).Value,number(3021));r.MovePrevious();assert.equal(r.Fields.Item(0).Value,3);});
test('Update field/value arrays validate all fields before any mutation',()=>{const r=rs();assert.throws(()=>r.Update(VBArray.from(['ID','Total']),VBArray.from([17,'oops'])),number(13));assert.equal(r.Fields.Item('ID').Value,1);assert.equal(r.EditMode,0);assert.throws(()=>r.Update(VBArray.from(['ID','Total']),VBArray.from([1])),number(3001));assert.throws(()=>r.Update(VBArray.from(['ID','id']),VBArray.from([1,2])),number(3001));});
test('invalid AddNew field/value arrays do not commit or discard an existing edit',()=>{const r=rs();r.Fields.Item('ID').Value=18;assert.throws(()=>r.AddNew('Missing',4),number(3265));assert.equal(r.RecordCount,3);assert.equal(r.EditMode,1);r.CancelUpdate();assert.equal(r.Fields.Item('ID').Value,1);});
test('AddNew with values commits immediately and uses typed Currency',()=>{const r=rs();r.AddNew(VBArray.from(['ID','Total']),VBArray.from([4,'1.2345']));assert.equal(r.EditMode,0);assert.ok(r.Fields.Item('Total').Value instanceof VBCurrency);assert.equal(r.Fields.Item('Total').Value.toString(),'1.2345');assert.equal(r.Fields.Item('Customer Name').Value,null);});
test('stable bookmarks survive sorting and edits but cannot access filtered or deleted rows',()=>{const r=rs();const b=r.Bookmark;r.Sort='[Customer Name] DESC';r.Bookmark=b;assert.equal(r.Fields.Item('ID').Value,1);r.Filter='ID > 1';assert.throws(()=>r.Bookmark=b,number(3001));r.Filter='';r.Bookmark=b;r.Delete();assert.throws(()=>r.Bookmark=b,number(3001));});
test('sort is stable, typed, case-insensitive and supports bracketed field names',()=>{const r=rs();r.Sort='Total DESC, [Customer Name] ASC';assert.deepEqual(r.view().map(x=>x.ID),[2,1,3]);r.Sort='[Customer Name] ASC';assert.deepEqual(r.view().map(x=>x.ID),[1,3,2]);});
test('invalid sort preserves the previous sort, view and current row',()=>{const r=rs();r.Sort='ID DESC';r.MoveNext();for(const text of ['Missing','ID sideways','ID,','ID, id','ID;constructor']){assert.throws(()=>r.Sort=text);assert.equal(r.Sort,'ID DESC');assert.equal(r.Fields.Item('ID').Value,2);}});
test('criteria support quoted names, doubled apostrophes, Currency and flat AND/OR',()=>{const r=rs();r.Filter="[Customer Name] = 'O''Malley'";assert.equal(r.RecordCount,1);assert.equal(r.Fields.Item('ID').Value,2);r.Filter='Total >= $1.23 AND ID < 3';assert.equal(r.RecordCount,2);r.Filter='ID = 1 OR ID = 2 AND Total > 3';assert.deepEqual(r.view().map(x=>x.ID),[2]);});
test('LIKE supports prefix and surrounding patterns without regex injection',()=>{const r=rs();r.Filter="[Customer Name] LIKE '*a*'";assert.equal(r.RecordCount,3);r.Filter="[Customer Name] LIKE 'gr%'";assert.equal(r.RecordCount,1);r.Filter="[Customer Name] LIKE '.*'";assert.equal(r.RecordCount,0);});
test('invalid or unsupported filters are atomic, not silently approximated',()=>{const r=rs();r.Filter='ID > 1';r.MoveLast();for(const text of ["Missing = 1","ID > 1 AND","(ID=1 OR ID=2)","ID = Null","[Customer Name] LIKE 'a*b'",'ID = process.exit()']){assert.throws(()=>r.Filter=text);assert.equal(r.Filter,'ID > 1');assert.equal(r.Fields.Item('ID').Value,3);}assert.throws(()=>r.Filter=1,number(3251));r.Filter=0;assert.equal(r.RecordCount,3);});
test('empty recordsets and zero matching rows have BOF and EOF set',()=>{const r=rs();r.Filter='ID > 9';assert.equal(r.BOF,-1);assert.equal(r.EOF,-1);assert.equal(r.RecordCount,0);assert.throws(()=>r.current(),number(3021));});
test('read-only recordsets reject every write path',()=>{const r=new MemoryRecordset();r.Fields.Append('ID',3);r.LockType=1;r.Open();assert.throws(()=>r.AddNew(),number(3251));assert.throws(()=>r.Delete(),number(3251));assert.throws(()=>r.Update('ID',1),number(3251));});
test('GetRows respects row limits, field selection, cursor advancement and empty results',()=>{const r=rs(),a=r.GetRows(2,undefined,VBArray.from(['Customer Name','ID']));assert.deepEqual(a.bounds,[[0,1],[0,1]]);assert.equal(a.get(0,0),'Ada');assert.equal(a.get(1,1),2);assert.equal(r.Fields.Item('ID').Value,3);const b=r.GetRows();assert.equal(b.get(0,0),3);assert.equal(r.EOF,-1);assert.equal(r.GetRows().data.length,0);});
test('data observers see lifecycle/edit/cancel events and disposal removes subscriptions',()=>{const r=rs(),events=[],off=r.subscribe(e=>events.push(e.kind));r.Fields.Item(0).Value=9;r.CancelUpdate();r.MoveNext();r.Sort='ID DESC';r.Close();assert.deepEqual(events,['edit','cancel','move','sort','close']);off();r.Open();assert.equal(events.length,5);});
test('an observer exception cannot roll back committed changes or stop other observers',()=>{const r=rs(),events=[];r.subscribe(()=>{throw Error('observer');});r.subscribe(e=>events.push(e.kind));r.Update('ID',18);assert.equal(r.Fields.Item('ID').Value,18);assert.deepEqual(events,['update']);assert.equal(r.lastObserverError.message,'observer');});
test('binding API writes typed values and refuses stale, removed and filtered records',()=>{const r=rs(),row=r.current();r.setRowValue(row,'ID','17',1);assert.equal(row.ID,17);assert.throws(()=>r.setRowValue(row,'ID',20,1),number(3197));r.Filter='ID < 4';assert.throws(()=>r.setRowValue(row,'ID',3),number(3021));r.Filter='';r.Bookmark=r._bookmarks.get(row);r.Delete();assert.throws(()=>r.setRowValue(row,'ID',2),number(3021));});
test('malicious field names do not alter JavaScript prototypes',()=>{const r=new MemoryRecordset();r.Fields.Append('__proto__',200);r.Fields.Append('constructor',200);r.Open();r.AddNew(VBArray.from(['__proto__','constructor']),VBArray.from(['data','safe']));assert.equal(Object.getPrototypeOf(r.current()),null);assert.equal(r.Fields.Item('__proto__').Value,'data');assert.equal({}.polluted,undefined);});
test('repeated reads reuse the compiled view until data or filter changes',()=>{const r=rs();r.Sort='ID DESC';const view=r.view();assert.equal(r.view(),view);r.MoveNext();assert.equal(r.view(),view);r.Update('ID',18);assert.notEqual(r.view(),view);});
test('VB execution exercises typed field edits, CancelUpdate, filters and row arrays',async()=>{const code=`Sub Main()
Dim r As Object,a As Variant
Set r=CreateObject("ADODB.Recordset")
r.Fields.Append "ID",adInteger
r.Fields.Append "Amount",adCurrency
r.Open
r.AddNew Array("ID","Amount"),Array(1,CCur("12.3456"))
r.Fields("ID").Value=2
r.CancelUpdate
Debug.Print r.Fields("ID").Value,r.Fields("Amount").Value
r.AddNew Array("ID","Amount"),Array(2,CCur(3))
r.Filter="ID > 1"
a=r.GetRows()
Debug.Print a(0,0),a(1,0),r.EOF
r.Close
End Sub`;const p=compileProject({startup:'Sub Main',modules:[{name:'M',kind:'module',code}]});assert.deepEqual(p.diagnostics,[]);const output=[],vm=new VirtualMachine(p,{print:s=>output.push(s)});await vm.start();assert.equal(vm.lastError,null);assert.deepEqual(output,['1 12.3456','2 3 -1']);});
