import test from 'node:test';import assert from 'node:assert/strict';import {VirtualMachine} from '../src/runtime/vm.js';import {compileProject} from '../src/language/compiler.js';import {Cell,LazyCell,NOTHING,VBArray} from '../src/runtime/values.js';
const project=(code,more=[])=>({name:'Debug',startup:'Sub Main',modules:[{name:'M',kind:'module',code},...more]});
async function paused(code,line,more=[]){const p=project(code,more),output=[],vm=new VirtualMachine(compileProject(p),{print:s=>output.push(s)});assert.equal(vm.program.valid,true,JSON.stringify(vm.program.diagnostics));vm.setBreakpoint('M',line);let release;const pause=new Promise(r=>release=r),off=vm.on('pause',e=>{off();release(e);});const running=vm.start();await pause;return {vm,running,output};}
const finish=async({vm,running})=>{vm.breakpoints.clear();vm.setWatchpoints([]);vm.resume();await running;};
test('safe watch arithmetic and intrinsics do not create implicit variables',async()=>{const p=await paused('Sub Main()\nDim x As Long\nx = 4\nDebug.Print x\nEnd Sub',4);assert.equal(await p.vm.evaluateWatch('x * 2 + Abs(-1)'),9);assert.equal(await p.vm.evaluateWatch('Len("abc")'),3);await assert.rejects(p.vm.evaluateWatch('notDeclared'),/Variable not defined/);assert.equal(p.vm.currentFrame.locals.has('notdeclared'),false);await finish(p);});
test('automatic watches do not invoke functions or properties',async()=>{const p=await paused('Public hits As Long\nSub Main()\nDebug.Print hits\nEnd Sub\nFunction SideEffect() As Long\nhits = hits + 1\nSideEffect = hits\nEnd Function\nProperty Get Value() As Long\nhits = hits + 1\nValue = hits\nEnd Property',3);for(const expr of ['SideEffect','SideEffect()','Value','M.Value','M.SideEffect()','New Collection','MsgBox("x")','CreateObject("Scripting.Dictionary")'])await assert.rejects(p.vm.evaluateWatch(expr),/disabled|cannot execute|not found/i);assert.equal(p.vm.instances.get('m').fields.get('hits').get(),0);await finish(p);});
test('lazy objects are displayed without construction',async()=>{const p=await paused('Sub Main()\nDim c As New Counter\nDebug.Print "hold"\nEnd Sub',3,[{name:'Counter',kind:'class',code:'Public value As Long\nPrivate Sub Class_Initialize()\nDebug.Print "created"\nEnd Sub'}]);assert.equal(await p.vm.evaluateWatch('c'),NOTHING);assert.equal(p.vm.inspectDebug('c').value,'Nothing');assert.equal(p.output.length,0);await finish(p);assert.deepEqual(p.output,['hold']);});
test('stored record and multidimensional array inspection is bounded',async()=>{const code='Type Row\nName As String\nCount As Long\nEnd Type\nSub Main()\nDim rows(1 To 300, 2 To 20) As Row\nrows(1, 2).Name = "first"\nDebug.Print "hold"\nEnd Sub';const p=await paused(code,8);const row=p.vm.inspectDebug('rows',{offset:0,limit:20});assert.equal(row.total,5700);assert.equal(row.children.length,20);assert.equal(row.children[0].expression,'rows(1, 2)');assert.equal(row.children[19].expression,'rows(2, 2)');assert.equal(row.truncated,true);const fields=p.vm.inspectDebug('rows(1, 2)');assert.equal(fields.children.find(f=>f.name==='Name').value,'"first"');await finish(p);});
test('typed edits preserve bounds and are atomic on failure',async()=>{const p=await paused('Sub Main()\nDim count As Integer\nDim a(1 To 2) As Byte\ncount = 12\nDebug.Print count\nEnd Sub',5);p.vm.assignDebug('count','count + 5',{pauseId:p.vm.debugPauseId});assert.equal(p.vm.currentFrame.locals.get('count').get(),17);assert.throws(()=>p.vm.assignDebug('count','999999'),/Overflow/);assert.equal(p.vm.currentFrame.locals.get('count').get(),17);p.vm.assignDebug('a(2)','255');assert.equal(await p.vm.evaluateWatch('a(2)'),255);assert.throws(()=>p.vm.assignDebug('a(2)','256'),/Overflow/);assert.equal(await p.vm.evaluateWatch('a(2)'),255);assert.throws(()=>p.vm.assignDebug('count','7',{pauseId:0}),/context changed/);await finish(p);assert.deepEqual(p.output,['17']);});
test('caller-frame inspection and editing do not change current frame',async()=>{const p=await paused('Sub Main()\nDim outer As Long\nouter = 10\nWorker\nDebug.Print outer\nEnd Sub\nSub Worker()\nDim inner As Long\ninner = 20\nDebug.Print inner\nEnd Sub',10);const frame=p.vm.currentFrame;assert.equal(p.vm.debugLocals({frameIndex:0})[0].value,'10');assert.equal(await p.vm.evaluateWatch('outer',{frameIndex:0}),10);p.vm.assignDebug('outer','30',{frameIndex:0});assert.equal(p.vm.currentFrame,frame);assert.throws(()=>p.vm.debugLocals({frameIndex:99}),/frame/);await finish(p);assert.deepEqual(p.output,['20','30']);});
test('constants and private cross-module fields are read-only',async()=>{const p=await paused('Private hidden As Long\nPublic Const Fixed = 9\nSub Main()\nDebug.Print Fixed\nEnd Sub',4);assert.throws(()=>p.vm.assignDebug('Fixed','2'),/read-only/);assert.equal(await p.vm.evaluateWatch('Fixed'),9);await finish(p);});
test('native getters and prototype paths are not executed',async()=>{const p=await paused('Sub Main()\nDim obj As Object\nDebug.Print "hold"\nEnd Sub',3);let calls=0;const native={Good:2,get Unsafe(){calls++;return 8;}};p.vm.currentFrame.locals.get('obj').set(native);assert.equal(await p.vm.evaluateWatch('obj.Good'),2);for(const expr of ['obj.Unsafe','obj.constructor','obj.__proto__'])await assert.rejects(p.vm.evaluateWatch(expr));assert.equal(calls,0);await finish(p);});
test('watch expression length and recursion bounds reject abuse',async()=>{const p=await paused('Sub Main()\nDebug.Print 1\nEnd Sub',2);await assert.rejects(p.vm.evaluateWatch('"'+'x'.repeat(5000)+'"'),/4096/);await assert.rejects(p.vm.evaluateWatch('('.repeat(80)+'1'+')'.repeat(80)),/complex/);await finish(p);});
test('Run to Cursor pauses before the target without retaining a breakpoint',async()=>{const p=await paused('Sub Main()\nDim x As Long\nx = 2\nx = 3\nDebug.Print x\nEnd Sub',3);let done;const next=new Promise(r=>done=r),off=p.vm.on('pause',e=>{off();done(e);});p.vm.runToCursor('M',5);const stop=await next;assert.equal(stop.instruction.line,5);assert.equal(stop.reason,'run-to-cursor');assert.equal(p.vm.currentFrame.locals.get('x').get(),3);assert.equal(p.vm.runTarget,null);assert.equal(p.vm.breakpoints.size,1);await finish(p);});
test('Run to Cursor validates break mode and executable source',async()=>{const p=await paused('Sub Main()\nDebug.Print 1\nEnd Sub',2);assert.throws(()=>p.vm.runToCursor('M',99),/not executable/);assert.throws(()=>p.vm.runToCursor('Missing',2),/not executable/);await finish(p);assert.throws(()=>p.vm.runToCursor('M',2),/break mode/);});
test('break-on-change watch triggers before the following statement',async()=>{const p=project('Sub Main()\nDim x As Long\nx = 1\nx = 2\nDebug.Print x\nEnd Sub'),vm=new VirtualMachine(compileProject(p)),pauses=[];vm.setWatchpoints([{id:'x',expression:'x',mode:'change'}]);vm.on('pause',e=>{pauses.push([e.instruction.line,vm.currentFrame.locals.get('x').get()]);vm.resume();});await vm.start();assert.deepEqual(pauses,[[4,1],[5,2]]);});
test('break-when-true watch respects procedure context',async()=>{const p=project('Sub Main()\nDim x As Long\nx = 2\nOther\nEnd Sub\nSub Other()\nDim x As Long\nx = 9\nDebug.Print x\nEnd Sub'),vm=new VirtualMachine(compileProject(p)),pauses=[];vm.setWatchpoints([{expression:'x = 9',mode:'true',module:'M',procedure:'Other'}]);vm.on('pause',e=>{pauses.push(e.instruction.line);vm.resume();});await vm.start();assert.ok(pauses.includes(9));assert.ok(pauses.every(n=>n>=7));});
test('watchpoint configuration validates atomically',()=>{const vm=new VirtualMachine(compileProject(project('Sub Main()\nEnd Sub')));vm.setWatchpoints([{expression:'1',mode:'true'}]);assert.throws(()=>vm.setWatchpoints([{expression:'bad(',mode:'change'}]));assert.equal(vm.watchpoints.length,1);assert.equal(vm.watchpoints[0].expression,'1');assert.throws(()=>vm.setWatchpoints(new Array(101).fill({expression:'1',mode:'true'})));});
test('unsafe breakpoint conditions never execute user procedures',async()=>{const p=project('Public hits As Long\nSub Main()\nDebug.Print hits\nEnd Sub\nFunction Touch() As Boolean\nhits = hits + 1\nTouch = True\nEnd Function'),vm=new VirtualMachine(compileProject(p));vm.setBreakpoint('M',3,'Touch()');vm.on('pause',()=>vm.resume());await vm.start();assert.equal(vm.instances.get('m').fields.get('hits').get(),0);});
