import test from 'node:test';import assert from 'node:assert/strict';
import {indexSource} from '../src/editor/projection.js';
import {updateSourceIndex,replacementChange,inputChange,HighlightCache} from '../src/editor/incremental.js';
function check(before,start,end,text){const next=before.slice(0,start)+text+before.slice(end);const a=updateSourceIndex(indexSource(before),next,replacementChange(start,end,text.length));assert.deepEqual(a.index,indexSource(next));return a;}
test('incremental indices preserve procedure starts for edits and end-of-file',()=>{for(const source of ['', '\n','abc\ndef\n','Public Sub Main()\nEnd Sub\nPublic Function X()\nEnd Function'])for(let i=0;i<=source.length;i++)for(const insert of ['a','\n','\nPublic Sub NewOne()\n','😀'])check(source,i,Math.min(source.length,i+2),insert);});
test('incremental random edits agree with a full reindex (2000 patches)',()=>{let source='Option Explicit\nPublic Sub Main()\n    Debug.Print "😀"\nEnd Sub\n';let seed=42;const rand=n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n;};for(let i=0;i<2000;i++){const start=rand(source.length+1),end=start+rand(source.length-start+1),insert=['x','\n','Public Sub A()\n','End Sub\n','😀',''][rand(6)];check(source,start,end,insert);source=source.slice(0,start)+insert+source.slice(end);}});
test('single-line edit does not rescan 100000 unchanged lines',()=>{const source='Option Explicit\n'+'    Debug.Print 1\n'.repeat(100000)+'Public Sub Main()\nEnd Sub';const index=indexSource(source);const start=index.starts[50000]+4;const r=updateSourceIndex(index,source.slice(0,start)+'X'+source.slice(start+1),replacementChange(start,start+1,1));assert.equal(r.scannedLines,1);assert.equal(r.changedProcedures,false);assert.equal(r.index.lines[99999],index.lines[99999]);});
test('input edit hints handle insertion, deletion, surrogate pairs and fallback',()=>{assert.deepEqual(inputChange('abc','axbc',{start:1,end:1,type:'insertText'},2),replacementChange(1,1,1));assert.deepEqual(inputChange('a😀b','ab',{start:3,end:3,type:'deleteContentBackward'},1),replacementChange(1,3,0));assert.deepEqual(inputChange('abc','ac',{start:1,end:1,type:'deleteContentForward'},1),replacementChange(1,2,0));assert.equal(inputChange('abc','ax',{start:1,end:3,type:'historyUndo'},2),null);});
test('highlight cache is bounded and least-recently-used',()=>{const c=new HighlightCache(2,1000);let count=0;const make=()=>String(++count);assert.equal(c.get('a',make),'1');c.get('b',make);assert.equal(c.get('a',make),'1');c.get('c',make);assert.equal(c.map.has('b'),false);assert.equal(c.hits,1);c.clear();assert.equal(c.chars,0);});
import {History} from '../src/core/core.js';
test('sparse source history scales with inserted bytes and replays in both directions',()=>{const h=new History();const apply=(p,patches,undo)=>{for(const t of undo?[...patches].reverse():patches){const a=undo?t.after:t.before,b=undo?t.before:t.after;p.code=p.code.slice(0,t.start)+b+p.code.slice(t.start+a.length);}return p;};const original={code:'x'.repeat(1000000)};let current={...original};for(let i=0;i<30;i++){const patch={start:i,before:'',after:'a'};h.recordPatch('M',patch,apply,'Type',true);current=apply(current,[patch],false);}assert.equal(h.undoStack.length,1);assert.ok(h.undoStack[0].bytes<5000);assert.deepEqual(h.undo(current),original);assert.deepEqual(h.redo(original),current);});

test('incremental indexing remains equivalent after deterministic randomized Unicode edits',()=>{
 let text='Option Explicit\nSub A()\nDim x As Long\nEnd Sub\n',index=indexSource(text),seed=123456;const random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};
 for(let i=0;i<2000;i++){const start=Math.floor(random()*(text.length+1)),end=Math.min(text.length,start+Math.floor(random()*8)),insert=['','\n','😀',"' hello\n",'Sub Z()\nEnd Sub\n',' X '][Math.floor(random()*6)],next=text.slice(0,start)+insert+text.slice(end);index=updateSourceIndex(index,next,replacementChange(start,end,insert.length)).index;text=next;const full=indexSource(text);assert.deepEqual(index.lines,full.lines);assert.deepEqual(index.starts,full.starts);assert.deepEqual(index.procedures,full.procedures);}
});
