import test from 'node:test';
import assert from 'node:assert/strict';
import {compileProject,compileModule} from '../src/language/compiler.js';
import {VirtualMachine} from '../src/runtime/vm.js';
import {ProjectDiagnosticCache,diagnosticSnapshot} from '../src/language/diagnostics.js';
const module=(name,code,kind='class',attributes=[])=>({name,code,kind,attributes});
const main=code=>module('MainModule',`Option Explicit\nSub Main()\n${code}\nEnd Sub`,'module');
async function run(modules){const program=compileProject({name:'Features06',startup:'Sub Main',modules});assert.deepEqual(program.diagnostics,[]);const output=[],vm=new VirtualMachine(program,{print:s=>output.push(s)});await vm.start();return {output,vm};}
const iValue=module('IValue','Public Function Scale(ByVal amount As Long, Optional ByVal factor As Long = 2) As Long\nEnd Function\nPublic Property Get Name() As String\nEnd Property\nPublic Property Let Name(ByVal value As String)\nEnd Property');
const value=module('Value','Implements IValue\nPrivate caption As String\nPrivate Function IValue_Scale(ByVal x As Long, Optional ByVal factor As Long = 2) As Long\nIValue_Scale = x * factor\nEnd Function\nPrivate Property Get IValue_Name() As String\nIValue_Name = caption\nEnd Property\nPrivate Property Let IValue_Name(ByVal x As String)\ncaption = x\nEnd Property\nPublic Function Own() As String\nOwn = "own"\nEnd Function');
test('interface dispatch preserves named contract, private implementation and properties',async()=>{const {output}=await run([main('Dim a As New Value, b As IValue\nSet b = a\nb.Name = "contract"\nDebug.Print b.Scale(amount:=5), b.Name\nDebug.Print a Is b, TypeOf b Is IValue, TypeOf b Is Value\nDebug.Print CallByName(b, "Scale", vbMethod, 4, 3)'),iValue,value]);assert.deepEqual(output,['10 contract','True True True','12']);});
test('interface view does not expose implementation-specific members',async()=>{await assert.rejects(()=>run([main('Dim b As IValue\nSet b = New Value\nDebug.Print b.Own()'),iValue,value]),e=>e.number===438);});
test('implementation private members cannot be called on concrete class',async()=>{await assert.rejects(()=>run([main('Dim a As New Value\nDebug.Print a.IValue_Scale(2)'),iValue,value]),e=>e.number===438);});
test('unsupported object-to-interface cast is rejected',async()=>{await assert.rejects(()=>run([main('Dim a As IValue\nSet a = New Other'),iValue,module('Other','')]),e=>e.number===13);});
test('two views of an object share state and identity',async()=>{const {output}=await run([main('Dim x As New Value, a As IValue, b As IValue\nSet a = x\nSet b = x\na.Name = "shared"\nDebug.Print b.Name, a Is b\nSet a = Nothing\nDebug.Print b.Name'),iValue,value]);assert.deepEqual(output,['shared True','shared']);});
test('interface ByVal and ByRef parameters dispatch against public contract',async()=>{const m=main('Dim x As New Value\nUseVal x\nUseRef x');m.code+='\nSub UseVal(ByVal x As IValue)\nDebug.Print x.Scale(3)\nEnd Sub\nSub UseRef(ByRef x As IValue)\nDebug.Print x.Scale(4)\nEnd Sub';assert.deepEqual((await run([m,iValue,value])).output,['6','8']);});
test('interfaces support public field contracts through property procedures',async()=>{const i=module('IPerson','Public Name As String'),c=module('Person','Implements IPerson\nPrivate n As String\nPrivate Property Get IPerson_Name() As String\nIPerson_Name = n\nEnd Property\nPrivate Property Let IPerson_Name(value As String)\nn = value\nEnd Property');assert.deepEqual((await run([main('Dim p As IPerson\nSet p = New Person\np.Name = "Alice"\nDebug.Print p.Name'),i,c])).output,['Alice']);});
for(const [title,modules,pattern]of [
 ['missing member',[iValue,module('Value','Implements IValue')],/must implement/i],
 ['unknown class',[module('Value','Implements Missing')],/not found/i],
 ['self interface',[module('Value','Implements Value')],/itself/i],
 ['wrong signature',[module('I','Public Function A(x As Long) As Long\nEnd Function'),module('C','Implements I\nPrivate Function I_A(x As String) As Long\nEnd Function')],/does not match/i],
 ['standard module',[module('M','Implements IValue','module'),iValue],/class or form/i],
 ['duplicate',[module('C','Implements IValue\nImplements IValue'),iValue],/Duplicate/i]])test('interface validation: '+title,()=>assert.ok(compileProject({name:'P',modules}).diagnostics.some(d=>pattern.test(d.message))));
test('default property participates in scalar operations and assignment',async()=>{const c=module('Box','Private n As Long\nPublic Property Get Value() As Long\nValue = n\nEnd Property\nPublic Property Let Value(ByVal value As Long)\nn = value\nEnd Property','class',['Attribute Value.VB_UserMemId = 0']);assert.deepEqual((await run([main('Dim b As New Box\nb = 7\nDebug.Print b + 2\nDim copy As Object\nSet copy = b\nDebug.Print b Is copy'),c])).output,['9','True']);});
test('indexed default properties retain argument and writeback semantics',async()=>{const c=module('Bag','Private n As Long\nPublic Property Get At(ByVal index As Long) As Long\nAt = n + index\nEnd Property\nPublic Property Let At(ByVal index As Long, ByVal value As Long)\nn = value - index\nEnd Property','class',['Attribute At.VB_UserMemId = 0']);assert.deepEqual((await run([main('Dim b As New Bag\nb(3) = 10\nDebug.Print b(4)'),c])).output,['11']);});
test('inline default-member attributes are removed before bytecode generation',async()=>{const c=module('Box','Public Function Value() As Long\nAttribute Value.VB_UserMemId = 0\nValue = 4\nEnd Function');assert.deepEqual((await run([main('Dim b As New Box\nDebug.Print b + 1'),c])).output,['5']);});
test('multiple default members are rejected',()=>assert.throws(()=>compileModule(module('C','Public Function A() As Long\nEnd Function\nPublic Function B() As Long\nEnd Function','class',['Attribute A.VB_UserMemId = 0','Attribute B.VB_UserMemId = 0'])),/Only one/));
test('module Def types cover declarations, parameters and function return',async()=>{const m=module('M','DefInt A-C\nDefStr X-Z\nDim count, zed\nFunction Add(a, b)\nAdd = a + b\nEnd Function\nSub Main()\nDim alpha, xray\nDebug.Print alpha, xray & "!", Add(2.5, 2.5)\nDebug.Print count, zed & "?"\nEnd Sub','module');const c=compileModule(m);assert.equal(c.procedures.get('add').returnType,'Integer');assert.equal(c.procedures.get('add').params[0].type,'Integer');assert.deepEqual((await run([m])).output,['0 ! 4','0 ?']);});
test('Def types apply to implicit names but explicit As/suffix win',async()=>{const m=module('M','DefStr A-Z\nSub Main()\nDim x As Long, y%, z$\nx = 8\ny = 3.5\nalphabet = 3\nDebug.Print x, y, TypeName(alphabet), Len(z)\nEnd Sub','module');assert.deepEqual((await run([m])).output,['8 4 String 0']);});
test('Def types are local to their module',async()=>assert.deepEqual((await run([module('M','DefStr A-Z\nSub Main()\nOther\nEnd Sub','module'),module('N','Sub Other()\nDim a\nDebug.Print IsEmpty(a)\nEnd Sub','module')])).output,['True']));
for(const source of ['DefInt Z-A','DefInt A-C\nDefStr C-D','DefStr AA','Sub Main()\nDefInt A-Z\nEnd Sub','DefStr A-Z\nType R\nfield\nEnd Type'])test('invalid default types: '+source.split('\n')[0],()=>assert.throws(()=>compileModule(module('M',source,'module'))));
test('diagnostics cache invalidates procedure attribute changes',()=>{const p={name:'P',modules:[module('C','Public Function Value() As Long\nEnd Function')]},cache=new ProjectDiagnosticCache();assert.equal(cache.check(diagnosticSnapshot(p)).valid,true);p.modules[0].attributes=['Attribute NotThere.VB_UserMemId = 0'];assert.equal(cache.check(diagnosticSnapshot(p)).valid,false);});
