import test from 'node:test';import assert from 'node:assert/strict';
import {newProject,createControl,normalizeProject} from '../src/project/model.js';
import {layoutEdit,editLayoutProperties,addAutoLayout,removeAutoLayout,reorderControls,reparentControls,worldBounds,selectedRoots,descendantIds} from '../src/layout/authoring.js';
import {layoutProperty,LAYOUT_DEFAULTS,layoutDefaults} from '../src/layout/contract.js';
import {layoutNode,layoutInsets,arrangeFormEdit} from '../src/layout/model.js';
import {GuideIndex,distanceGuides,insertionGuide,gapRegions} from '../src/layout/guides.js';
import {nativeLayoutSeed} from '../src/native/layout-seed.js';
import {compileProject} from '../src/language/compiler.js';
import {EditorIntelligence} from '../src/editor/intelligence.js';
const make=()=>{const p=newProject('Layout'),f=p.modules[0].form;p.settings.anchoring=true;f.controls=[createControl('CommandButton','A',100,100),createControl('CommandButton','B',1700,100),createControl('CommandButton','C',3300,100)];f.controls.forEach((c,i)=>{c.id='c'+i;Object.assign(c.properties,{Width:1200,Height:400});});return {p,f};};
test('wrapping produces a named Frame, retains IDs and preserves event source',()=>{const {f}=make(),old=JSON.stringify(f),out=layoutEdit(f,d=>addAutoLayout(d,['c0','c1'])),wrapper=out.form.controls.find(c=>c.id===out.selection[0]);assert.equal(JSON.stringify(f),old);assert.equal(wrapper.name,'LayoutFrame1');assert.equal(wrapper.properties.LayoutMode,1);assert.equal(wrapper.properties.LayoutGap,400);assert.equal(wrapper.properties.Width,2800);assert.equal(wrapper.properties.Height,400);assert.equal(wrapper.properties.LayoutWidthMode,1);for(const id of ['c0','c1'])assert.equal(out.form.controls.find(c=>c.id===id).nativeParentId,wrapper.id);});
test('enabling a single existing container uses its children instead of wrapping it',()=>{const {f}=make();const out=layoutEdit(f,d=>addAutoLayout(d,[]));assert.equal(out.form.controls.length,3);assert.equal(out.form.properties.LayoutMode,1);});
test('batch layout properties validate merged min/max before publishing',()=>{const {f}=make();f.controls[0].properties.MaximumWidth=1300;const out=layoutEdit(f,d=>editLayoutProperties(d,['c0'],{MinimumWidth:1400,MaximumWidth:1800}));assert.equal(out.form.controls[0].properties.Width,1400);const old=JSON.stringify(f);assert.throws(()=>layoutEdit(f,d=>editLayoutProperties(d,['c0','c1'],{MinimumWidth:900,MaximumWidth:500})));assert.equal(JSON.stringify(f),old);});
test('bad selections, unknown properties and nonvisual controls reject atomically',()=>{const {f}=make();f.controls.push(createControl('Timer','Timer1'));assert.throws(()=>layoutEdit(f,d=>editLayoutProperties(d,['c0','missing'],{LayoutMode:1})));assert.throws(()=>layoutEdit(f,d=>editLayoutProperties(d,['c0'],{Unregistered:1})));assert.throws(()=>layoutEdit(f,d=>addAutoLayout(d,[d.controls.at(-1).id])));assert.throws(()=>layoutEdit(f,()=>['missing']));});
test('reparenting preserves world geometry and nested identities',()=>{const {f}=make(),frame=createControl('Frame','Frame1',500,500);frame.id='parent';f.controls.push(frame);const before=worldBounds(f),out=layoutEdit(f,d=>reparentControls(d,['c1'],'parent'));const c=out.form.controls.find(c=>c.id==='c1');assert.equal(c.parent,'Frame1');assert.equal(c.nativeParentId,'parent');assert.deepEqual(worldBounds(out.form).get('c1'),before.get('c1'));});
test('reparenting into flow resets stale explicit grid placement',()=>{const {f}=make();f.properties.LayoutMode=5;f.controls[0].properties.LayoutColumn=1;f.controls[0].properties.LayoutRow=1;const out=layoutEdit(f,d=>reparentControls(d,['c0'],null,2));assert.equal(out.form.controls[2].id,'c0');assert.equal(out.form.controls[2].properties.LayoutColumn,-1);assert.equal(out.form.controls[2].properties.LayoutRow,-1);});
test('reparenting prevents cycles and wrapping rejects mixed parents',()=>{const {f}=make(),frame=createControl('Frame','Frame1',0,0);frame.id='parent';f.controls.push(frame);f.controls[0].parent=frame.name;f.controls[0].nativeParentId=frame.id;assert.throws(()=>layoutEdit(f,d=>reparentControls(d,['parent'],'c0')),/container/);assert.throws(()=>layoutEdit(f,d=>reparentControls(d,['parent'],'parent')),/ancestor/);assert.throws(()=>layoutEdit(f,d=>addAutoLayout(d,['c0','c1'])),/one container/);assert.throws(()=>layoutEdit(f,d=>reparentControls(d,['c1'],null,NaN)),/index/);});
test('stable multi-selection one-step reorder does not reverse selected children',()=>{const {f}=make(),out=layoutEdit(f,d=>reorderControls(d,['c1','c2'],-1));assert.deepEqual(out.form.controls.map(c=>c.id),['c1','c2','c0']);const back=layoutEdit(out.form,d=>reorderControls(d,['c1','c2'],1));assert.deepEqual(back.form.controls.map(c=>c.id),['c0','c1','c2']);});
test('remove auto layout keeps the container and current geometry',()=>{const {f}=make(),out=layoutEdit(f,d=>addAutoLayout(d,['c0','c1'])),before=out.form.controls.map(c=>[c.id,c.properties.Left,c.properties.Top,c.properties.Width,c.properties.Height]),removed=layoutEdit(out.form,d=>removeAutoLayout(d,out.selection));assert.deepEqual(removed.form.controls.map(c=>[c.id,c.properties.Left,c.properties.Top,c.properties.Width,c.properties.Height]),before);assert.equal(removed.form.controls[0].properties.LayoutMode,0);});
test('per-edge insets inherit linked values and grid strings round-trip through project normalization',()=>{const {p,f}=make();Object.assign(f.properties,{LayoutMode:5,LayoutGridColumns:'1200 hug 2fr',LayoutGridRows:'',LayoutPadding:120,LayoutPaddingLeft:300});assert.deepEqual(layoutInsets(f.properties),[120,120,120,300]);const copy=normalizeProject(p);assert.equal(copy.modules[0].form.properties.LayoutGridColumns,'1200 hug 2fr');assert.equal(copy.modules[0].form.properties.LayoutGridRows,'');});
test('setting a Fill child resolves a same-axis Hug parent to Fixed in authored state',()=>{const {f}=make(),out=layoutEdit(f,d=>addAutoLayout(d,['c0','c1'])),wrapper=out.form.controls[0];const next=layoutEdit(out.form,d=>editLayoutProperties(d,['c0'],{LayoutWidthMode:2}));assert.equal(next.form.controls[0].properties.LayoutWidthMode,0);assert.equal(next.form.controls[0].properties.Width,wrapper.properties.Width);});
test('manual resize changes only the resized sizing axis to Fixed',()=>{const {f}=make(),out=layoutEdit(f,d=>addAutoLayout(d,['c0','c1']));const next=layoutEdit(out.form,d=>{d.controls[0].properties.Width+=600;return [d.controls[0].id];});assert.equal(next.form.controls[0].properties.LayoutWidthMode,0);assert.equal(next.form.controls[0].properties.LayoutHeightMode,1);});
test('unknown custom controls use authored intrinsic fallback, not a feedback callback',()=>{const {f}=make();f.controls[0].type='CustomOcx';f.controls[0].properties.LayoutWidthMode=1;const n=layoutNode(f.controls[0]);assert.equal(n.measure,undefined);assert.equal(n.preferredWidth,1200);});
test('deep hierarchy selection and world transforms are iterative',()=>{const {f}=make();f.controls=Array.from({length:10000},(_,i)=>({id:String(i),name:'F'+i,type:'Frame',parent:i?'F'+(i-1):null,nativeParentId:i?String(i-1):null,properties:{Left:1,Top:1,Width:10,Height:10}}));assert.deepEqual(selectedRoots(f,['0','9999']).map(c=>c.id),['0']);assert.equal(descendantIds(f,['0']).size,10000);assert.equal(worldBounds(f).get('9999').x,10000);});
test('new constants and contextual sizing completions follow the strict project flag',()=>{const {p,f}=make(),m=p.modules[0],s=new EditorIntelligence();m.code='Private Const Flow As Long = vbLayoutGrid\nPrivate Const SizeMode As Long = vbLayoutSizeHug';assert.ok(compileProject(p).valid);const text='A.LayoutWidthMode = ';assert.ok(s.completions(p,m,1,text,text.length).items.some(i=>i.name==='vbLayoutSizeFill'));p.settings.anchoring=false;assert.equal(compileProject(p).valid,false);assert.equal(s.completions(p,m,1,'A.',2).items.some(i=>i.name==='LayoutWidthMode'),false);});
for(const changes of [{LayoutMode:4},{LayoutMode:5},{LayoutWidthMode:1},{LayoutIgnore:-1},{LayoutGridRows:'1fr'},{LayoutPaddingLeft:50},{LayoutGap:-1},{LayoutAlign:4}])test('freestanding native export diagnoses '+JSON.stringify(changes),()=>{const {p,f}=make();Object.assign(f.controls[0].properties,changes);assert.throws(()=>nativeLayoutSeed(p),/HTML\/Electron/);});
test('native seed retains public Inherit value while classic anchoring remains supported',()=>{const {p}=make(),seed=nativeLayoutSeed(p);assert.equal(seed.rows[2][22],5);});
test('guide index aligns moving edges without snapping a stationary resize edge',()=>{const index=new GuideIndex([{id:1,x:100,y:80,width:40,height:20}]);const out=index.snap({x:0,y:0,width:99,height:79},2,{xEdges:[2],yEdges:[2]});assert.equal(out.dx,1);assert.equal(out.dy,1);assert.equal(out.guides.length,2);});
test('guide exclusion, negative-coordinate distances and wrap insertion are deterministic',()=>{const r=[{id:'a',x:-80,y:20,width:40,height:20},{id:'b',x:0,y:20,width:40,height:20},{id:'c',x:-80,y:60,width:40,height:20}];assert.equal(new GuideIndex(r,{exclude:['a']}).rects.length,2);assert.equal(distanceGuides(r[0],r[1])[0].value,40);assert.equal(insertionGuide(r,{x:-90,y:65},3,{x:0,y:0,width:100,height:100}).index,2);assert.equal(gapRegions(r,1).length,1);});
test('classic property defaults remain free of extension members',()=>{const c=createControl('CommandButton','Original');for(const key of Object.keys(LAYOUT_DEFAULTS))assert.equal(Object.hasOwn(c.properties,key),false);assert.deepEqual(layoutDefaults(createControl('Timer')),{});});

test('smart spacing repeats neighboring gaps and centers between peers',()=>{const index=new GuideIndex([{id:'a',x:0,y:0,width:40,height:20},{id:'b',x:60,y:0,width:40,height:20}]);let out=index.snap({x:119,y:0,width:40,height:20},2);assert.equal(out.dx,1);assert.ok(out.guides.some(g=>g.kind==='equal-gap'));const wide=new GuideIndex([{id:'a',x:0,y:0,width:20,height:20},{id:'b',x:100,y:0,width:20,height:20}]);out=wide.snap({x:49,y:0,width:20,height:20},2);assert.equal(out.dx,1);assert.deepEqual(out.guides.filter(g=>g.kind==='equal-gap').map(g=>g.value),[30,30]);});
test('resize size guides match sibling dimensions while retaining the opposite edge',()=>{const index=new GuideIndex([{id:'a',x:200,y:100,width:40,height:20}]);const out=index.snap({x:0,y:0,width:39,height:19},2,{resize:'se',xEdges:[2],yEdges:[2]});assert.equal(out.dx,1);assert.equal(out.dy,1);assert.equal(out.guides.filter(g=>g.kind==='size').length,2);});


test('grid property fields accept bounded per-track limits without evaluating source',()=>{
  const p=layoutProperty('LayoutGridColumns','[{"size":"1fr","min":600,"max":1800},"2fr"]');
  assert.equal(typeof p,'string');
  assert.throws(()=>layoutProperty('LayoutGridColumns','[{"size":"1fr","min":900,"max":100}]'));
  assert.throws(()=>layoutProperty('LayoutGridColumns','[process.exit()]'));
});
