import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {publishAtomicSnapshot,nativeSnapshot,readStableNativeFolder} from '../tools/native-snapshot.mjs';
import {readZip} from '../src/project/zip.js';
import {verifyClassicRoundtrip,classicRoundtripOptions} from '../tools/verify-classic-roundtrip.mjs';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'vb6-interop-test-'));
let sequence=0;const dir=async()=>{const d=path.join(root,String(++sequence));await fs.mkdir(d);return d;};
test.after(()=>fs.rm(root,{recursive:true,force:true}));
test('atomic snapshot publishes complete file and refuses overwrite',async()=>{const d=await dir(),p=path.join(d,'p.zip'),b=Uint8Array.of(1,2,3);const r=await publishAtomicSnapshot(p,b);assert.equal(r.size,3);assert.deepEqual(await fs.readFile(p),Buffer.from(b));await assert.rejects(()=>publishAtomicSnapshot(p,new Uint8Array([9])),e=>e.code==='EEXIST');assert.deepEqual(await fs.readdir(d),['p.zip']);});
test('two racing snapshot publishers have exactly one winner',async()=>{const d=await dir(),p=path.join(d,'p.zip'),r=await Promise.allSettled([publishAtomicSnapshot(p,Uint8Array.of(1)),publishAtomicSnapshot(p,Uint8Array.of(2))]);assert.equal(r.filter(v=>v.status==='fulfilled').length,1);assert.ok([1,2].includes((await fs.readFile(p))[0]));assert.deepEqual(await fs.readdir(d),['p.zip']);});
test('whole native snapshot is independently readable with exact binary content',async()=>{const d=await dir();await fs.writeFile(path.join(d,'P.vbp'),'Type=Exe');await fs.writeFile(path.join(d,'P.frx'),Uint8Array.of(0,255));const p=path.join(root,'full.zip');await nativeSnapshot(d,p);const entries=await readZip(await fs.readFile(p));assert.equal(entries.size,2);assert.deepEqual(entries.get('P.frx'),Uint8Array.of(0,255));});
test('snapshot destination inside input is rejected',async()=>{const d=await dir();await assert.rejects(()=>nativeSnapshot(d,path.join(d,'bad.zip')),/outside/);});
test('native snapshot ignores recovery backups',async()=>{const d=await dir();await fs.mkdir(path.join(d,'.vb6-save-journal'));await fs.writeFile(path.join(d,'.vb6-save-journal','secret'),'old');await fs.writeFile(path.join(d,'P.vbp'),'new');assert.equal((await readStableNativeFolder(d)).size,1);});
test('round-trip staging exercises original and reopened source in both compiler modes without claiming compilation',async()=>{const d=await dir(),out=path.join(d,'report');const r=await verifyClassicRoundtrip({project:'examples/classic/HelloRuntime.vbp',out});assert.equal(r.compilerStatus,'not-run');assert.equal(r.ideStatus,'not-run');assert.equal(r.builds.length,4);assert.ok(r.builds.every(b=>!b.compiled));assert.equal(JSON.parse(await fs.readFile(path.join(out,'report.json'),'utf8')).bytePreservation,true);});
test('round-trip report does not turn a mocked or missing compiler into a pass',async()=>{const d=await dir(),out=path.join(d,'report');await assert.rejects(()=>verifyClassicRoundtrip({project:'examples/classic/HelloRuntime.vbp',out,compile:true,allowNativeCode:true},{builder:async()=>({compiled:false})}),/did not confirm/);assert.equal(JSON.parse(await fs.readFile(path.join(out,'report.json'),'utf8')).compilerStatus,'failed');});
test('native certification command requires explicit consent',()=>{assert.throws(()=>classicRoundtripOptions(['--project','P.vbp','--out','x','--compile']),/requires/);assert.throws(()=>classicRoundtripOptions(['--project','P.vbp','--out','x','--ide-smoke']),/requires/);});
test('round-trip output must be a new directory',async()=>{const d=await dir();await assert.rejects(()=>verifyClassicRoundtrip({project:'examples/classic/HelloRuntime.vbp',out:d}),e=>e.code==='EEXIST');});
