import test from 'node:test';
import assert from 'node:assert/strict';
import {ControlAdapterRegistry} from '../src/controls/adapters.js';
import {OcxPropertyBag,ocxControlSite} from '../src/controls/ocx-site.js';
import {VBArray,VBCurrency,VBDecimal,NOTHING,VBErrorValue,tagScalar,scalarType} from '../src/runtime/values.js';
import {createControl,newProject} from '../src/project/model.js';
import {encodeAutomationValue} from '../src/runtime/automation-wire.js';
import {declarationTargets,handlerEdit} from '../src/editor/event-completion.js';
const metadata={baseName:'Gauge',displayName:'Acme Gauge',properties:[{name:'Value',default:25,description:'Current reading'},{name:'Mode',default:0,choices:[{value:0,label:'Automatic'},{value:1,label:'Manual'}]},{name:'Serial',default:'ABC',readOnly:true}],events:[{name:'Changing',params:[{name:'Value',type:'Long'},{name:'Cancel',type:'Boolean',byRef:true}]}],defaultEvent:'Changing'};
const adapter=(model,options)=>({__control:true,model,node:{},refresh(){},dispose(){},event(){return options;}});
const registry=options=>new ControlAdapterRegistry().register('Acme.Gauge.1',{runtime:adapter,designer:adapter,metadata,...options});
test('component metadata is detached, frozen, case-insensitive and does not activate code',()=>{let calls=0;const input=structuredClone(metadata),r=new ControlAdapterRegistry().register('Acme.Gauge',{metadata:input,runtime(){calls++;}});input.properties[0].default=900;assert.equal(r.defaults('ACME.GAUGE').Value,25);assert.equal(r.describe('acme.gauge').baseName,'Gauge');assert.equal(calls,0);assert.throws(()=>r.describe('Acme.Gauge').properties.push({}),TypeError);assert.equal(r.property('acme.gauge','serial').readOnly,true);});
test('metadata rejects source injection, duplicate properties, invalid enums and event modes',()=>{for(const m of [{baseName:'A.B'},{properties:[{name:'constructor'}]},{properties:[{name:'X'},{name:'x'}]},{events:[{name:'Foo\nEnd Sub'}]},{events:[{name:'Changed',params:[{name:'Value',type:'X\nEnd Sub'}]}]},{properties:[{name:'Style',default:2,choices:[{value:0,label:'Zero'}]}]},{defaultEvent:'Missing'}])assert.throws(()=>new ControlAdapterRegistry().register('Test.C',{runtime:adapter,metadata:m}),TypeError);});
test('property metadata validates readonly, enums and value types before mutation',()=>{const r=registry();assert.throws(()=>r.validateProperties('Acme.Gauge.1',{Serial:'NEW'}),/read-only/);assert.throws(()=>r.validateProperties('Acme.Gauge.1',{Mode:2}),/choice/);assert.throws(()=>r.validateProperties('Acme.Gauge.1',{Value:'x'}),/type/);assert.doesNotThrow(()=>r.validateProperties('Acme.Gauge.1',{Mode:1,Value:55}));});
test('trusted property pages receive detached state and cannot change readonly fields',async()=>{const model=createControl('Acme.Gauge.1','Gauge1'),r=registry({propertyPages:async m=>{m.name='Changed';return {Value:80};}});assert.deepEqual(await r.editProperties(model),{Value:80});assert.equal(model.name,'Gauge1');await assert.rejects(()=>registry({propertyPages:()=>({Serial:'BAD'})}).editProperties(model),/read-only/);assert.equal(await registry({propertyPages:()=>null}).editProperties(model),null);});
test('property bag preserves exact variants and nonzero multidimensional array bounds',()=>{const bag=new OcxPropertyBag(),array=new VBArray([[-1,0],[2,3]]);array.data=[1,'text',null,NOTHING];const entries={Caption:'Hello',Empty:undefined,Null:null,Nothing:NOTHING,Currency:new VBCurrency('123.4567'),Decimal:new VBDecimal('123456789.123456789'),Date:new Date(2020,1,3,4,5,6),Error:new VBErrorValue(7),Array:array};for(const [k,v] of Object.entries(entries))bag.WriteProperty(k,v);const restored=new OcxPropertyBag(JSON.parse(JSON.stringify(bag.Contents)));for(const [k,v] of Object.entries(entries)){const value=restored.ReadProperty(k.toLowerCase());if(v instanceof VBArray){assert.deepEqual(value.bounds,v.bounds);assert.deepEqual(value.data,v.data);assert.equal(value.type,v.type);assert.deepEqual(encodeAutomationValue(value),encodeAutomationValue(v));}else assert.deepEqual(value,v);}assert.equal(restored.Count,Object.keys(entries).length);});
test('property bag defaults, snapshots and replacement are transactional and detached',()=>{const b=new OcxPropertyBag();b.WriteProperty('Caption','x');b.WriteProperty('caption','default','default');assert.equal(b.Count,0);assert.equal(b.ReadProperty('caption','default'),'default');b.WriteProperty('Value',10);const snapshot=b.Contents;snapshot.properties[0].value.v=22;assert.equal(b.ReadProperty('value'),10);assert.throws(()=>b.Contents={...b.Contents,properties:[...b.Contents.properties,{name:'VALUE',value:{t:'number',v:1}}]},/Duplicate/);assert.equal(b.ReadProperty('Value'),10);assert.throws(()=>b.WriteProperty('Object',{}),TypeError);assert.throws(()=>b.Contents={...b.Contents,properties:[{name:'Object',value:{t:'object',id:'o1'}}]},/Unexpected native object/);assert.equal(b.Count,1);});
test('property bags enforce bounded names, count, versions and cumulative size',()=>{const b=new OcxPropertyBag();assert.throws(()=>b.WriteProperty('__proto__',1),TypeError);assert.throws(()=>new OcxPropertyBag({format:'VB6.OCX.PropertyBag',version:2,properties:[]}),TypeError);for(let i=0;i<256;i++)b.WriteProperty('P'+i,i);assert.throws(()=>b.WriteProperty('P256',256),TypeError);assert.equal(b.Count,256);const big=new OcxPropertyBag();big.WriteProperty('A','a'.repeat(500000));big.WriteProperty('B','b'.repeat(500000));assert.throws(()=>big.WriteProperty('C','c'.repeat(100000)),RangeError);assert.equal(big.Count,2);});
test('control site initializes once, persists state, supplies ambient properties and terminates once',async()=>{const log=[],factory=(model,{ocxSite})=>({...adapter(model,{}),ocxLifecycle:{initProperties(site){log.push('init');assert.equal(site,ocxSite);},readProperties(b){log.push('read:'+b.ReadProperty('Value'));},writeProperties(b){b.WriteProperty('Value',123);log.push('write');},terminate(){log.push('terminate');}},event(name,args){log.push(name+':'+args[0]);},dispose(){log.push('dispose');}}),r=registry({runtime:factory,designer:factory,lifecycle:true}),model=createControl('Acme.Gauge.1','Gauge1');const control=r.create(model,{design:true,form:{props:{BackColor:10}}}),site=ocxControlSite(control);assert.equal(site.Ambient.UserMode,0);assert.equal(site.Ambient.BackColor,10);assert.equal(site.Extender,control);site.PropertyChanged('Value');assert.equal(site.Dirty,true);model.ocxState=r.save(control);assert.equal(site.Dirty,false);await site.RaiseEvent('Changing',[2]);control.dispose();control.dispose();assert.equal(ocxControlSite(control),null);assert.throws(()=>site.save(),/not active/);const restored=r.create(model);assert.equal(ocxControlSite(restored).Ambient.UserMode,-1);await ocxControlSite(restored).RaiseEvent('Changing',[3]);restored.dispose();assert.deepEqual(log,['init','write','terminate','dispose','read:123','Changing:3','terminate','dispose']);});
test('failed portable initialization disposes the instance and terminates its site',()=>{const log=[],r=registry({lifecycle:true,runtime:model=>({...adapter(model,{}),ocxLifecycle:{initProperties(){throw Error('bad state');},terminate(){log.push('terminate');}},dispose(){log.push('dispose');}})});assert.throws(()=>r.create(createControl('Acme.Gauge.1')),/bad state/);assert.deepEqual(log,['terminate','dispose']);});
test('custom event targets generate typed ByRef handlers and control-array Index without factory calls',()=>{const project=newProject(),module=project.modules.find(m=>m.form),model=createControl('Acme.Gauge.1','Gauge1');model.properties.Index=2;module.form.controls.push(model);const r=registry(),service={index:()=>({symbols:[],interfaces:[],procedures:[]})};const target=declarationTargets(project,module,service,r).find(t=>t.name==='Gauge1');assert.deepEqual(target.members[0].params,['Index As Integer','ByVal Value As Long','ByRef Cancel As Boolean']);const edit=handlerEdit(project,module,service,'Gauge1','Changing',r);assert.match(edit.text,/Private Sub Gauge1_Changing\(Index As Integer, ByVal Value As Long, ByRef Cancel As Boolean\)/);});

test('Boolean metadata uses VB truth values and property bags preserve the Boolean wire tag',()=>{const r=new ControlAdapterRegistry().register('Test.Boolean',{runtime:adapter,metadata:{properties:[{name:'Checked',default:true}]}});assert.equal(r.defaults('Test.Boolean').Checked,-1);assert.deepEqual(r.property('Test.Boolean','Checked').choices,[{value:0,label:'False'},{value:-1,label:'True'}]);r.validateProperties('Test.Boolean',{Checked:0});const b=new OcxPropertyBag();b.WriteProperty('Checked',true);assert.deepEqual(b.Contents.properties[0].value,{t:'boolean',v:true});assert.equal(b.ReadProperty('Checked'),-1);});

test('property bags retain every numeric subtype through explicit scalar reads',()=>{
 const bag=new OcxPropertyBag();for(const type of ['byte','integer','long','single','double','boolean'])bag.WriteProperty(type,tagScalar(type==='boolean'?-1:7,type));
 const copy=new OcxPropertyBag(JSON.parse(JSON.stringify(bag.Contents)));
 for(const type of ['byte','integer','long','single','double','boolean']){assert.equal(scalarType(copy.ReadPropertyScalar(type)),type);assert.equal(typeof copy.ReadProperty(type),'number');}
 assert.deepEqual(copy.Contents,bag.Contents);assert.equal(copy.ReadPropertyScalar('Missing',null),null);
});


test('Byte control events retain the declaration in generated handlers',()=>{
 const project=newProject(),module=project.modules.find(m=>m.form),model=createControl('Test.Byte','ByteControl1');module.form.controls.push(model);
 const r=new ControlAdapterRegistry().register('Test.Byte',{runtime:adapter,metadata:{events:[{name:'Changed',params:[{name:'Value',type:'Byte',byRef:true}]}]}}),service={index:()=>({symbols:[],interfaces:[],procedures:[]})};
 assert.match(handlerEdit(project,module,service,'ByteControl1','Changed',r).text,/Private Sub ByteControl1_Changed\(ByRef Value As Byte\)/);
});
