import test from 'node:test';
import assert from 'node:assert/strict';
import {browseNativeControlProperty} from '../tools/interop/ocx-property-browsing.mjs';
const result=()=>({supported:true,displaySupported:true,display:'Automatic',pageSupported:true,page:'559a7bce-8f46-4c42-9c1e-e19d015da019',predefinedSupported:true,predefined:[{label:'Automatic',cookie:0xffffffff,value:{t:'number',vt:2,v:-1}}]});
function setup(reply=result()){const calls=[];return {calls,client:{lcid:1045,request:async r=>{calls.push(r);return reply;}}};}
test('property browsing uses the owned handle, exposed name and client locale without native setters',async()=>{const {client,calls}=setup();assert.deepEqual(await browseNativeControlProperty(client,'o1','Appearance'),result());assert.deepEqual(calls,[{op:'controlBrowseProperty',handle:'o1',member:'Appearance',lcid:1045}]);});
test('property snapshots preserve unsigned cookies and tagged values and cannot be mutated',async()=>{const reply=result(),{client}=setup(reply),snapshot=await browseNativeControlProperty(client,'o1','Appearance');reply.predefined[0].value.v=5;assert.equal(snapshot.predefined[0].value.v,-1);assert.throws(()=>snapshot.predefined.push({}));assert.throws(()=>snapshot.predefined[0].value.v=3);});
test('unsupported per-property interface is explicit',async()=>{const {client}=setup({supported:false});assert.deepEqual(await browseNativeControlProperty(client,'o1','Appearance'),{supported:false});});
test('individual optional capabilities remain distinguishable from an empty predefined list',async()=>{const reply={supported:true,displaySupported:false,display:null,pageSupported:false,page:null,predefinedSupported:false,predefined:[]};assert.deepEqual(await browseNativeControlProperty(setup(reply).client,'o1','A'),reply);reply.predefinedSupported=true;assert.equal((await browseNativeControlProperty(setup(reply).client,'o1','A')).predefinedSupported,true);});
test('invalid identifiers, handles and locales fail before transport',async()=>{const {client,calls}=setup();for(const name of ['','constructor','Prototype','__proto__','Name\0','A'.repeat(256),1,null])await assert.rejects(browseNativeControlProperty(client,'o1',name));for(const handle of ['x1','o0','o-1','o1\n',{},null])await assert.rejects(browseNativeControlProperty(client,handle,'A'));for(const lcid of [-1,1.5,'1033',0x100000])await assert.rejects(browseNativeControlProperty({...client,lcid},'o1','A'));assert.equal(calls.length,0);});
test('native HRESULT rejection is not converted into unsupported metadata',async()=>{const failure=Object.assign(Error('E_FAIL'),{hresult:-2147467259});await assert.rejects(browseNativeControlProperty({lcid:1033,request:async()=>{throw failure;}},'o1','A'),error=>error===failure);});
test('malformed native capability and predefined responses fail closed',async()=>{for(const change of [{supported:1},{displaySupported:0},{display:5},{display:'a'.repeat(4097)},{page:'invalid'},{pageSupported:false},{predefinedSupported:false},{predefined:new Array(257).fill(result().predefined[0])},{predefined:[{label:'x',cookie:-1,value:{t:'empty'}}]},{predefined:[{label:'x',cookie:0x100000000,value:{t:'empty'}}]},{predefined:[{label:'x',cookie:1.5,value:{t:'empty'}}]}])await assert.rejects(browseNativeControlProperty(setup({...result(),...change}).client,'o1','A'));});
test('metadata queries cannot smuggle newly adopted native objects including nested arrays',async()=>{for(const value of [{t:'object',id:'o2'},{t:'array',elementType:12,bounds:[[0,0]],v:[{t:'object',id:'o2'}]}]){const reply=result();reply.predefined[0].value=value;await assert.rejects(browseNativeControlProperty(setup(reply).client,'o1','A'));}});
test('raw DATE precision, currency, decimal and typed array descriptors are retained',async()=>{for(const value of [{t:'date',v:44000.500000001},{t:'currency',v:'123.4567'},{t:'decimal',v:'12.125'},{t:'array',elementType:17,bounds:[[-1,0]],v:[{t:'number',vt:17,v:2},{t:'number',vt:17,v:3}]}]){const reply=result();reply.predefined[0].value=value;assert.deepEqual((await browseNativeControlProperty(setup(reply).client,'o1','A')).predefined[0].value,value);}});
