import test from 'node:test';
import assert from 'node:assert/strict';
import {VirtualMachine} from '../src/runtime/vm.js';
import {virtualKey,characterKey,mouseButton,shiftMask,mouseCoordinates} from '../src/controls/input.js';
for(const [key,code,wanted]of [['ArrowLeft','ArrowLeft',37],['ArrowUp','ArrowUp',38],['ArrowRight','ArrowRight',39],['ArrowDown','ArrowDown',40],['a','KeyA',65],['Z','KeyZ',90],['F12','F12',123],['Enter','Enter',13],['Escape','Escape',27],['Tab','Tab',9],['Backspace','Backspace',8],['1','Numpad1',97],['+','NumpadAdd',107],[';','Semicolon',186],['Unidentified','KeyQ',81]])test(`virtual key ${key}/${code}`,()=>assert.equal(virtualKey({key,code,keyCode:0}),wanted));
for(const [key,wanted]of [['a',97],['A',65],['Enter',13],['Backspace',8],['Tab',9],['ArrowLeft',0],['Dead',0],['😀',0]])test('character key '+key,()=>assert.equal(characterKey({key}),wanted));
test('mouse button ordinal, released button, held chord and hover masks',()=>{for(const [button,buttons,kind,wanted]of [[0,0,'MouseMove',0],[-1,0,'MouseMove',0],[0,3,'MouseMove',3],[1,4,'MouseDown',4],[2,2,'MouseDown',2],[0,1,'MouseDown',1],[2,0,'MouseUp',2],[1,0,'MouseUp',4],[0,2,'MouseUp',1]])assert.equal(mouseButton({button,buttons},kind),wanted);});
test('all modifier masks',()=>{for(let n=0;n<8;n++)assert.equal(shiftMask({shiftKey:n&1,ctrlKey:n&2,altKey:n&4}),n);});
function vm(){const machine=new VirtualMachine({name:'Input',startup:'Sub Main',modules:[]});machine.setState('running');return machine;}
test('queued motion retains latest position and one completion',async()=>{const v=vm(),owner={},key={},seen=[];v.processing=true;const first=v.enqueueInput(owner,key,()=>seen.push(1),{coalesce:true});for(let i=2;i<=1000;i++)assert.equal(v.enqueueInput(owner,key,()=>seen.push(i),{coalesce:true}),first);assert.equal(v.eventQueue.length,1);v.processing=false;await v.processEvents();await first;assert.deepEqual(seen,[1000]);v.stop();});
test('motion cannot replace down/up or another control array element',async()=>{const v=vm(),owner={},first={},second={},seen=[];v.processing=true;v.enqueueInput(owner,null,()=>seen.push('down'));v.enqueueInput(owner,first,()=>seen.push('old'),{coalesce:true});v.enqueueInput(owner,second,()=>seen.push('second'),{coalesce:true});v.enqueueInput(owner,first,()=>seen.push('latest'),{coalesce:true});v.enqueueInput(owner,null,()=>seen.push('up'));assert.equal(v.eventQueue.length,4);v.processing=false;await v.processEvents();assert.deepEqual(seen,['down','latest','second','up']);v.stop();});
test('different form instances retain independent pending motion',async()=>{const v=vm(),key={},seen=[];v.processing=true;v.enqueueInput({},key,()=>seen.push(1),{coalesce:true});v.enqueueInput({},key,()=>seen.push(2),{coalesce:true});assert.equal(v.eventQueue.length,2);v.processing=false;await v.processEvents();assert.deepEqual(seen,[1,2]);v.stop();});
test('input action is serialized with asynchronous procedure calls',async()=>{const v=vm(),seen=[];const a=v.enqueueInput({},null,async()=>{seen.push('preview');await new Promise(r=>setTimeout(r,5));seen.push('control');});const b=v.enqueueInput({},null,()=>seen.push('next'));await Promise.all([a,b]);assert.deepEqual(seen,['preview','control','next']);v.stop();});
for(const state of ['paused','stopped','error'])test(state+' drains input promises without delivering stale input',async()=>{const v=vm();v.processing=true;let ran=false;const pending=v.enqueueInput({},null,()=>ran=true);v.setState(state);await pending;assert.equal(v.eventQueue.length,0);v.setState('running');v.processing=false;await v.processEvents();assert.equal(ran,false);v.stop();});
for(const state of ['ready','paused','stopped','error'])test('new input is ignored in '+state,async()=>{const v=vm();v.setState(state);await v.enqueueInput({},null,()=>assert.fail('invalid input'));assert.equal(v.eventQueue.length,0);v.stop();});
test('disabled/unloaded target is rechecked at delivery',async()=>{const v=vm();v.processing=true;let valid=true;const pending=v.enqueueInput({},null,()=>assert.fail('stale control'),{valid:()=>valid});valid=false;v.processing=false;await v.processEvents();await pending;v.stop();});
test('pausing input does not discard pending timers',()=>{const v=vm();v.processing=true;const timer={key:'Timer_Timer',resolve:()=>{}};v.eventQueue.push(timer);v.enqueueInput({},null,()=>{});v.setState('paused');assert.deepEqual(v.eventQueue,[timer]);v.stop();});
test('input respects the event queue bound',async()=>{const v=vm();v.processing=true;for(let i=0;i<1000;i++)v.enqueueInput({},null,()=>{});await v.enqueueInput({},null,()=>assert.fail('over limit'));assert.equal(v.eventQueue.length,1000);v.stop();});
function surface(){return {offsetWidth:204,offsetHeight:104,clientWidth:200,clientHeight:100,clientLeft:2,clientTop:2,scrollLeft:0,scrollTop:0,getBoundingClientRect:()=>({left:10,top:20,width:408,height:208})};}
test('all standard mouse ScaleModes account for client borders and CSS scaling',()=>{for(const [mode,factor]of [[1,15],[2,.75],[3,1],[4,8],[5,1/96],[6,25.4/96],[7,2.54/96]]){const control={type:'Form',props:{ScaleMode:mode},content:surface()};assert.deepEqual(mouseCoordinates(control,{clientX:34,clientY:64}),[10*factor,20*factor]);}});
test('custom/reversed scale retains fractional coordinates and origins',()=>{const control={type:'Form',props:{ScaleMode:0,ScaleWidth:100,ScaleHeight:-50,ScaleLeft:25,ScaleTop:100},content:surface()};assert.deepEqual(mouseCoordinates(control,{clientX:34,clientY:64}),[30,90]);});
