import test from 'node:test';
import assert from 'node:assert/strict';
import {arrangeMDIRects} from '../src/runtime/mdi.js';
import {compileProject} from '../src/language/compiler.js';
import {VirtualMachine} from '../src/runtime/vm.js';
import {createForm,newProject} from '../src/project/model.js';
import {parseFRM,serializeFRM} from '../src/project/formats.js';
function form(name,code='',parent=false){const m=createForm(name);m.form.type=parent?'MDIForm':'Form';m.form.properties.MDIChild=parent?0:-1;m.code=code;return m;}
const main=code=>({name:'MainModule',kind:'module',code:'Sub Main()\n'+code+'\nEnd Sub'});
async function run(modules){const output=[],forms=[],controller={parent:null};const host={print:s=>output.push(s),createForm:async(model,instance)=>{const f={type:model.type,instance,controlMap:new Map(),shown:false,Show(){this.shown=true;},Hide(){this.shown=false;},suspendTimers(){}};if(model.type==='MDIForm')controller.parent=f;else if(Number(model.properties.MDIChild)){f.mdiChild=true;f.mdiController=controller;}forms.push(f);return f;}};const vm=new VirtualMachine({name:'MDILab',startup:'Sub Main',modules},host);await vm.start();return {vm,forms,output};}
test('MDI tile geometry covers every pixel without rounding gaps',()=>{for(const mode of [1,2]){const rects=arrangeMDIRects(7,901,503,mode);assert.equal(rects.length,7);if(mode===1){assert.equal(rects.reduce((n,r)=>n+r.height,0),503);assert.equal(rects.at(-1).top+rects.at(-1).height,503);}else{assert.equal(rects.reduce((n,r)=>n+r.width,0),901);assert.equal(rects.at(-1).left+rects.at(-1).width,901);}}});
test('MDI cascade cycles positions and icon geometry stays nonnegative',()=>{const cascade=arrangeMDIRects(25,800,600,0),icons=arrangeMDIRects(10,160,200,3);assert.equal(cascade[0].left,cascade[10].left);assert.ok(icons.every(r=>r.left>=0&&r.top>=0));assert.deepEqual(arrangeMDIRects(0,800,600),[]);});
test('MDI geometry rejects invalid modes and item counts',()=>{for(const n of [-1,1001,1.5])assert.throws(()=>arrangeMDIRects(n,900,500));assert.throws(()=>arrangeMDIRects(3,900,500,4));});
test('compiler rejects multiple MDI parents or orphan child forms',()=>{let p=compileProject({modules:[form('Parent1','',true),form('Parent2','',true)]});assert.equal(p.diagnostics[0].number,360);p=compileProject({modules:[form('Child')]});assert.equal(p.diagnostics[0].number,366);});
test('native FRM interchange preserves MDI form type and MDIChild property',()=>{for(const parent of [false,true]){const m=form(parent?'Host':'Child','',parent),out=parseFRM(serializeFRM(m),m.name+'.frm').module;assert.equal(out.form.type,m.form.type);assert.equal(out.form.properties.MDIChild,parent?0:-1);}});
test('MDIForm initialization/load use the native event prefix',async()=>{const parent=form('Host','Private Sub MDIForm_Initialize()\nDebug.Print "init"\nEnd Sub\nPrivate Sub MDIForm_Load()\nDebug.Print "load"\nEnd Sub',true);assert.deepEqual((await run([main('Host.Show'),parent])).output,['init','load']);});
test('showing an MDI child first shows its parent once',async()=>{const parent=form('Host','Private Sub MDIForm_Load()\nDebug.Print "parent"\nEnd Sub',true),child=form('Child','Private Sub Form_Load()\nDebug.Print "child"\nEnd Sub');const result=await run([main('Child.Show'),child,parent]);assert.deepEqual(result.output,['parent','child']);assert.ok(result.forms.every(f=>f.shown));});
test('parent load showing children does not recursively reload the MDI parent',async()=>{const parent=form('Host','Private Sub MDIForm_Load()\nDebug.Print "parent"\nChild.Show\nEnd Sub',true),child=form('Child','Private Sub Form_Load()\nDebug.Print "child"\nEnd Sub');assert.deepEqual((await run([main('Host.Show'),parent,child])).output,['parent','child']);});
test('unloading MDI parent dispatches query modes before closing all children',async()=>{const parent=form('Host','Private Sub MDIForm_QueryUnload(Cancel As Integer, UnloadMode As Integer)\nDebug.Print "parent", UnloadMode\nEnd Sub',true),child=form('Child','Private Sub Form_QueryUnload(Cancel As Integer, UnloadMode As Integer)\nDebug.Print "child", UnloadMode\nEnd Sub');const result=await run([main('Host.Show\nChild.Show\nUnload Host\nDebug.Print Forms.Count'),parent,child]);assert.deepEqual(result.output,['parent 1','child 4','0']);assert.ok(result.forms.every(f=>!f.shown));});
test('one child cancellation preserves all loaded MDI windows',async()=>{const result=await run([main('Host.Show\nChild.Show\nOther.Show\nUnload Host\nDebug.Print Forms.Count'),form('Host','',true),form('Child','Private Sub Form_QueryUnload(Cancel As Integer, UnloadMode As Integer)\nCancel = True\nEnd Sub'),form('Other')]);assert.deepEqual(result.output,['3']);assert.ok(result.forms.every(f=>f.shown));});
test('Unload cancellation does not partially hide a sibling window',async()=>{const result=await run([main('Host.Show\nChild.Show\nOther.Show\nUnload Host\nDebug.Print Forms.Count'),form('Host','',true),form('Child'),form('Other','Private Sub Form_Unload(Cancel As Integer)\nCancel = True\nEnd Sub')]);assert.deepEqual(result.output,['3']);assert.ok(result.forms.every(f=>f.shown));});
test('MDI parent and child modal requests fail before load side effects',async()=>{for(const target of ['Host','Child'])await assert.rejects(()=>run([main(target+'.Show vbModal'),form('Host','',true),form('Child')]),e=>e.number===401);});
test('New MDIForm is rejected while New child instances work',async()=>{await assert.rejects(()=>run([main('Dim a As Object\nSet a = New Host'),form('Host','',true)]),e=>e.number===360);const result=await run([main('Dim a As New Child, b As New Child\na.Show\nb.Show\nDebug.Print Forms.Count'),form('Host','',true),form('Child')]);assert.deepEqual(result.output,['3']);});
