import test from 'node:test';
import assert from 'node:assert/strict';
import {VBCurrency, NOTHING, binary, unary, coerce, roundRatio} from '../src/runtime/values.js';
import {compileProject} from '../src/language/compiler.js';
import {preprocess} from '../src/language/conditional.js';
import {VirtualMachine} from '../src/runtime/vm.js';
async function run(body, extras=[], settings={}) {
  const p=compileProject({name:'Parity',startup:'Sub Main',settings,modules:[{name:'M',kind:'module',code:body},...extras]});
  assert.deepEqual(p.diagnostics,[]);const output=[];const vm=new VirtualMachine(p,{print:s=>output.push(s)});await vm.start();return {vm,output};
}
const main=body=>`Option Explicit\nSub Main()\n${body}\nEnd Sub`;
for(const value of ['922337203685477.5807','-922337203685477.5808','0.0001','-0.0001','123456789012345.1234','0','1.23'])test('Currency exact decimal '+value,()=>assert.equal(new VBCurrency(value).toString(),value));
for(const [input,expected] of [['1.23445','1.2344'],['1.23455','1.2346'],['-1.23445','-1.2344'],['-1.23455','-1.2346'],['1.23456e2','123.456'],['.00005','0'],['.00015','0.0002']])test('Currency decimal rounding '+input,()=>assert.equal(new VBCurrency(input).toString(),expected));
test('Currency rejects both range overflows',()=>{for(const n of ['922337203685477.5808','-922337203685477.5809'])assert.throws(()=>new VBCurrency(n),e=>e.number===6);});
test('Currency multiplication retains integer precision and ties to even',()=>{assert.equal(binary('*',new VBCurrency('12345678901234.5678'),new VBCurrency('2')).toString(),'24691357802469.1356');assert.equal(binary('*',new VBCurrency('.0001'),new VBCurrency('.5')).toString(),'0');assert.equal(binary('*',new VBCurrency('.0003'),new VBCurrency('.5')).toString(),'.0002'.replace(/^\./,'0.'));});
test('Currency comparisons distinguish adjacent units at the upper range',()=>{const a=new VBCurrency('922337203685477.5806'),b=new VBCurrency('922337203685477.5807');assert.equal(binary('<',a,b),-1);assert.equal(binary('=',a,b),0);});
test('Currency unary and checked arithmetic do not silently overflow',()=>{assert.equal(unary('-',new VBCurrency('1.0001')).toString(),'-1.0001');assert.throws(()=>unary('-',new VBCurrency('-922337203685477.5808')),e=>e.number===6);assert.throws(()=>binary('+',new VBCurrency('922337203685477.5807'),new VBCurrency('.0001')),e=>e.number===6);});
test('Currency literals and library functions execute without IEEE conversion',async()=>assert.deepEqual((await run(main('Dim c As Currency\nc = 922337203685477.5807@\nDebug.Print c\nDebug.Print -922337203685477.5808@\nDebug.Print CCur("123456789012345.1234")\nDebug.Print Abs(-1.2345@), Round(1.235@, 2)'))).output,['922337203685477.5807','-922337203685477.5808','123456789012345.1234','1.2345 1.24']));
test('Null concatenation and implication have explicit three-valued results',()=>{assert.equal(binary('&',null,null),null);assert.equal(binary('imp',0,null),-1);assert.equal(binary('imp',null,-1),-1);assert.equal(binary('and',null,0),0);assert.equal(binary('or',null,-1),-1);});
test('Nothing is distinct from Null, Empty, and non-object operands',async()=>{assert.deepEqual((await run(main('Dim o As Object\nDebug.Print IsNull(o), IsEmpty(o), IsObject(o), TypeName(o), VarType(o)\nDebug.Print o Is Nothing\nDebug.Print IsNull(Null), IsEmpty(Empty)'))).output,['False False True Nothing 9','True','True True']);assert.throws(()=>binary('is',null,NOTHING),e=>e.number===424);assert.throws(()=>coerce(null,'Object'),e=>e.number===94);});
test('As New is lazy, aliases retain objects and Nothing triggers recreation',async()=>{const cls={name:'Thing',kind:'class',code:'Public Value As Long\nPrivate Sub Class_Initialize()\nDebug.Print "created"\nValue = 7\nEnd Sub'};assert.deepEqual((await run(main('Dim t As New Thing, old As Thing\nDebug.Print "before"\nDebug.Print t.Value\nSet old = t\nSet t = Nothing\nDebug.Print old.Value\nDebug.Print t.Value\nDebug.Print old Is t'),[cls])).output,['before','created','7','7','created','7','False']);});
test('fixed strings pad and truncate at assignments',async()=>assert.deepEqual((await run(main('Dim s As String * 4\nDebug.Print Len(s)\ns = "ab"\nDebug.Print "[" & s & "]"\ns = "abcdef"\nDebug.Print s'))).output,['4','[ab  ]','abcd']));
test('conditional compilation skips unavailable native code and preserves lines',async()=>{const code='#Const N = 2\n#If Win32 Then\nDeclare Function Native Lib "x" () As Long\n#ElseIf N = 2 And VBWEB Then\nSub Main()\nDebug.Print "web"\nEnd Sub\n#Else\nnot valid source !\n#End If';const result=await run(code);assert.deepEqual(result.output,['web']);assert.equal(result.vm.program.modules.get('m').procedures.get('main').code[0].line,6);});
test('project conditional constants and nested dead branches',async()=>assert.deepEqual((await run('#If FEATURE Then\nSub Main()\nDebug.Print 42\nEnd Sub\n#Else\n#If InvalidCall() Then\nerror\n#End If\n#End If',[],{conditionalConstants:{FEATURE:-1}})).output,['42']));
for(const code of ['#Else','#End If','#If True Then','#If True Then\n#Else\n#Else\n#End If','#If Now() Then\n#End If'])test('conditional structure rejects '+code.replaceAll('\n',' / '),()=>assert.throws(()=>preprocess(code),e=>e.number===1002));
