/** ZIP interoperability without a runtime dependency. Writes STORE; reads STORE/DEFLATE. */
const encoder=new TextEncoder(),decoder=new TextDecoder();
const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0;}
export function crc32(bytes){let crc=0xffffffff;for(const b of bytes)crc=table[(crc^b)&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}
function unsafePath(path){return !path||/^[\\/]|^[A-Za-z]:|\0/.test(path)||path.split(/[\\/]/).includes('..');}
function concat(parts){const result=new Uint8Array(parts.reduce((s,p)=>s+p.length,0));let at=0;for(const p of parts){result.set(p,at);at+=p.length;}return result;}
function header(size){const bytes=new Uint8Array(size);return {bytes,view:new DataView(bytes.buffer)};}
export function writeZip(files){const locals=[],centrals=[],names=new Set();let offset=0;const now=new Date(),dosTime=(now.getHours()<<11)|(now.getMinutes()<<5)|(now.getSeconds()>>1),dosDate=((Math.max(1980,now.getFullYear())-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate();
  for(const [path,input]of Object.entries(files)){if(unsafePath(path))throw new Error('Unsafe ZIP path');const key=path.replace(/\\/g,'/').split('/').filter(p=>p&&p!=='.').join('/').toLowerCase();if(names.has(key))throw new Error('Duplicate ZIP entry: '+path);names.add(key);const name=encoder.encode(path),data=typeof input==='string'?encoder.encode(input):new Uint8Array(input),crc=crc32(data);const h=header(30),v=h.view;v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(10,dosTime,true);v.setUint16(12,dosDate,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);locals.push(h.bytes,name,data);
    const c=header(46),cv=c.view;cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint16(12,dosTime,true);cv.setUint16(14,dosDate,true);cv.setUint32(16,crc,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);centrals.push(c.bytes,name);offset+=h.bytes.length+name.length+data.length;
  }
  const central=concat(centrals),end=header(22),v=end.view,count=Object.keys(files).length;v.setUint32(0,0x06054b50,true);v.setUint16(8,count,true);v.setUint16(10,count,true);v.setUint32(12,central.length,true);v.setUint32(16,offset,true);return concat([...locals,central,end.bytes]);
}
export async function readZip(input,{maxExpandedBytes=50*1024*1024,maxFiles=2000}={}){const bytes=input instanceof Uint8Array?input:new Uint8Array(input),v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(v.getUint32(i,true)===0x06054b50){end=i;break;}}if(end<0)throw new Error('Invalid ZIP: end record not found');const count=v.getUint16(end+10,true);if(count>maxFiles)throw new Error('ZIP has too many files');let pos=v.getUint32(end+16,true),total=0;const files=new Map(),names=new Set();
  for(let i=0;i<count;i++){if(pos+46>bytes.length||v.getUint32(pos,true)!==0x02014b50)throw new Error('Invalid ZIP directory');const flags=v.getUint16(pos+8,true),method=v.getUint16(pos+10,true),crc=v.getUint32(pos+16,true),size=v.getUint32(pos+20,true),expanded=v.getUint32(pos+24,true),nameLen=v.getUint16(pos+28,true),extraLen=v.getUint16(pos+30,true),commentLen=v.getUint16(pos+32,true),offset=v.getUint32(pos+42,true),name=decoder.decode(bytes.subarray(pos+46,pos+46+nameLen));pos+=46+nameLen+extraLen+commentLen;if(flags&1)throw new Error('Encrypted ZIP is not supported');if(unsafePath(name))throw new Error('Unsafe path in ZIP');if(name.endsWith('/'))continue;total+=expanded;if(total>maxExpandedBytes)throw new Error('ZIP expansion limit exceeded');if(offset+30>bytes.length||v.getUint32(offset,true)!==0x04034b50)throw new Error('Invalid ZIP file header');const start=offset+30+v.getUint16(offset+26,true)+v.getUint16(offset+28,true);if(start+size>bytes.length)throw new Error('Truncated ZIP');let data=bytes.slice(start,start+size);if(method===8){if(typeof DecompressionStream==='undefined')throw new Error('This browser cannot decompress ZIP files; extract them and import the source files together.');const stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));const reader=stream.getReader(),chunks=[];let length=0;while(true){const result=await reader.read();if(result.done)break;length+=result.value.length;if(length>expanded||length>maxExpandedBytes){await reader.cancel();throw new Error('ZIP expansion exceeds declared size');}chunks.push(result.value);}data=concat(chunks);}else if(method!==0)throw new Error('Unsupported ZIP compression: '+method);if(data.length!==expanded||crc32(data)!==crc)throw new Error('ZIP checksum mismatch: '+name);const normalized=name.replace(/\\/g,'/').split('/').filter(p=>p&&p!=='.').join('/'),key=normalized.toLowerCase();if(names.has(key))throw new Error('Duplicate ZIP entry: '+name);names.add(key);files.set(normalized,data);
  }return files;
}
