import {prepareXamlEdit,readXamlDocument} from '../../xaml/documents.js';
import {normalizeProject} from '../../project/model.js';

/** Plan a project transaction without mutating live state. Cross-language edits
 * cannot overwrite implicit VB6 renames performed by the XAML designer. */
export function prepareProjectEdits(project,plans,records,{schema,runState='design',isLocked=()=>false}={}) {
  if(!['design','paused'].includes(runState))throw new Error('The project is read-only while running.');
  const targets=plans.map(plan=>{
    const record=records.get(plan.uri),module=project.modules.find(m=>m.id===record?.moduleId);
    if(!record||!module)throw new Error('Workspace edit targets an unknown project document.');
    const current=record.language==='vb6'?module.code:readXamlDocument(module,{schema}).text;
    if(current!==plan.before)throw new Error('The project changed before the workspace edit was applied.');
    if(record.language==='xaml'&&(runState!=='design'||isLocked(module.id)))throw new Error('XAML is read-only while running, paused or locked.');
    return {plan,record,module};
  });
  let next=structuredClone(project);const direct=new Set(targets.filter(t=>t.record.language==='vb6').map(t=>t.module.id));
  for(const {plan,record,module}of targets)if(record.language==='vb6')next.modules.find(m=>m.id===module.id).code=plan.after;
  for(const {plan,record,module}of targets)if(record.language==='xaml'){
    const before=next,proposal=prepareXamlEdit(next,module.id,plan.after,{schema});
    if(proposal.conflict)throw new Error('Resolve the XAML designer conflict before applying language-server edits.');
    if(proposal.result.diagnostics.some(d=>d.severity==='error'))throw new Error('Workspace edit would produce invalid XAML: '+proposal.result.diagnostics.find(d=>d.severity==='error').message);
    for(const id of direct)if(before.modules.find(m=>m.id===id).code!==proposal.project.modules.find(m=>m.id===id).code)throw new Error('This workspace edit overlaps a VB6 rename generated by the XAML designer. Apply the changes separately.');
    next=proposal.project;
  }
  return normalizeProject(next);
}
