import {uiDocument} from '../core/window-context.js';
import {keyboardTransaction} from './keyboard-transaction.js';
import {el} from '../core/core.js';
import {icon,showMenu,modal,promptDialog,alertDialog,tabbedPages} from './ui.js';
import {CommandBarLayout,COMMANDS} from './command-bar-model.js';

export class CommandBars {
  constructor(ide){
    this.ide=ide;this.model=new CommandBarLayout();this.views=new Map();this.catalog=new Map(COMMANDS.map(c=>[c.id,c]));this.hosts=new Map();
    const top=el('div',{class:'command-bars-host command-bars-top','aria-label':'Top toolbars'});ide.toolbar.replaceWith(top);this.hosts.set('top',top);
    const work=el('div',{class:'command-workarea'});ide.workspace.replaceWith(work);work.append(ide.workspace);this.workarea=work;
    for(const edge of ['left','right']){const host=el('div',{class:'command-bars-host command-bars-'+edge,'aria-label':edge+' toolbars'});this.hosts.set(edge,host);edge==='left'?work.prepend(host):work.append(host);}
    const bottom=el('div',{class:'command-bars-host command-bars-bottom','aria-label':'Bottom toolbars'});ide.statusbar.before(bottom);this.hosts.set('bottom',bottom);
    ide.root.classList.add('command-bar-shell');
    for(const host of this.hosts.values())host.addEventListener('contextmenu',e=>{e.preventDefault();this.menu(e.clientX,e.clientY);});
    this.observer=new ResizeObserver(()=>this.constrain());this.observer.observe(ide.root);this.render();
  }
  snapshot(){return this.model.snapshot();}
  restore(value){this.model.restore(value);this.render();}
  save(){this.ide.autosave();}
  show(id,visible){const b=this.model.get(id);if(!b)return;b.visible=visible===undefined?!b.visible:visible;this.render();this.save();}
  dock(id,edge){this.browserWindows?.attach('toolbar:'+id,'layout');const b=this.model.get(id);if(!b||!['top','bottom','left','right','float'].includes(edge))return;b.dock=edge;b.visible=true;this.render();this.save();}
  render(){
    const focused=uiDocument().activeElement,focusBar=focused?.closest('[data-command-bar]')?.dataset.commandBar,focusCommand=focused?.dataset.command;
    for(const b of this.model.bars){let view=this.views.get(b.id);if(!view){view=el('div',{class:'command-bar toolbar','data-command-bar':b.id,role:'toolbar'});this.views.set(b.id,view);}view.setAttribute('aria-label',b.name+' toolbar');view.hidden=!b.visible;view.dataset.dock=b.dock;
      if(!b.visible)this.browserWindows?.attach('toolbar:'+b.id,'hidden');const parent=this.browserWindows?.mount('toolbar:'+b.id)||(b.dock==='float'?this.ide.root:this.hosts.get(b.dock));if(view.parentNode!==parent)parent.append(view);
      view.classList.toggle('command-bar-floating',b.dock==='float');view.classList.toggle('command-bar-vertical',['left','right'].includes(b.dock));view.classList.toggle('command-bar-large',!!this.ide.appearance.largeToolbarIcons);
      const grip=el('span',{class:'toolbar-grip',tabindex:0,role:'button','aria-label':'Move '+b.name+' toolbar',title:b.name+' toolbar — drag or press Shift+F10'});grip.addEventListener('pointerdown',e=>this.drag(b.id,e));grip.addEventListener('dblclick',()=>this.dock(b.id,b.dock==='float'?'top':'float'));grip.addEventListener('keydown',e=>{if((e.shiftKey&&e.key==='F10')||e.key==='ContextMenu'){e.preventDefault();const r=grip.getBoundingClientRect();this.menu(r.left,r.bottom,b.id);}else if(e.ctrlKey&&e.key==='Enter'){e.preventDefault();this.dock(b.id,b.dock==='float'?'top':'float');}else if(e.key==='Enter'&&b.dock==='float'){e.preventDefault();this.keyboardMove(b.id);}});
      const nodes=[grip];if(b.dock==='float'){nodes.push(el('strong',{class:'command-floating-name'},b.name),el('button',{class:'command-floating-close','aria-label':'Hide '+b.name+' toolbar',title:'Hide toolbar',onclick:()=>this.show(b.id,false)},icon('close',12)));}
      b.items.forEach((id,index)=>{if(id==='|'){nodes.push(el('span',{class:'tool-separator','data-bar-index':index}));return;}const c=this.catalog.get(id),button=el('button',{class:'tool-button','data-command':id,'data-bar-index':index,title:c.label,'aria-label':c.label,onclick:e=>{if(e.altKey){this.itemMenu(b.id,index,e.clientX,e.clientY);return;}this.ide.command(id);}},icon(c.icon));button.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();this.itemMenu(b.id,index,e.clientX,e.clientY);});button.addEventListener('keydown',e=>{if(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();this.model.move(b.id,index,index+(e.key==='ArrowRight'?1:-1));this.render();this.save();}else if(e.altKey&&e.key==='Delete'){e.preventDefault();b.items.splice(index,1);this.render();this.save();}});nodes.push(button);});
      if(b.id==='standard'&&!['left','right'].includes(b.dock))nodes.push(el('span',{class:'toolbar-spacer'}),this.ide.zoomSelect);
      view.replaceChildren(...nodes);view.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();this.menu(e.clientX,e.clientY,b.id);};view.onkeydown=e=>this.navigate(view,e);
      if(b.dock==='float')this.place(b,view);else{view.style.left='';view.style.top='';view.style.width='';}
    }
    for(const [id,view]of this.views)if(!this.model.get(id)){this.browserWindows?.attach('toolbar:'+id,'remove');this.browserWindows?.pending.delete('toolbar:'+id);view.remove();this.views.delete(id);}
    for(const [edge,host]of this.hosts)host.hidden=!this.model.bars.some(b=>b.visible&&b.dock===edge&&!this.browserWindows?.has('toolbar:'+b.id));
    this.ide.toolbar=this.views.get('standard');this.update();
    if(focusBar){const view=this.views.get(focusBar);if(view&&!view.hidden){const candidate=focused.isConnected?focused:focusCommand?[...view.querySelectorAll('[data-command]')].find(n=>n.dataset.command===focusCommand):view.querySelector('.toolbar-grip');candidate?.focus({preventScroll:true});}}
  }
  update(){
    const ide=this.ide;if(!ide.project)return;const enabled=new Map();for(const category of ['File','Edit','View','Project','Format','Debug','Run','Tools']){const visit=items=>{for(const item of items||[]){if(item?.id)enabled.set(item.id,item.enabled!==false);if(item?.items)visit(item.items);}};visit(ide.menu(category));}
    for(const view of this.views.values())for(const button of view.querySelectorAll('[data-command]')){const id=button.dataset.command;button.disabled=enabled.get(id)===false;if(id.startsWith('align:'))button.disabled=ide.runState!=='design'||!ide.activeModule?.form;}
  }
  navigate(view,e){if(e.defaultPrevented||e.altKey||e.ctrlKey)return;const vertical=view.classList.contains('command-bar-vertical');if(!['Home','End',vertical?'ArrowUp':'ArrowLeft',vertical?'ArrowDown':'ArrowRight'].includes(e.key))return;e.preventDefault();const controls=[...view.querySelectorAll('button:not([disabled]),select,.toolbar-grip')].filter(n=>!n.hidden),index=controls.indexOf(e.target);const next=e.key==='Home'?0:e.key==='End'?controls.length-1:(index+(['ArrowDown','ArrowRight'].includes(e.key)?1:-1)+controls.length)%controls.length;controls[next]?.focus();}
  menu(x,y,id){const b=this.model.get(id);showMenu([...this.model.bars.map(bar=>({label:bar.name,checked:bar.visible,action:()=>this.show(bar.id)})),null,...(b?[{label:this.browserWindows?.has('toolbar:'+b.id)?'Return to IDE':'Float in Browser Window',action:()=>this.browserWindows?.has('toolbar:'+b.id)?this.browserWindows.attach('toolbar:'+b.id):this.detach?.(b.id)},{label:'Dock to',items:['top','bottom','left','right','float'].map(edge=>({label:edge[0].toUpperCase()+edge.slice(1),checked:b.dock===edge,action:()=>this.dock(b.id,edge)}))},{label:'Move',enabled:b.dock==='float',action:()=>this.keyboardMove(b.id)},{label:'Reset '+b.name,action:()=>{this.model.reset(b.id);this.render();this.save();}},null]:[]),{label:'Customize…',action:()=>this.customize()}],x,y);}
  itemMenu(id,index,x,y){const b=this.model.get(id);showMenu([{label:'Move Left / Up',enabled:index>0,action:()=>{this.model.move(id,index,index-1);this.render();this.save();}},{label:'Move Right / Down',enabled:index<b.items.length-1,action:()=>{this.model.move(id,index,index+1);this.render();this.save();}},{label:'Begin a Group',checked:b.items[index-1]==='|',action:()=>{if(b.items[index-1]==='|')b.items.splice(index-1,1);else this.model.insert(id,'|',index);this.render();this.save();}},{label:'Remove Button',action:()=>{b.items.splice(index,1);this.render();this.save();}},null,{label:'Customize…',action:()=>this.customize(id)}],x,y);}
  place(b,view){if(this.browserWindows?.has('toolbar:'+b.id))return;const width=view.offsetWidth||300,height=view.offsetHeight||60;b.x=Math.max(0,Math.min(Math.max(0,innerWidth-width),b.x));b.y=Math.max(0,Math.min(Math.max(0,innerHeight-height),b.y));Object.assign(view.style,{left:b.x+'px',top:b.y+'px'});}
  constrain(){for(const b of this.model.bars)if(b.dock==='float'&&b.visible)this.place(b,this.views.get(b.id));}
  drag(id,event){if(this.browserWindows?.has('toolbar:'+id))return;if(event.button!==0)return;const b=this.model.get(id),before=this.snapshot(),view=this.views.get(id),r=view.getBoundingClientRect(),sx=event.clientX,sy=event.clientY;let moved=false,target;this.ide.docking.track(event,e=>{if(!moved&&Math.hypot(e.clientX-sx,e.clientY-sy)<5)return;if(!moved){b.dock='float';moved=true;this.render();}b.x=r.left+e.clientX-sx;b.y=r.top+e.clientY-sy;this.place(b,this.views.get(id));target=null;if(!e.ctrlKey){if(e.clientY<85)target='top';else if(e.clientY>innerHeight-45)target='bottom';else if(e.clientX<35)target='left';else if(e.clientX>innerWidth-35)target='right';}for(const [edge,host]of this.hosts)host.classList.toggle('command-drop-target',edge===target);},()=>{for(const host of this.hosts.values())host.classList.remove('command-drop-target');if(moved){if(target)b.dock=target;this.render();this.save();}},()=>{for(const host of this.hosts.values())host.classList.remove('command-drop-target');if(moved)this.restore(before);});}
  keyboardMove(id){const b=this.model.get(id);if(b?.dock!=='float')return;const old=[b.x,b.y];this.views.get(id).querySelector('.toolbar-grip').focus();this.ide.status('Move toolbar: arrow keys; Enter to accept; Escape to cancel.');
    const finish=()=>{if(this.views.has(id))this.place(b,this.views.get(id));this.save();this.ide.status('Ready');};
    keyboardTransaction(this,{step:(dx,dy)=>{b.x+=dx;b.y+=dy;this.place(b,this.views.get(id));},commit:finish,cancel:()=>{[b.x,b.y]=old;finish();}});
  }
  async customize(initial='standard'){
    const working=new CommandBarLayout();working.restore(this.snapshot());const barsPage=el('div',{class:'customize-toolbars'}),commandsPage=el('div',{class:'customize-commands'}),list=el('select',{size:9,'aria-label':'Toolbars',style:{width:'100%'}}),visible=el('input',{type:'checkbox','aria-label':'Show selected toolbar'}),dock=el('select',{'aria-label':'Toolbar docking'},...['top','bottom','left','right','float'].map(value=>el('option',{value},value))),large=el('input',{type:'checkbox',checked:!!this.ide.appearance.largeToolbarIcons,'aria-label':'Large toolbar buttons'});
    const target=el('select',{'aria-label':'Customize toolbar'}),category=el('select',{'aria-label':'Command category'},...['All',...new Set(COMMANDS.map(c=>c.category))].map(name=>el('option',{value:name},name))),available=el('select',{size:12,'aria-label':'Available commands'}),items=el('select',{size:12,'aria-label':'Toolbar commands'});
    const selected=()=>working.get(target.value||list.value)||working.bars[0];const renderCommands=()=>{const b=selected(),previous=items.selectedIndex;items.replaceChildren(...b.items.map((id,index)=>el('option',{value:index},id==='|'?'— Separator —':this.catalog.get(id).label)));items.selectedIndex=Math.max(0,Math.min(previous,items.options.length-1));};
    const renderBars=(id=list.value||initial)=>{list.replaceChildren(...working.bars.map(b=>el('option',{value:b.id},(b.visible?'☑ ':'☐ ')+b.name)));target.replaceChildren(...working.bars.map(b=>el('option',{value:b.id},b.name)));list.value=id;target.value=id;const b=working.get(id)||working.bars[0];list.value=b.id;target.value=b.id;visible.checked=b.visible;dock.value=b.dock;renderCommands();};
    const filter=()=>available.replaceChildren(...COMMANDS.filter(c=>category.value==='All'||c.category===category.value).map(c=>el('option',{value:c.id},c.label)));filter();
    list.onchange=()=>{target.value=list.value;const b=selected();visible.checked=b.visible;dock.value=b.dock;renderCommands();};target.onchange=()=>{list.value=target.value;list.onchange();};category.onchange=filter;visible.onchange=()=>{working.get(list.value).visible=visible.checked;const id=list.value;renderBars(id);};dock.onchange=()=>working.get(list.value).dock=dock.value;
    const action=(label,callback)=>el('button',{type:'button',onclick:async()=>{try{await callback();}catch(error){await alertDialog(error.message,'Customize');}}},label);
    barsPage.append(el('div',{class:'customize-main'},list,el('div',{class:'customize-buttons'},action('New…',async()=>{const name=await promptDialog('New Toolbar','Toolbar name:','');if(name!==null)renderBars(working.create(name).id);}),action('Rename…',async()=>{const b=working.get(list.value);if(!b.custom)throw new Error('Only custom toolbars can be renamed.');const name=await promptDialog('Rename Toolbar','Toolbar name:',b.name);if(name!==null){working.rename(b.id,name);renderBars(b.id);}}),action('Delete',()=>{working.remove(list.value);renderBars(working.bars[0].id);}),action('Reset',()=>{working.reset(list.value);renderBars(list.value);}))),el('label',{},visible,' Show selected toolbar'),el('label',{},'Docking: ',dock),el('label',{},large,' Large buttons'));
    commandsPage.append(el('div',{class:'customize-command-selectors'},el('label',{},'Categories: ',category),el('label',{},'Toolbar: ',target)),el('div',{class:'customize-command-columns'},available,el('div',{class:'customize-buttons'},action('Add →',()=>{if(available.value){working.insert(selected().id,available.value,items.selectedIndex<0?selected().items.length:items.selectedIndex+1);renderCommands();}}),action('Separator →',()=>{working.insert(selected().id,'|',items.selectedIndex<0?selected().items.length:items.selectedIndex+1);renderCommands();}),action('Remove',()=>{if(items.selectedIndex>=0){selected().items.splice(items.selectedIndex,1);renderCommands();}}),action('Move Up',()=>{const i=items.selectedIndex;working.move(selected().id,i,i-1);renderCommands();items.selectedIndex=Math.max(0,i-1);}),action('Move Down',()=>{const i=items.selectedIndex;working.move(selected().id,i,i+1);renderCommands();items.selectedIndex=Math.min(selected().items.length-1,i+1);})),items),el('p',{},'Right-click a toolbar button to move, group or remove it. Alt+Left/Right reorders a focused button; Alt+Delete removes it.'));
    renderBars(initial);const accepted=await modal('Customize',{width:650,content:tabbedPages([{id:'bars',label:'Toolbars',node:barsPage},{id:'commands',label:'Commands',node:commandsPage}],{label:'Customization pages'}),buttons:[{label:'OK',value:true,primary:true},{label:'Cancel',value:false}]});if(accepted){this.model=working;this.ide.appearance.largeToolbarIcons=large.checked;this.render();this.save();}
  }
}
export function installCommandBars(ide){const bars=ide.commandBars=new CommandBars(ide),menu=ide.menu.bind(ide),command=ide.command.bind(ide),snapshot=ide.layoutSnapshot.bind(ide),restore=ide.restoreLayout.bind(ide),update=ide.updateCommandState.bind(ide),appearance=ide.applyAppearance.bind(ide);ide.menu=name=>{const items=menu(name);if(name==='View')items.push(null,{label:'Toolbars',items:[...bars.model.bars.map(b=>({label:b.name,checked:b.visible,action:()=>bars.show(b.id)})),null,{id:'customizeToolbars',label:'Customize…'}]});if(name==='Tools')items.push(null,{id:'customizeToolbars',label:'Customize…'});return items;};ide.command=(id,...args)=>id==='customizeToolbars'?bars.customize():command(id,...args);ide.layoutSnapshot=()=>({...snapshot(),commandBars:bars.snapshot()});ide.restoreLayout=layout=>{restore(layout);if(layout?.commandBars)try{bars.restore(layout.commandBars);}catch(error){ide.status('Saved toolbar layout ignored: '+error.message);}};ide.updateCommandState=()=>{update();bars.update();};ide.applyAppearance=()=>{appearance();for(const view of bars.views.values())view.classList.toggle('command-bar-large',!!ide.appearance.largeToolbarIcons);};return bars;}
