import {DesignImmediateSession} from './design-immediate.js';
import {hasUIDialog} from '../core/window-context.js';
import {el,lower} from '../core/core.js';
import {findModule,newId} from '../project/model.js';
import {procedures} from '../editor/language-service.js';
import {wordAt} from '../editor/intelligence.js';
import {modal,promptDialog,alertDialog,showMenu} from './ui.js';

const WINDOWS=[['immediate','Immediate'],['locals','Locals'],['watch','Watch'],['callStack','Call Stack'],['breakpoints','Breakpoints'],['errors','Errors'],['output','Output'],['evaluation','Evaluate Expression']];
/** Fixed-height, keyboard-operable storage tree. Expansion is explicit and
 * bounded; values are textContent, never HTML, and edits use the typed VM API. */
export class DebugValueTree {
 constructor(label,{inspect,edit}={}){this.rows=[];this.expanded=new Map();this.selected=0;this.inspect=inspect;this.edit=edit;this.serial=0;
  this.root=el('div',{class:'debug-value-tree',role:'treegrid',tabindex:0,'aria-label':label,'aria-colcount':3});this.header=el('div',{class:'debug-value-header',role:'row'},...['Expression','Value','Type'].map(s=>el('span',{role:'columnheader'},s)));this.scroller=el('div',{class:'debug-value-scroll'});this.spacer=el('div',{class:'debug-value-spacer'});this.layer=el('div',{class:'debug-value-layer'});this.scroller.append(this.spacer,this.layer);this.root.append(this.header,this.scroller);this.scroller.addEventListener('scroll',()=>this.paint());this.observer=new ResizeObserver(()=>this.paint());this.observer.observe(this.scroller);
  this.root.addEventListener('keydown',e=>{const count=this.flat?.length||0,row=this.flat?.[this.selected];if(['ArrowDown','ArrowUp','Home','End','PageDown','PageUp'].includes(e.key)){e.preventDefault();const page=Math.max(1,Math.floor(this.scroller.clientHeight/19)-1),index=e.key==='Home'?0:e.key==='End'?count-1:this.selected+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:e.key==='PageDown'?page:-page);this.select(index);}else if(e.key==='ArrowRight'&&row?.expandable){e.preventDefault();this.expand(row);}else if(e.key==='ArrowLeft'&&row){e.preventDefault();if(this.expanded.has(row.expression)){this.expanded.delete(row.expression);this.rebuild();}else if(row.parent){this.select(this.flat.findIndex(r=>r.expression===row.parent));}}else if(['Enter','F2'].includes(e.key)&&row){e.preventDefault();if(row.more)this.more(row);else if(row.editable)this.edit?.(row);else if(row.expandable)this.expand(row);}else if(e.key===' '&&row?.expandable){e.preventDefault();this.toggle(row);}});
 }
 set(rows){const previous=this.flat?.[this.selected]?.expression;this.rows=rows||[];this.expanded.clear();this.serial++;this.rebuild();if(previous){const index=this.flat.findIndex(r=>r.expression===previous);if(index>=0)this.selected=index;}this.paint();}
 rebuild(){this.flat=[];const walk=(rows,depth=0,parent=null)=>{for(const row of rows){this.flat.push({...row,depth,parent});const expanded=this.expanded.get(row.expression);if(expanded){walk(expanded.children,depth+1,row.expression);if(expanded.truncated)this.flat.push({name:'Show more…',expression:row.expression+'::more',parent:row.expression,depth:depth+1,more:true,nextOffset:expanded.nextOffset,value:'',type:''});}}};walk(this.rows);this.spacer.style.height=this.flat.length*19+'px';this.root.setAttribute('aria-rowcount',String(this.flat.length+1));this.selected=Math.max(0,Math.min(this.selected,this.flat.length-1));this.paint();}
 select(index){this.selected=Math.max(0,Math.min(this.flat.length-1,index));const top=this.selected*19;if(top<this.scroller.scrollTop)this.scroller.scrollTop=top;else if(top+19>this.scroller.scrollTop+this.scroller.clientHeight)this.scroller.scrollTop=top-this.scroller.clientHeight+19;this.paint();}
 async expand(row){if(this.expanded.has(row.expression))return;const serial=this.serial;try{const result=await this.inspect?.(row.expression,0);if(serial!==this.serial||!result)return;this.expanded.set(row.expression,result);this.rebuild();}catch(error){if(serial===this.serial){this.expanded.set(row.expression,{children:[{expression:row.expression+'::error',name:error.message,value:'',type:'',editable:false}],truncated:false});this.rebuild();}}}
 async more(row){const serial=this.serial,existing=this.expanded.get(row.parent);if(!existing||existing.children.length>=2000)return;try{const result=await this.inspect(row.parent,row.nextOffset);if(serial!==this.serial||!result)return;existing.children.push(...result.children);existing.nextOffset=result.nextOffset;existing.truncated=result.truncated&&existing.children.length<2000;this.rebuild();}catch{}}
 toggle(row){if(this.expanded.has(row.expression)){this.expanded.delete(row.expression);this.rebuild();}else this.expand(row);}
 paint(){if(!this.flat)return;const start=Math.max(0,Math.floor(this.scroller.scrollTop/19)-2),end=Math.min(this.flat.length,start+Math.ceil((this.scroller.clientHeight||190)/19)+5),nodes=[];for(let i=start;i<end;i++){const row=this.flat[i],node=el('div',{class:'debug-value-row'+(i===this.selected?' selected':''),role:'row',id:'debug-row-'+this.labelId+'-'+i,'aria-rowindex':i+2,'aria-level':row.depth+1,'aria-selected':String(i===this.selected),'data-expression':row.expression,style:{top:i*19+'px'}},el('span',{class:'debug-expression',role:'gridcell',style:{paddingLeft:(row.depth*13+3)+'px'}},row.expandable?el('button',{class:'debug-expand',tabindex:-1,'aria-label':(this.expanded.has(row.expression)?'Collapse ':'Expand ')+row.name,onclick:e=>{e.stopPropagation();this.select(i);this.toggle(row);}},this.expanded.has(row.expression)?'−':'+'):el('span',{class:'debug-expand-spacer'}),el('span',{},row.name||row.expression)),el('span',{role:'gridcell',title:row.value},row.value),el('span',{role:'gridcell'},row.type));if(row.expandable)node.setAttribute('aria-expanded',String(this.expanded.has(row.expression)));node.addEventListener('click',()=>{this.select(i);this.root.focus();if(row.more)this.more(row);});node.addEventListener('dblclick',()=>{if(row.more)this.more(row);else if(row.editable)this.edit?.(row);else if(row.expandable)this.toggle(row);});node.addEventListener('contextmenu',e=>{e.preventDefault();this.select(i);showMenu([{label:'Edit Value…',enabled:!!row.editable,action:()=>this.edit?.(row)},{label:'Expand / Collapse',enabled:!!row.expandable,action:()=>this.toggle(row)},{label:'Copy Expression',action:()=>navigator.clipboard?.writeText(row.expression)},{label:'Copy Value',action:()=>navigator.clipboard?.writeText(row.value||'')}],e.clientX,e.clientY);});nodes.push(node);}this.layer.replaceChildren(...nodes);if(this.selected>=start&&this.selected<end)this.root.setAttribute('aria-activedescendant','debug-row-'+this.labelId+'-'+this.selected);else this.root.removeAttribute('aria-activedescendant');}
 dispose(){this.serial++;this.observer.disconnect();}
}
let treeSequence=0;
export class DebugWorkbench {
 constructor(ide){this.ide=ide;this.views=new Map();this.frameIndex=null;this.pauseId=0;this.execution=null;this.watchDefinitions=[];this.refreshSerial=0;this.legacyRender=ide.renderDebug.bind(ide);ide.docking.unregister('debug');
  for(const [id,title]of WINDOWS){const body=el('div',{class:'debug-body'}),panel=el('section',{class:'debug-dock debug-tool-window','aria-label':title+' Window'},ide.caption(title,()=>this.hide(id)),body);ide.docking.register(id,panel,{edge:'bottom',group:'debug-windows',hidden:true,title});this.views.set(id,{id,title,panel,body,signature:''});}
  ide.debugDock=this.views.get('immediate').panel;ide.debugBody=this.views.get('immediate').body;ide.debugCaption=ide.debugDock.querySelector('.tool-caption');
  this.buildLocals();this.buildWatches();this.buildStack();this.buildEvaluation();
 }
 current(){return this.views.get(WINDOWS.find(([,title])=>title===this.ide.debugTab)?.[0]||'immediate');}
 show(name){const id=this.views.has(name)?name:WINDOWS.find(([,title])=>title===name)?.[0]||'immediate',view=this.views.get(id);this.ide.debugTab=view.title;this.ide.debugDock=view.panel;this.ide.debugBody=view.body;this.ide.debugCaption=view.panel.querySelector('.tool-caption');this.ide.root.classList.remove('hidden-debug');this.ide.docking.show(id,true);this.refresh();if(this.ide.runState==='paused'&&id==='locals')this.refreshLocals();queueMicrotask(()=>{if(id==='immediate')this.ide.immediateInput?.focus();else this.ide.docking.focus(id);});}
 hide(id){this.ide.docking.show(id,false);if([...this.views.keys()].every(key=>this.ide.docking.model.windows.get(key).hidden))this.ide.root.classList.add('hidden-debug');}
 legacy(view){const ide=this.ide,oldTab=ide.debugTab,oldBody=ide.debugBody,selection=ide.immediateInput&&ide.immediateInput.ownerDocument.activeElement===ide.immediateInput?[ide.immediateInput.selectionStart,ide.immediateInput.selectionEnd]:null;ide.debugTab=view.title;ide.debugBody=view.body;this.legacyRender();ide.debugTab=oldTab;ide.debugBody=oldBody;if(selection&&view.id==='immediate')ide.immediateInput.setSelectionRange(...selection);}
 refresh(){if(!this.ide.project)return;const ide=this.ide;for(const view of this.views.values()){
    if(view.id==='evaluation')continue;
    if(view.id==='locals'){const rows=ide.runState==='paused'?ide.locals:[],signature=JSON.stringify(rows)+':'+this.pauseId+':'+this.frameIndex;if(view.signature!==signature){view.signature=signature;this.localsTree.set(rows);this.refreshContext();}continue;}if(view.id==='watch'){this.renderWatches();continue;}if(view.id==='callStack'){this.renderStack();continue;}
    const source=view.id==='immediate'?ide.immediateOutput:view.id==='output'?ide.output:view.id==='breakpoints'?ide.breakpoints:ide.diagnostics,signature=JSON.stringify(source);if(view.signature!==signature||!view.body.children.length){view.signature=signature;this.legacy(view);}
  }}
 schedule(){if(this.scheduled)return;this.scheduled=requestAnimationFrame(()=>{this.scheduled=0;this.refresh();});}
 buildLocals(){const view=this.views.get('locals');this.context=el('select',{'aria-label':'Locals stack frame',onchange:()=>this.selectFrame(Number(this.context.value))});this.localsStatus=el('span',{class:'debug-context-status'});this.localsTree=new DebugValueTree('Local variables',{inspect:(expression,offset)=>this.inspect(expression,offset),edit:row=>this.editValue(row)});this.localsTree.labelId=++treeSequence;view.body.append(el('div',{class:'debug-context-bar'},el('label',{},'Context: ',this.context),this.localsStatus),this.localsTree.root);}
 refreshContext(){const old=this.context.value,options=this.ide.stack.map((frame,index)=>({index:frame.index??index,label:frame.module+'.'+frame.procedure})).reverse();this.context.replaceChildren(...options.map(f=>el('option',{value:f.index},f.label)));if(this.frameIndex!==null)this.context.value=String(this.frameIndex);else this.context.value=old;this.context.disabled=this.ide.runState!=='paused';this.localsStatus.textContent=this.ide.runState==='paused'?'Break mode':'Not in break mode';}
 async selectFrame(index){if(this.ide.runState!=='paused')return;this.frameIndex=index;this.refreshContext();await this.refreshLocals();this.ide.updateWatches();const frame=this.ide.stack[index],module=frame&&findModule(this.ide.project,frame.module);if(module)this.ide.openDocument(module.id,'code',frame.line);this.renderStack();}
 async refreshLocals(){if(this.ide.runState!=='paused'||!this.ide.runtimeFrame)return;const serial=++this.refreshSerial;try{const result=await this.ide.requestRuntime('debugLocals',{frameIndex:this.frameIndex});if(serial!==this.refreshSerial||this.ide.runState!=='paused')return;this.ide.locals=result.locals;this.localsTree.set(result.locals);this.pauseId=result.pauseId;this.refreshContext();}catch(error){this.localsStatus.textContent=error.message;}}
 inspect(expression,offset=0){if(this.ide.runState!=='paused')return Promise.reject(new Error('Pause the program to inspect values.'));return this.ide.requestRuntime('debugInspect',{expression,frameIndex:this.frameIndex,offset,limit:100});}
 async editValue(row){if(this.ide.runState!=='paused'||!row.editable)return;const pauseId=this.pauseId,frameIndex=this.frameIndex;const text=await promptDialog('Edit Value',row.expression+' =',row.literal??row.value);if(text===null)return;try{const result=await this.ide.requestRuntime('debugAssign',{expression:row.expression,value:text,frameIndex,pauseId});this.ide.locals=result.locals;this.localsTree.set(result.locals);this.ide.updateWatches();this.ide.status('Updated '+row.expression);}catch(error){await alertDialog(error.message,'Cannot change value');}}
 buildStack(){const view=this.views.get('callStack');this.stackBody=el('div',{class:'debug-stack-list',role:'listbox',tabindex:0,'aria-label':'Call stack frames'});view.body.append(el('div',{class:'debug-context-bar'},'Double-click a frame to inspect its local variables.'),this.stackBody);this.stackBody.addEventListener('keydown',e=>{const rows=[...this.stackBody.children],current=rows.findIndex(n=>n.classList.contains('selected'));if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?rows.length-1:Math.max(0,Math.min(rows.length-1,current+(e.key==='ArrowDown'?1:-1)));rows.forEach((r,i)=>r.classList.toggle('selected',i===next));rows[next]?.focus();}else if(e.key==='Enter'){e.preventDefault();rows[current]?.dispatchEvent(new Event('dblclick'));}});}
 renderStack(){this.stackBody.replaceChildren(...[...this.ide.stack].reverse().map((frame,reversed)=>{const index=frame.index??this.ide.stack.length-1-reversed,row=el('div',{class:'debug-stack-row'+(index===this.frameIndex?' selected':''),role:'option',tabindex:0,'aria-selected':String(index===this.frameIndex),'data-frame-index':index},el('span',{},index===this.ide.stack.length-1?'▶':''),el('span',{},frame.module+'.'+frame.procedure),el('span',{},'Line '+frame.line));row.addEventListener('dblclick',()=>this.selectFrame(index));row.addEventListener('click',()=>{for(const child of this.stackBody.children)child.classList.toggle('selected',child===row);});return row;}));}
 buildWatches(){const view=this.views.get('watch');this.watchInput=el('input',{'aria-label':'Watch expression',placeholder:'Expression'});const add=()=>{const expression=this.watchInput.value.trim();if(expression){if(!this.ide.watches.includes(expression)){this.ide.watches.push(expression);this.watchDefinitions.push({id:newId(),expression,mode:'expression',module:'',procedure:''});}this.watchInput.value='';this.ide.updateWatches();this.renderWatches();this.ide.autosave();}};this.ide.attachExpressionIntelliSense?.(this.watchInput);this.watchInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();add();}});this.watchTable=el('div',{class:'debug-watch-list'});view.body.append(el('div',{class:'watch-entry'},this.watchInput,el('button',{onclick:add},'Add'),el('button',{onclick:()=>this.watchDialog()},'Add Watch…')),this.watchTable);}
 normalizeWatches(){this.watchDefinitions=this.watchDefinitions.filter(d=>this.ide.watches.includes(d.expression));for(const expression of this.ide.watches)if(!this.watchDefinitions.some(d=>d.expression===expression))this.watchDefinitions.push({id:newId(),expression,mode:'expression',module:'',procedure:''});}
 renderWatches(){this.normalizeWatches();const rows=this.ide.watches.map(expression=>{const definition=this.watchDefinitions.find(w=>w.expression===expression),value=this.ide.watchValues.find(w=>w.expression===expression),context=[definition.module,definition.procedure].filter(Boolean).join('.')||'(All Procedures)',remove=el('button',{title:'Remove watch','aria-label':'Remove watch '+expression,onclick:()=>{this.ide.watches=this.ide.watches.filter(w=>w!==expression);this.normalizeWatches();this.ide.updateWatches();this.renderWatches();this.ide.autosave();}},'×');return {values:[expression,value?.value||'<not evaluated>',value?.type||'',context,definition.mode==='change'?'Break on Change':definition.mode==='true'?'Break When True':'Watch',remove],action:()=>this.watchDialog(definition)};});this.watchTable.replaceChildren(this.ide.debugTable(['Expression','Value','Type','Context','Watch Type',''],rows));}
 async watchDialog(existing=null,initial=''){const expression=el('input',{'aria-label':'Watch expression to add',value:existing?.expression||initial||this.selection(),style:{width:'100%'}}),module=el('select',{'aria-label':'Watch module'},el('option',{value:''},'(All Modules)'),...this.ide.project.modules.map(m=>el('option',{value:m.name},m.name))),procedure=el('select',{'aria-label':'Watch procedure'}),mode=el('select',{'aria-label':'Watch type'},el('option',{value:'expression'},'Watch Expression'),el('option',{value:'true'},'Break When Value Is True'),el('option',{value:'change'},'Break When Value Changes'));module.value=existing?.module||'';mode.value=existing?.mode||'expression';const updateProcedures=()=>{const m=this.ide.project.modules.find(m=>m.name===module.value);procedure.replaceChildren(el('option',{value:''},'(All Procedures)'),...(m?procedures(m.code):[]).map(p=>el('option',{value:p.name},p.name)));};module.onchange=updateProcedures;updateProcedures();procedure.value=existing?.procedure||'';const content=el('div',{class:'watch-dialog'},el('label',{},'Expression: ',expression),el('fieldset',{},el('legend',{},'Context'),el('label',{},'Module: ',module),el('label',{},'Procedure: ',procedure)),el('label',{},'Watch Type: ',mode),el('p',{},'Automatic watches read stored values and supported pure expressions. They do not call project procedures, property getters or lazy constructors.'));
  this.ide.attachExpressionIntelliSense?.(expression);await modal(existing?'Edit Watch':'Add Watch',{width:490,content,buttons:[{label:'OK',primary:true,value:true,action:()=>{const text=expression.value.trim();if(!text||text.length>4096)throw new Error('Enter an expression of at most 4096 characters.');if(this.ide.watches.some(e=>e===text&&e!==existing?.expression))throw new Error('That expression is already watched.');if(!existing&&this.ide.watches.length>=100)throw new Error('At most 100 watches are supported.');if(existing){const index=this.ide.watches.indexOf(existing.expression);this.ide.watches[index]=text;Object.assign(existing,{expression:text,module:module.value,procedure:procedure.value,mode:mode.value});}else{this.ide.watches.push(text);this.watchDefinitions.push({id:newId(),expression:text,module:module.value,procedure:procedure.value,mode:mode.value});}this.ide.updateWatches();this.show('Watch');this.ide.autosave();}},{label:'Cancel',value:false}]});}
 selection(){const editor=this.ide.editor;if(!editor?.module)return '';const {start,end}=editor.selectionBounds();return start!==end?editor.text.slice(start,end).trim():wordAt(editor.text,editor.cursor().offset).text;}
 async quickWatch(){if(this.ide.runState!=='paused')return alertDialog('Pause the program before opening Quick Watch.','Quick Watch');const expression=el('input',{'aria-label':'Quick Watch expression',value:this.selection(),style:{width:'100%'}}),context=el('div',{class:'debug-quick-context'}),status=el('div',{class:'debug-quick-status',role:'status'}),tree=new DebugValueTree('Quick Watch values',{inspect:(expr,offset)=>this.inspect(expr,offset),edit:row=>this.editValue(row)});tree.labelId=++treeSequence;tree.root.style.height='210px';let generation=0,disposed=false;
  const evaluate=async()=>{const text=expression.value.trim(),serial=++generation;if(!text){status.textContent='Enter an expression.';return false;}try{const result=await this.inspect(text);if(disposed||serial!==generation)return false;tree.set([{...result,name:text}]);tree.expanded.set(text,result);tree.rebuild();context.textContent=result.context.module+'.'+result.context.procedure;status.textContent=result.value;}catch(error){if(disposed||serial!==generation)return false;tree.set([]);status.textContent=error.message;}return false;};this.ide.attachExpressionIntelliSense?.(expression);expression.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();evaluate();}});const content=el('div',{class:'quick-watch'},el('label',{},'Expression: ',expression),context,tree.root,status);await modal('Quick Watch',{width:630,content,onReady:()=>evaluate(),buttons:[{label:'Recalculate',primary:true,action:evaluate},{label:'Add Watch',action:()=>{const text=expression.value.trim();if(text&&!this.ide.watches.includes(text)){this.ide.watches.push(text);this.normalizeWatches();this.ide.updateWatches();this.ide.autosave();}return false;}},{label:'Evaluate Function…',value:true,action:()=>{const text=expression.value.trim();setTimeout(()=>this.showEvaluation(text),0);}},{label:'Close',value:false}]});disposed=true;generation++;tree.dispose();}
 async showRuntimeError(data){
  this.errorDialogClose?.(false);
  const token=this.ide.bridgeToken,pauseId=data.pauseId,error=data.error;let closeDialog;
  const message=el('div',{class:'dialog-message'},"Run-time error '"+error.number+"':\n\n"+error.message);
  const current=()=>this.ide.bridgeToken===token&&this.ide.runState==='paused'&&this.pauseId===pauseId;
  await modal('Microsoft Visual Basic',{width:440,nativeModal:true,content:message,onReady:({finish})=>{closeDialog=finish;this.errorDialogClose=finish;},buttons:[
   {label:'End',value:'end',action:()=>{if(current())this.ide.stop(false);}},
   {label:'Debug',value:'debug',primary:true},
   {label:'Help',action:()=>{message.textContent="Run-time error '"+error.number+"':\n\n"+error.message+'\n\n'+(error.handled?'Continue delivers the error to the enabled On Error handler.':'Correct values or code, then Continue to retry the statement.')+' Set Next Statement can redirect execution within a safe region. End resets the project.';return false;}}
  ]});
  if(this.errorDialogClose===closeDialog)this.errorDialogClose=null;if(current())this.ide.editor.input.focus();
 }
 buildEvaluation(){
  const body=this.views.get('evaluation').body;
  this.evaluationExpression=el('input',{'aria-label':'Evaluation expression',spellcheck:false,style:{flex:1,minWidth:0}});
  const instructions=el('input',{type:'number',min:1,max:10000000,value:100000,'aria-label':'Evaluation instruction limit',style:{width:'95px'}}),time=el('input',{type:'number',min:1,max:60000,value:5000,'aria-label':'Evaluation time limit in milliseconds',style:{width:'80px'}});
  this.evaluationOutput=el('pre',{class:'output-text',role:'status',style:{whiteSpace:'pre-wrap',margin:'4px'}},'Explicit evaluation may run procedures and change application state. Automatic watches never do.');
  const cancel=el('button',{onclick:()=>this.ide.sendRuntime('cancelEvaluation')},'Cancel Evaluation');
  const execute=async()=>{if(this.ide.runState!=='paused'){this.evaluationOutput.textContent='Pause the program first.';return;}if(this.evaluationBusy)return;
   const expression=this.evaluationExpression.value.trim();if(!expression)return;this.evaluationBusy=true;this.evaluationOutput.textContent='Evaluating '+expression+'…';
   try{await this.ide.applyCodeChanges();const result=await this.ide.requestRuntime('debugEvaluate',{expression,frameIndex:this.frameIndex,pauseId:this.pauseId,instructionLimit:Number(instructions.value),timeLimit:Number(time.value)});this.evaluationOutput.textContent=expression+' = '+result.value;this.ide.locals=result.locals;this.localsTree.set(result.locals);this.ide.updateWatches();}
   catch(error){this.evaluationOutput.textContent=error.message;}
   finally{this.evaluationBusy=false;}
  };
  this.ide.attachExpressionIntelliSense?.(this.evaluationExpression);this.evaluationExpression.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();execute();}});
  body.append(el('div',{class:'debug-context-bar'},'Selected stack frame; side effects are retained, including after cancellation.'),el('div',{class:'watch-entry'},this.evaluationExpression,el('button',{onclick:execute},'Evaluate'),cancel),el('div',{class:'watch-entry'},el('label',{},'Instructions ',instructions),el('label',{},'Time (ms) ',time)),this.evaluationOutput);
 }
 showEvaluation(expression=this.selection()){this.evaluationExpression.value=expression;this.show('evaluation');queueMicrotask(()=>this.evaluationExpression.focus());}
 snapshot(){this.normalizeWatches();return this.watchDefinitions.map(w=>({...w}));}
 restore(definitions){if(!Array.isArray(definitions))return;this.watchDefinitions=definitions.slice(0,100).filter(w=>w&&typeof w.expression==='string'&&w.expression.length<=4096&&['expression','change','true'].includes(w.mode)).map(w=>({id:String(w.id||newId()),expression:w.expression,mode:w.mode,module:String(w.module||''),procedure:String(w.procedure||'')}));this.normalizeWatches();}
 syncWatches(){this.normalizeWatches();if(this.ide.runtimeFrame){this.ide.sendRuntime('watch',{expressions:this.ide.watches,frameIndex:this.frameIndex});const watches=this.watchDefinitions.filter(w=>w.mode!=='expression');const key=JSON.stringify(watches);if(key!==this.sentWatchpoints){this.sentWatchpoints=key;this.ide.sendRuntime('watchpoints',{watches});}}else this.ide.watchValues=this.ide.watches.map(expression=>({expression,value:'<not running>'}));this.renderWatches();}
}
export function installDebugWindows(ide){const workbench=ide.debuggerWindows=new DebugWorkbench(ide),show=ide.showDebug.bind(ide),toggle=ide.togglePanel.bind(ide),message=ide.onRuntimeMessage.bind(ide),command=ide.command.bind(ide),menu=ide.menu.bind(ide),snapshot=ide.layoutSnapshot.bind(ide),restore=ide.restoreLayout.bind(ide),key=ide.keydown.bind(ide);
  const designImmediate=ide.designImmediate=new DesignImmediateSession(ide);
  for(const method of ['run','stop','markDirty']){const original=ide[method].bind(ide);ide[method]=(...args)=>{designImmediate.reset();return original(...args);};}
  ide.executeImmediate=async text=>{
    const generation=designImmediate.generation,project=ide.project;
    try{
      if(ide.runtimeFrame){
        const token=ide.bridgeToken,pauseId=workbench.pauseId;
        const result=await ide.requestRuntime('agentImmediate',{text,frameIndex:ide.runState==='paused'?workbench.frameIndex:null,pauseId:ide.runState==='paused'?pauseId:undefined});
        if(ide.bridgeToken===token&&workbench.pauseId===pauseId){if(result.locals)ide.locals=result.locals;ide.updateWatches();workbench.schedule();}
        return result;
      }
      return await designImmediate.execute(text);
    }catch(error){if(ide.project===project&&generation===designImmediate.generation){ide.immediateOutput.push('Error: '+error.message);ide.renderDebug();}}
  };
  ide.showDebug=name=>workbench.show(name);ide.renderDebug=()=>workbench.refresh();ide.updateWatches=()=>workbench.syncWatches();ide.togglePanel=(id,value)=>{if(id==='debug'){if(value===false||value===undefined&&!ide.root.classList.contains('hidden-debug'))for(const key of workbench.views.keys())workbench.hide(key);else workbench.show(ide.debugTab);return;}return toggle(id,value);};
  ide.onRuntimeMessage=event=>{const data=event.data,valid=ide.runtimeFrame&&event.source===ide.runtimeFrame.contentWindow&&data?.channel==='vb6-runtime'&&data.token===ide.bridgeToken;if(valid&&data.type==='evaluation'){ide.evaluating=!!data.active;if(data.active){ide.evaluationWasMinimized=ide.runtimeWindow?.classList.contains('minimized');ide.runtimeWindow?.classList.remove('minimized');}else{if(ide.evaluationWasMinimized&&ide.runState==='paused')ide.runtimeWindow?.classList.add('minimized');ide.evaluationWasMinimized=false;}ide.updateCommandState();}if(valid&&data.type==='pause'){workbench.frameIndex=(data.stack?.length||1)-1;workbench.pauseId=data.pauseId||0;workbench.execution={module:data.source,line:data.line,column:data.column,endColumn:data.endColumn};workbench.refreshSerial++;}if(valid&&data.type==='state'&&data.state==='running')workbench.refreshSerial++;message(event);if(valid){if(data.type==='pause'&&data.error)workbench.showRuntimeError(data);if(data.type==='state'&&data.state!=='paused')workbench.errorDialogClose?.(false);if(data.type==='ready'){workbench.sentWatchpoints=null;workbench.syncWatches();}if(['pause','watches','immediate','error','output','state'].includes(data.type))workbench.schedule();}};
  ide.command=async(id,...args)=>{if(id==='evaluateExpression')return workbench.showEvaluation();if(id==='cancelEvaluation'){if(ide.runState==='design')return designImmediate.cancel();return ide.sendRuntime('cancelEvaluation');}if(id==='quickWatch')return workbench.quickWatch();if(id==='addWatch')return workbench.watchDialog();if(id==='showNextStatement'){const execution=workbench.execution,module=execution&&findModule(ide.project,execution.module);if(module&&ide.runState==='paused'){ide.openDocument(module.id,'code',execution.line);ide.editor.goToLine(execution.line,execution.column||1);ide.editor.input.focus();}return;}if(id==='runToCursor'){if(ide.runState==='design'&&ide.activeModule){if(!ide.executableLine(ide.activeModule.name,ide.editor.cursor().line))return alertDialog('The selected line is not executable.','Run to Cursor');return ide.run(false,{runToCursor:{module:ide.activeModule.name,line:ide.editor.cursor().line,column:ide.editor.cursor().column}});}if(ide.runState!=='paused'||!ide.activeModule)return alertDialog('Pause the program and select an executable code line.','Run to Cursor');try{await ide.applyCodeChanges();return await ide.requestRuntime('runToCursor',{module:ide.activeModule.name,line:ide.editor.cursor().line,column:ide.editor.cursor().column});}catch(error){return alertDialog(error.message,'Run to Cursor');}}return command(id,...args);};
  ide.menu=name=>{const items=menu(name);if(name==='Debug')items.splice(3,0,{id:'evaluateExpression',label:'Evaluate Expression…',enabled:ide.runState==='paused'},{id:'cancelEvaluation',label:'Cancel Evaluation',enabled:!!ide.evaluating},{id:'runToCursor',label:'Run to Cursor',shortcut:'Ctrl+F8',enabled:['design','paused'].includes(ide.runState)&&!!ide.activeModule},{id:'showNextStatement',label:'Show Next Statement',enabled:ide.runState==='paused'});return items;};
  ide.keydown=e=>{if(!e.defaultPrevented&&!hasUIDialog()&&e.key==='F8'&&(e.ctrlKey||e.metaKey)&&!e.shiftKey){e.preventDefault();ide.command('runToCursor');return;}return key(e);};
  ide.layoutSnapshot=()=>({...snapshot(),watchDefinitions:workbench.snapshot()});ide.restoreLayout=layout=>{restore(layout);workbench.restore(layout?.watchDefinitions);};
  ide.on('stop',()=>{workbench.errorDialogClose?.(false);workbench.sentWatchpoints=null;workbench.execution=null;workbench.frameIndex=null;workbench.refreshSerial++;workbench.schedule();});return workbench;
}
