import {layoutEnabled,validateLayout} from '../layout/contract.js';
import {hasUIDialog} from '../core/window-context.js';
import {el,clone,lower,download} from '../core/core.js';
import {scanDeclarations,wordAt} from '../editor/intelligence.js';
import {positionAt} from '../editor/projection.js';
import {THEMES,colorValue} from '../theme/theme.js';
import {normalizeIdeAppearance as normalizeAppearance,resolveIdeTheme} from '../theme/ide-appearance.js';
import {createIdeThemeSettings} from './theme-settings.js';
import {addProcedureSource,readProcedureAttributes,updateProcedureAttributes,formatControls} from './procedure-tools.js';
import {modal,alertDialog,tabbedPages} from './ui.js';
const check=(label,value)=>{const input=el('input',{type:'checkbox',checked:!!value});return {input,node:el('label',{class:'option-check'},input,label)};};
const field=(name,value,attrs={})=>el('input',{'aria-label':name,value,...attrs});
const select=(name,items,value)=>{const node=el('select',{'aria-label':name},...items.map(item=>el('option',{value:Array.isArray(item)?item[0]:item},Array.isArray(item)?item[1]:item)));node.value=value;return node;};
const group=(name,...children)=>el('fieldset',{},el('legend',{},name),...children);
export class IdeTools {
 constructor(ide){this.ide=ide;this.buildPalette();}
 async addProcedure(){const ide=this.ide,module=ide.activeModule;if(!module||ide.runState!=='design')return;const original=module.code,name=field('Procedure name',''),type=select('Procedure type',['Sub','Function','Property'],'Sub'),scope=select('Procedure scope',['Public','Private'],'Public'),staticLocals=check('All local variables as Static',false),body=el('div',{class:'dialog-grid'},el('label',{},'Name:'),name,el('label',{},'Type:'),type,el('label',{},'Scope:'),scope,staticLocals.node);
 await modal('Add Procedure',{width:390,content:body,buttons:[{label:'OK',value:true,primary:true,action:()=>{if(ide.activeModule!==module||module.code!==original||ide.runState!=='design')throw new Error('The module changed while this dialog was open.');const result=addProcedureSource(module,{name:name.value,type:type.value,scope:scope.value,staticLocals:staticLocals.input.checked}),before=clone(ide.project);module.code=result.code;ide.record(before,'Add '+result.name,false);ide.openDocument(module.id,'code',result.line);return true;}},{label:'Cancel',value:false}]});}
 async attributes(){const ide=this.ide,module=ide.activeModule;if(!module||ide.runState!=='design')return;const procedures=scanDeclarations(module).procedures,names=[...new Set(procedures.map(p=>p.name))];if(!names.length)return alertDialog('This module has no procedures.','Procedure Attributes');const current=procedures.filter(p=>p.line<=ide.editor.cursor().line).at(-1)?.name||names[0],name=select('Attribute procedure',names,current),description=field('Procedure description','',{maxlength:4096}),help=field('Help context ID',0,{type:'number',min:0,max:2147483647}),id=field('Procedure ID',''),hidden=check('Hide this member in Object Browser',false),restricted=check('Restricted member metadata',false),originalCode=module.code,originalAttributes=JSON.stringify(module.attributes||[]);
 const load=()=>{const a=readProcedureAttributes(module,name.value);description.value=a.description;help.value=a.helpContext;id.value=a.memberId??'';hidden.input.checked=a.hidden;restricted.input.checked=a.restricted;};name.addEventListener('change',load);load();
 await modal('Procedure Attributes',{width:520,content:el('div',{class:'procedure-attributes'},el('div',{class:'dialog-grid'},el('label',{},'Name:'),name,el('label',{},'Description:'),description,el('label',{},'Help Context ID:'),help),group('Advanced',el('div',{class:'dialog-grid'},el('label',{},'Procedure ID:'),id),hidden.node,restricted.node),el('p',{class:'tool-note'},'Attributes are saved in native source metadata. Native COM dispatch and Windows Help integration are not provided.')),buttons:[{label:'OK',value:true,primary:true,action:()=>{if(ide.activeModule!==module||ide.runState!=='design'||module.code!==originalCode||JSON.stringify(module.attributes||[])!==originalAttributes)throw new Error('The module changed while this dialog was open.');const attributes=updateProcedureAttributes(module,name.value,{description:description.value,helpContext:help.value,memberId:id.value,hidden:hidden.input.checked,restricted:restricted.input.checked}),before=clone(ide.project);module.attributes=attributes;ide.record(before,'Procedure attributes');return true;}},{label:'Cancel',value:false}]});
 }
 async options(){const ide=this.ide,initialProject=ide.project,a=normalizeAppearance(ide.appearance),settings=ide.project.settings,checks=new Map(),add=(key,label,value)=>{const item=check(label,value);checks.set(key,item.input);return item.node;},value=key=>checks.get(key).checked;
 const themeSettings=createIdeThemeSettings(a);
 const tab=field('Tab width',settings.tabWidth,{type:'number',min:1,max:32}),font=select('Editor font',['Courier New','Consolas','monospace'],a.editorFont),size=select('Editor font size',[11,12,13,14,16,18,20],a.editorSize),colors={...a.codeColors},theme=themeSettings.select,appTheme=select('Application theme',Object.values(THEMES).map(t=>[t.id,t.name]),settings.theme||'classic'),grid=field('Grid size (twips)',settings.gridSize||120,{type:'number',min:15,max:1200}),backend=select('Graphics backend',[['auto','WebGPU with Canvas2D fallback'],['canvas2d','Canvas2D']],settings.renderer||'auto');
 const editor=el('div',{},group('Code Settings',add('autoSyntaxCheck','Auto Syntax Check',a.autoSyntaxCheck),add('requireVariableDeclaration','Require Variable Declaration',a.requireVariableDeclaration),add('autoListMembers','Auto List Members',a.autoListMembers),add('autoQuickInfo','Auto Quick Info',a.autoQuickInfo),add('autoDataTips','Auto Data Tips',a.autoDataTips),add('autoIndent','Auto Indent',a.autoIndent),el('label',{class:'option-check'},'Tab Width: ',tab)),group('Window Settings',add('dragText','Drag-and-Drop Text Editing',a.dragText),add('fullModule','Default to Full Module View',a.fullModule),add('procedureSeparators','Procedure Separator',a.procedureSeparators)),el('p',{class:'tool-note'},'Automatic syntax diagnostics run after an edit without stealing focus. A worker is used when available; the fallback yields between modules. Check Project Syntax also validates cross-module constraints.'));
 const roles=[['text','Normal Text'],['background','Code Background'],['keyword','Keyword Text'],['comment','Comment Text'],['selection','Selection Background'],['selectionText','Selection Text'],['breakpoint','Breakpoint Background'],['execution','Execution Background']],role=select('Code color category',roles,'text'),color=field('Code color','#000000',{type:'color'}),sample=el('pre',{class:'editor-options-sample','aria-label':'Editor format sample'}),palette=()=>resolveIdeTheme(themeSettings.value(),!!theme.ownerDocument.defaultView.matchMedia?.('(prefers-color-scheme: dark)').matches).colors,roleMap={text:'windowText',background:'window',selectionText:'selectionText'};
 const samplePaint=()=>{const get=key=>colors[key]||palette()[roleMap[key]||key];sample.style.font=`${size.value}px/${Number(size.value)+4}px "${font.value}",monospace`;sample.style.background=get('background');sample.style.color=get('text');sample.replaceChildren(el('span',{style:{color:get('comment')}},"' This is a comment\n"),el('span',{style:{color:get('keyword')}},'Public Sub '),'Example()\n    Dim count As Long\n',el('span',{style:{color:get('keyword')}},'End Sub'));color.value=get(role.value);};for(const input of [font,size,theme,role])input.addEventListener('change',samplePaint);color.addEventListener('input',()=>{colors[role.value]=color.value;samplePaint();});themeSettings.onChange(samplePaint);samplePaint();
 const format=el('div',{},group('Code Colors',el('div',{class:'dialog-grid'},el('label',{},'Text category:'),role,el('label',{},'Color:'),color),el('button',{type:'button',onclick:()=>{delete colors[role.value];samplePaint();}},'Use System Color'),el('button',{type:'button',onclick:()=>{for(const key of Object.keys(colors))delete colors[key];samplePaint();}},'Reset All Colors')),el('div',{class:'dialog-grid'},el('label',{},'Font:'),font,el('label',{},'Size:'),size),add('margin','Margin Indicator Bar',a.margin),add('lineNumbers','Line numbers (browser extension)',settings.lineNumbers),sample);
 const errorTrapping=select('Error Trapping',[['all','Break on All Errors'],['class','Break in Class Module'],['unhandled','Break on Unhandled Errors']],settings.errorTrapping||'unhandled');
 const general=el('div',{},group('Layout Extensions',add('anchoring','Enable anchoring and automatic layout (this project)',layoutEnabled(ide.project)),el('p',{class:'tool-note'},'Off by default. Enables layout properties, designer tools and VB code in this project and its supported exports.')),group('Error Trapping',errorTrapping),group('Form Grid Settings',add('showGrid','Show Grid',settings.showGrid!==false),el('label',{class:'option-check'},'Grid Size (twips): ',grid),add('snapToGrid','Align Controls to Grid',settings.snapToGrid!==false)),group('Appearance',el('div',{class:'dialog-grid'},el('label',{},'IDE Theme:'),theme,el('label',{},'Application Theme:'),appTheme,el('label',{},'Graphics:'),backend),themeSettings.preferences,themeSettings.preview,themeSettings.note,add('tooltips','Show ToolTips',a.tooltips),add('largeToolbarIcons','Large Toolbar Buttons',a.largeToolbarIcons),add('documentTabs','Show Document Tabs',a.documentTabs)),group('Edit and Continue',add('notifyStateLoss','Notify Before State Loss',a.notifyStateLoss)));
 const dockList=el('div',{class:'options-dock-list'}),dockChecks=[];for(const [id,window]of ide.docking.model.windows){const view=ide.docking.panels.get(id),item=check(view.title,window.dockable);item.input.setAttribute('aria-label','Dockable '+view.title);dockList.append(item.node);dockChecks.push([id,item.input]);}
 const windowMode=select('IDE window mode',[
   ['mdi','In-page MDI only'],['hybrid','MDI with optional browser windows']
 ],a.windowMode);
 const docking=el('div',{},group('Window Mode',el('label',{class:'option-check'},'IDE window mode: ',windowMode),
   el('p',{class:'tool-note'},'In-page MDI supports moving, resizing, minimizing, maximizing, cascading and tiling documents. MDI-only returns detached panes without closing documents. Optional browser windows are opened only when requested; switching modes never opens popups automatically.')),
 el('p',{},'Select the windows that can dock. Clearing a box makes that window float inside the browser.'),dockList,el('p',{class:'tool-note'},'Drag a caption to an edge or another tool window. Hold Ctrl to suppress docking. Escape cancels a move.'));
 // Preserve absent optional defaults so an IDE-only change does not dirty the project or add an undo entry.
 const apply=()=>{if(ide.project!==initialProject)throw new Error('The current project changed.');const width=Number(tab.value),step=Number(grid.value);if(!Number.isInteger(width)||width<1||width>32)throw new Error('Tab width must be a whole number from 1 to 32.');if(!Number.isFinite(step)||step<15||step>1200)throw new Error('Grid size must be from 15 to 1200 twips.');const before=clone(ide.project),appearance={...a,...themeSettings.value(),windowMode:windowMode.value,codeColors:colors,theme:theme.value,editorFont:font.value,editorSize:Number(size.value)};for(const key of ['autoSyntaxCheck','requireVariableDeclaration','autoListMembers','autoQuickInfo','autoDataTips','autoIndent','dragText','fullModule','procedureSeparators','margin','tooltips','largeToolbarIcons','documentTabs','notifyStateLoss'])appearance[key]=value(key);validateLayout({...ide.project,settings:{...settings,anchoring:value('anchoring')}},false);Object.assign(settings,{anchoring:value('anchoring'),errorTrapping:errorTrapping.value,tabWidth:width,gridSize:step,showGrid:value('showGrid'),snapToGrid:value('snapToGrid'),lineNumbers:value('lineNumbers'),renderer:backend.value,theme:appTheme.value});if(!Object.hasOwn(before.settings,'anchoring')&&!settings.anchoring)delete settings.anchoring;if(!Object.hasOwn(before.settings,'errorTrapping')&&settings.errorTrapping==='unhandled')delete settings.errorTrapping;ide.sendRuntime('debuggerOptions',{errorTrapping:errorTrapping.value});if(!Object.hasOwn(before.settings,'lineNumbers')&&!settings.lineNumbers)delete settings.lineNumbers;if(!Object.hasOwn(before.settings,'theme')&&settings.theme==='classic')delete settings.theme;ide.appearance=normalizeAppearance(appearance);for(const [id,input]of dockChecks)ide.docking.model.setDockable(id,input.checked);ide.docking.render();ide.docking.changed();ide.applyAppearance();ide.commandBars?.render();if(JSON.stringify(before)!==JSON.stringify(ide.project))ide.record(before,'Options');else ide.renderAll();ide.autosave();return true;};
 await modal('Options',{width:555,content:tabbedPages([{id:'editor',label:'Editor',node:editor},{id:'format',label:'Editor Format',node:format},{id:'general',label:'General',node:general},{id:'docking',label:'Docking',node:docking}],{label:'Options categories',selected:'editor'}),buttons:[{label:'OK',value:true,primary:true,action:apply},{label:'Cancel',value:false}]});
 }
 buildPalette(){const ide=this.ide,body=el('div',{class:'ide-color-palette'}),target=select('Palette property',['BackColor','ForeColor'],'BackColor'),sample=el('div',{class:'ide-palette-sample'},'Sample'),swatches=el('div',{class:'ide-palette-swatches',role:'toolbar','aria-label':'Color palette'});this.paletteTarget=target;const colors=['#000000','#808080','#800000','#808000','#008000','#008080','#000080','#800080','#ffffff','#c0c0c0','#ff0000','#ffff00','#00ff00','#00ffff','#0000ff','#ff00ff'];
 const apply=color=>{sample.style[target.value==='BackColor'?'background':'color']=colorValue(color);if(ide.runState!=='design'||!ide.activeModule?.form){ide.status('Select a form or control to apply a palette color.');return;}ide.setProperty(target.value,color);};for(const [index,hex]of colors.entries()){const rgb=parseInt(hex.slice(1),16),bgr=((rgb&255)<<16)|(rgb&65280)|(rgb>>>16),button=el('button',{type:'button','aria-label':'Palette '+hex,title:hex,style:{background:hex},tabindex:index? -1:0,onclick:()=>apply(bgr)});swatches.append(button);}
 swatches.addEventListener('keydown',e=>{const buttons=[...swatches.children],index=buttons.indexOf(swatches.ownerDocument.activeElement);if(index<0)return;const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:e.key==='ArrowRight'?Math.min(index+1,15):e.key==='ArrowLeft'?Math.max(index-1,0):e.key==='ArrowDown'?Math.min(index+8,15):e.key==='ArrowUp'?Math.max(index-8,0):-1;if(next>=0){e.preventDefault();buttons.forEach((b,i)=>b.tabIndex=i===next?0:-1);buttons[next].focus();}});
 body.append(el('div',{class:'ide-palette-header'},target,sample),swatches,el('button',{type:'button',onclick:()=>apply(target.value==='BackColor'?0x8000000f:0x80000012)},'System Color'));const panel=el('section',{class:'ide-color-palette-window'},ide.caption('Color Palette',()=>ide.docking.show('colorPalette',false)),body);ide.docking.register('colorPalette',panel,{edge:'bottom',hidden:true,title:'Color Palette'});
 }
 format(command){const ide=this.ide,designer=ide.designer;if(ide.runState!=='design'||!ide.activeModule?.form||designer.locked)return;const controls=designer.selected();if(!controls.length)return;const before=clone(ide.project),changed=formatControls(ide.activeModule.form,controls,command,ide.project.settings.gridSize||120,designer.primaryId);if(changed)ide.record(before,'Format '+command);}
 async printCode(){const ide=this.ide,module=ide.activeModule;if(!module)return;const range=ide.editor.selectionBounds(),selection=module.code.slice(range.start,range.end),scope=select('Print range',[['module','Current Module'],['project','Current Project'],...(selection?[['selection','Selection']]:[])],'module'),numbers=check('Line numbers',true);const yes=await modal('Print Code',{width:400,content:el('div',{},el('label',{},'Range: ',scope),numbers.node,el('p',{class:'tool-note'},'Opens a browser print window containing source only. Browser and operating-system print settings remain native.'))});if(!yes)return;const docs=scope.value==='project'?ide.project.modules:[{...module,code:scope.value==='selection'?selection:module.code}],escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),html='<!doctype html><html><meta charset="utf-8"><title>'+escape(ide.project.name)+' — Code</title><style>body{font:12px monospace}section{break-before:page}section:first-child{break-before:auto}pre{white-space:pre-wrap;tab-size:'+Number(ide.project.settings.tabWidth||4)+'}button{font:13px sans-serif}@media print{button{display:none}}</style><button onclick="print()">Print</button>'+docs.map(m=>'<section><h2>'+escape(m.name)+'</h2><pre>'+escape(numbers.input.checked?m.code.split('\n').map((line,i)=>String(i+1).padStart(5)+'  '+line).join('\n'):m.code)+'</pre></section>').join('')+'</html>';const win=window.open('about:blank','_blank');if(win){win.opener=null;win.document.write(html);win.document.close();}else {download(ide.project.name+'-source-print.html',html,'text/html');ide.status('Popup blocked; downloaded the source print document instead.');}}
}
export function installIdeTools(ide){const tools=ide.ideTools=new IdeTools(ide),command=ide.command.bind(ide),menu=ide.menu.bind(ide);ide.optionsDialog=()=>tools.options();ide.command=async(id,...args)=>{if(id==='addProcedure')return tools.addProcedure();if(id==='procedureAttributes')return tools.attributes();if(id==='colorPalette')return ide.docking.show('colorPalette',true);if(id==='printCode')return tools.printCode();if(id.startsWith('format:'))return tools.format(id.slice(7));if(id==='stop'&&ide.runState==='paused'&&ide.appearance.notifyStateLoss){const yes=await modal('Reset Project',{width:390,content:el('p',{},'Ending execution will discard the current variable values. End this project?')});if(!yes)return;}return command(id,...args);};
 ide.menu=name=>{const items=menu(name),design=ide.runState==='design'&&!!ide.activeModule;if(name==='Tools')items.unshift({id:'addProcedure',label:'Add Procedure…',enabled:design},{id:'procedureAttributes',label:'Procedure Attributes…',enabled:design},null);if(name==='View')items.push(null,{id:'colorPalette',label:'Color Palette'});if(name==='File'){const at=items.findIndex(i=>i?.id==='projectProperties');items.splice(at<0?items.length:at,0,{id:'printCode',label:'Print Code…',shortcut:'Ctrl+P',enabled:!!ide.activeModule});}if(name==='Format'){for(const [axis,label]of [['horizontal','Horizontal Spacing'],['vertical','Vertical Spacing']])items.push({label,items:[['Equal','Make Equal'],['Increase','Increase'],['Decrease','Decrease'],['Remove','Remove']].map(([suffix,title])=>({id:'format:'+axis+suffix,label:title,enabled:design}))});items.push({label:'Center in Form',items:[['Horizontal','Horizontally'],['Vertical','Vertically']].map(([axis,title])=>({id:'format:center'+axis+'InForm',label:title,enabled:design}))},{label:'Size to',items:[['Grid','Grid'],['Tallest','Tallest'],['Shortest','Shortest'],['Widest','Widest'],['Narrowest','Narrowest']].map(([size,label])=>({id:'format:sizeTo'+size,label,enabled:design}))});}return items;};const key=ide.keydown.bind(ide);ide.keydown=e=>{if(!e.defaultPrevented&&!hasUIDialog()&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='p'){e.preventDefault();ide.command('printCode');return;}return key(e);};return tools;}
