import {installResourceEditor} from './resource-editor.js';
import {readRES,writeRES,setResource,setResourceString} from '../project/res.js';
import {installDiagnostics} from './diagnostics.js';
import {installEditorFeatures} from '../editor/ide-integration.js';
import {installDocking} from './docking.js';
import {installCommandBars} from './command-bars.js';
import {installDebugWindows} from './debug-windows.js';
import {installIdeTools} from './ide-tools.js';
import {installBrowserWindows} from './browser-windows.js';
import {hasUIDialog,uiDocument} from '../core/window-context.js';
import {installWorkspaceState} from './workspace-state.js';
import {fromBase64,toBase64} from '../project/frx.js';
import { Signal, History, el, clone, lower, safeName, download, debounce, VERSION } from '../core/core.js';
import { newProject, createForm, createControl, normalizeProject, newId, uniqueName, findModule, BASIC_CONTROL_TYPES, EXTENDED_CONTROL_TYPES, projectStats } from '../project/model.js';
import { importFiles, sourceFiles } from '../project/formats.js';
import { readZip, writeZip } from '../project/zip.js';
import { EXAMPLES } from '../project/examples.js';
import { compileProject } from '../language/compiler.js';
import { exportApplication } from '../exporter/exporter.js';
import { FormDesigner } from '../designer/designer.js';
import { SourceEditor } from '../editor/editor.js';
import { procedures, renameSymbol, defaultEventSignature, BUILTINS, MEMBERS } from '../editor/language-service.js';
import { DEFAULT_EVENTS, CONTROL_EVENTS } from '../controls/controls.js';
import { PropertyInspector } from './properties.js';
import { icon, controlIcon, showMenu, closeMenu, modal, alertDialog, promptDialog, makeDraggable, resizeHandle, tabbedPages } from './ui.js';
import {ClassicTooltips} from '../theme/tooltip.js';
import {ObjectBrowser} from './object-browser.js';
import {ProjectSearch} from './project-search.js';
import {mapBookmarks,normalizeBookmarks,navigateBookmark} from '../editor/navigation.js';
import {IdeDocuments} from './documents.js';
import {THEMES,applyTheme,normalizeAppearance} from '../theme/theme.js';
import {menuIsOpen,mnemonicText} from '../theme/menu.js';

const STORAGE_KEY='vb6-studio-web.workspace.v1';
const DEBUG_TABS=['Immediate','Locals','Watch','Call Stack','Breakpoints','Errors','Output'];
const EVENT_LIST={Form:['Load','Initialize','Activate','Deactivate','Resize','QueryUnload','Unload','Click','DblClick','KeyDown','KeyPress','KeyUp'],Timer:['Timer'],TreeView:['NodeClick','Click','DblClick'],ListView:['ItemClick','Click','DblClick'],Toolbar:['ButtonClick'],MonthView:['DateClick'],TextBox:['Change',...CONTROL_EVENTS],RichTextBox:['Change',...CONTROL_EVENTS],Slider:['Change',...CONTROL_EVENTS],ComboBox:['Click','Change',...CONTROL_EVENTS]};
export class VB6Studio extends Signal {
  constructor(container){super();this.container=container;this.appearance=normalizeAppearance();this.visualRevision=0;this.history=new History(120);this.docs=[];this.breakpoints=[];this.watches=[];this.output=[];this.immediateOutput=[];this.diagnostics=[];this.locals=[];this.stack=[];this.watchValues=[];this.runState='design';this.debugTab='Immediate';this.toolboxMode='standard';this.expandedFolders=new Set(['form','module','class']);this.autosave=debounce(()=>this.persist(),600);this.buildShell();this.bindEvents();let project;try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved?.project){project=normalizeProject(saved.project);this.breakpoints=saved.breakpoints||[];this.watches=saved.watches||[];this.restoreLayout(saved.layout);}}catch{}this.loadProject(project||EXAMPLES[0].create(),{initial:true});this.restoreDocuments();this.applyAppearance();this.status('Ready');}
  buildShell(){this.root=el('div',{class:'ide-shell hidden-debug'});this.titleText=el('span',{class:'app-title-text'});this.titlebar=el('div',{class:'app-title'},el('span',{class:'brand-icon'},icon('project')),this.titleText,el('div',{class:'window-buttons'},el('button',{title:'Toggle full screen',onclick:()=>this.command('fullScreen')},icon('maximize',12)),el('button',{title:'About this application',onclick:()=>this.command('about')},'?')));this.menubar=el('nav',{class:'menubar','aria-label':'Main menu'});for(const name of ['File','Edit','View','Project','Format','Debug','Run','Tools','Window','Help']){const button=el('button',{'data-menu':name,onclick:()=>this.openMenu(name,button)},name);this.menubar.append(button);}this.toolbar=el('div',{class:'toolbar',role:'toolbar','aria-label':'Standard toolbar'},el('span',{class:'toolbar-grip'}));const tools=[['new','new','New Project (Ctrl+N)'],['open','open','Open Project (Ctrl+O)'],['save','save','Save Project (Ctrl+S)'],null,['cut','cut','Cut (Ctrl+X)'],['copy','copy','Copy (Ctrl+C)'],['paste','paste','Paste (Ctrl+V)'],null,['undo','undo','Undo (Ctrl+Z)'],['redo','redo','Redo (Ctrl+Shift+Z)'],null,['run','run','Start / Continue (F5)'],['pause','pause','Break (Ctrl+Break)'],['stop','stop','End (Shift+F5)'],['stepInto','step','Step Into (F8)'],null,['viewCode','code','View Code (F7)'],['viewForm','form','View Object (Shift+F7)'],['projectExplorer','project','Project Explorer (Ctrl+R)'],['properties','properties','Properties Window (F4)'],['objectBrowser','object','Object Browser (F2)'],null,['find','find','Find (Ctrl+F)'],['exportHTML','export','Make standalone HTML application']];for(const entry of tools){if(!entry){this.toolbar.append(el('span',{class:'tool-separator'}));continue;}const [id,glyph,title]=entry,button=el('button',{class:'tool-button'+(['cut','copy','paste','find'].includes(id)?' secondary-tool':'')+(['stepInto','projectExplorer','objectBrowser'].includes(id)?' optional-tool':''),title,'aria-label':title,'data-command':id,onclick:()=>this.command(id)},icon(glyph));this.toolbar.append(button);}this.toolbar.append(el('span',{class:'toolbar-spacer'}));this.zoomSelect=el('select',{class:'toolbar-select','aria-label':'Designer zoom',style:{width:'76px'},onchange:()=>this.designer.setZoom(Number(this.zoomSelect.value))},...[.5,.75,1,1.25,1.5,2].map(n=>el('option',{value:n,selected:n===1},Math.round(n*100)+'%')));this.toolbar.append(this.zoomSelect);
    this.workspace=el('main',{class:'workspace'});this.toolbox=el('section',{class:'toolbox','aria-label':'Toolbox'},this.caption('Toolbox',()=>this.togglePanel('toolbox')));this.toolboxFilter=el('select',{class:'toolbox-filter','aria-label':'Toolbox category',onchange:()=>{this.toolboxMode=this.toolboxFilter.value;this.renderToolbox();}},el('option',{value:'standard'},'General'),el('option',{value:'extended'},'Controls'),el('option',{value:'all'},'All'));this.toolboxGrid=el('div',{class:'toolbox-grid',role:'toolbar','aria-label':'Form controls'});this.toolbox.append(this.toolboxFilter,this.toolboxGrid);this.center=el('section',{class:'center-dock'});this.documentArea=el('div',{class:'document-area'});this.documentLabel=el('strong');this.documentTitle=el('div',{class:'document-title'},icon('form'),this.documentLabel,el('div',{class:'window-buttons'},el('button',{title:'Tile code and designer',onclick:()=>this.command('tile')},'▥'),el('button',{title:'Close current document',onclick:()=>this.closeDocument()},'×')));this.views=el('div',{class:'document-views'});this.designerPane=el('div',{class:'designer-pane'});this.codePane=el('div',{class:'code-pane'});this.views.append(this.designerPane,this.codePane);this.documentTabs=el('div',{class:'document-tabs',role:'tablist','aria-label':'Open documents'});this.documentArea.append(this.documentTitle,this.views,this.documentTabs);this.center.append(this.documentArea);this.debugResizer=el('div',{class:'split-handle split-horizontal debug-resizer'});this.debugDock=el('section',{class:'debug-dock','aria-label':'Debug windows'});this.debugCaption=this.caption('Immediate',()=>this.togglePanel('debug'));this.debugBody=el('div',{class:'debug-body'});this.debugTabs=el('div',{class:'debug-tabs',role:'tablist'});for(const tab of DEBUG_TABS)this.debugTabs.append(el('button',{role:'tab','data-debug-tab':tab,onclick:()=>this.showDebug(tab)},tab));this.debugDock.append(this.debugCaption,this.debugBody,this.debugTabs);this.center.append(this.debugResizer,this.debugDock);resizeHandle(this.debugResizer,'y',delta=>{const value=this.debugDock.offsetHeight-delta;this.root.style.setProperty('--bottom-height',Math.max(85,Math.min(innerHeight*.55,value))+'px');this.autosave();});
    this.right=el('aside',{class:'right-dock'});this.projectPanel=el('section',{class:'dock-panel project-panel','aria-label':'Project Explorer'});this.projectCaption=this.caption('Project - Project1',()=>this.togglePanel('project'));this.projectPanel.append(this.projectCaption);this.projectToolbar=el('div',{class:'panel-toolbar'},this.smallButton('viewCode','code','View Code'),this.smallButton('viewForm','form','View Object'),this.smallButton('toggleFolders','folder','Toggle folders'));this.projectTree=el('div',{class:'project-tree',role:'tree','aria-label':'Project Explorer'});this.projectPanel.append(this.projectToolbar,this.projectTree);this.projectResizer=el('div',{class:'split-handle split-horizontal'});resizeHandle(this.projectResizer,'y',delta=>{this.root.style.setProperty('--project-height',Math.max(95,Math.min(450,this.projectPanel.offsetHeight+delta))+'px');this.autosave();});this.propertiesPanel=el('section',{class:'dock-panel properties-panel','aria-label':'Properties'});this.propertyCaption=this.caption('Properties — frmOrders',()=>this.togglePanel('properties'));this.propertiesPanel.append(this.propertyCaption);this.inspector=new PropertyInspector(this.propertiesPanel,this);this.layoutPanel=el('section',{class:'dock-panel layout-panel'},this.caption('Form Layout',()=>this.togglePanel('layout')));this.layoutScreen=el('div',{class:'layout-screen'});this.layoutMini=el('div',{class:'layout-mini-form',title:'Drag to change the form startup position'});this.layoutScreen.append(this.layoutMini);this.layoutPanel.append(el('div',{class:'layout-monitor'},this.layoutScreen));this.right.append(this.projectPanel,this.projectResizer,this.propertiesPanel,this.layoutPanel);const rightResizer=el('div',{class:'split-handle split-vertical',style:{gridColumn:'4'}});resizeHandle(rightResizer,'x',delta=>{this.root.style.setProperty('--right-width',Math.max(195,Math.min(550,this.right.offsetWidth-delta))+'px');this.autosave();});this.workspace.append(this.toolbox,el('div',{style:{gridColumn:'2'}}),this.center,rightResizer,this.right);
    this.statusbar=el('footer',{class:'statusbar'});this.statusMessage=el('span',{class:'status-field status-message',role:'status'});this.statusPosition=el('span',{class:'status-field status-position'},'0, 0');this.statusCursor=el('span',{class:'status-field status-cursor'},'Ln 1, Col 1');this.statusBackend=el('span',{class:'status-field status-backend'},'Canvas2D');this.statusMode=el('span',{class:'status-field status-mode'},'Design');this.statusbar.append(this.statusMessage,this.statusPosition,this.statusCursor,this.statusBackend,this.statusMode);this.root.append(this.titlebar,this.menubar,this.toolbar,this.workspace,this.statusbar);this.container.append(this.root);
    this.documentTitle.remove();this.views.remove();this.documents=new IdeDocuments(this);installEditorFeatures(this);this.tooltips=new ClassicTooltips(this.root,{enabled:()=>this.appearance.tooltips});this.rightResizer=rightResizer;this.installMenuBar();this.installWorkspaceNavigation();installDocking(this);installCommandBars(this);installDebugWindows(this);installIdeTools(this);installDiagnostics(this);installWorkspaceState(this);installBrowserWindows(this);installResourceEditor(this);this.fileInput=el('input',{type:'file',multiple:true,accept:'.vb6web,.vb6proj,.vbp,.frm,.bas,.cls,.frx,.res,.zip,.json,.png,.jpg,.bmp,.gif,.ico',hidden:true});this.root.append(this.fileInput);this.fileInput.addEventListener('change',()=>{const files=[...this.fileInput.files];this.fileInput.value='';this.importBrowserFiles(files,{add:this.addingFiles});});}
  caption(text,onClose){return el('div',{class:'tool-caption'},el('strong',{},text),el('button',{title:'Hide window','aria-label':'Hide '+text.split(' — ')[0],onclick:onClose},icon('close',12)));}
  smallButton(id,glyph,title){return el('button',{class:'tool-button',title,'aria-label':title,'data-command':id,onclick:()=>this.command(id)},icon(glyph));}
  makeDockable(panel){const header=panel.querySelector('.tool-caption');header.tabIndex=0;header.setAttribute('aria-label',panel.getAttribute('aria-label')||header.textContent);const toggle=()=>{if(panel.classList.contains('panel-floating')){panel.classList.remove('panel-floating');panel.removeAttribute('style');this.status('Window docked.');}else{const r=panel.getBoundingClientRect();panel.classList.add('panel-floating');Object.assign(panel.style,{left:Math.max(0,Math.min(innerWidth-220,r.left-140))+'px',top:Math.max(0,Math.min(innerHeight-180,r.top))+'px',width:Math.max(210,r.width)+'px',height:Math.max(140,r.height)+'px'});this.status('Double-click the title bar to dock this window.');}this.updateDockVisibility();this.autosave();};header.addEventListener('dblclick',e=>{if(!e.target.closest('button'))toggle();});header.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='Enter'){e.preventDefault();toggle();}});header.addEventListener('contextmenu',e=>{e.preventDefault();showMenu([{label:'Dockable',checked:!panel.classList.contains('panel-floating'),action:toggle},null,{label:'Hide',action:()=>header.querySelector('button')?.click()}],e.clientX,e.clientY);});header.addEventListener('pointerdown',event=>{if(!panel.classList.contains('panel-floating')||event.target.closest('button')||event.button!==0)return;event.preventDefault();const r=panel.getBoundingClientRect(),x=event.clientX,y=event.clientY;header.setPointerCapture(event.pointerId);const move=e=>{panel.style.left=Math.max(0,Math.min(innerWidth-panel.offsetWidth,r.left+e.clientX-x))+'px';panel.style.top=Math.max(0,Math.min(innerHeight-24,r.top+e.clientY-y))+'px';};const up=()=>{header.removeEventListener('pointermove',move);header.removeEventListener('pointerup',up);header.removeEventListener('pointercancel',up);header.removeEventListener('lostpointercapture',up);this.autosave();};header.addEventListener('pointermove',move);header.addEventListener('pointerup',up);header.addEventListener('pointercancel',up);header.addEventListener('lostpointercapture',up);});const observer=new ResizeObserver(()=>{if(panel.classList.contains('panel-floating'))this.autosave();});observer.observe(panel);(this.dockObservers||=[]).push(observer);}
  bindEvents(){this.history.on('change',()=>this.updateCommandState());
    document.addEventListener('keydown',e=>this.keydown(e));document.addEventListener('keyup',e=>{if(e.key==='Alt'&&this.altCandidate){this.altCandidate=false;if(document.querySelector('.ide-modal-cover,.property-color-popup'))return;e.preventDefault();if(this.menubar.contains(document.activeElement)){closeMenu();this.menuReturnFocus?.focus();}else{this.menuReturnFocus=document.activeElement;this.menubar.firstElementChild.focus();}}});window.addEventListener('message',e=>this.onRuntimeMessage(e));this.root.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();if(!this.dropOverlay){this.dropOverlay=el('div',{class:'dnd-overlay'},'Open project or source files');this.root.append(this.dropOverlay);}}});this.root.addEventListener('dragleave',e=>{if(!this.root.contains(e.relatedTarget)){this.dropOverlay?.remove();this.dropOverlay=null;}});this.root.addEventListener('drop',e=>{e.preventDefault();this.dropOverlay?.remove();this.dropOverlay=null;this.importBrowserFiles([...e.dataTransfer.files]);});this.bindLayoutMini();window.addEventListener('beforeunload',()=>this.persist());}
  get activeModule(){return this.project?findModule(this.project,this.activeDoc?.id):null;}
  loadProject(project,{initial=false}={}){this.stop(false);this.documents.reset();this.visualRevision++;this.project=normalizeProject(project);this.editor.showLineNumbers=!!this.project.settings.lineNumbers;this.history.reset();this.docs=[];this.activeDoc=null;this.splitView=false;this.dirty=false;this.savedJSON=JSON.stringify(this.project);this.diagnostics=[];this.output=[];this.immediateOutput=[];this.locals=[];this.stack=[];this.watchValues=[];if(!initial){this.breakpoints=[];this.watches=[];}const first=findModule(this.project,this.project.startup)||this.project.modules[0];if(first)this.openDocument(first.id,first.form?'form':'code');else this.renderAll();this.renderToolbox();this.renderDebug();this.persist();this.rememberProject();}
  openDocument(id,view='code',line){const module=findModule(this.project,id);if(!module)return;view=module.form?view:'code';const key=module.id+':'+view;let doc=this.docs.find(d=>d.key===key);if(!doc){doc={key,id:module.id,view};this.docs.push(doc);}this.documents.activate(doc);if(this.documents.mdi.windows.get(key)?.minimized)this.documents.mdi.restore(key);if(line&&view==='code')this.editor.goToLine(line);this.autosave();}
  closeDocument(key=this.documents.mdi.active||this.activeDoc?.key){if(this.documents.closeTool(key))return;const index=this.docs.findIndex(d=>d.key===key);if(index<0)return;this.docs.splice(index,1);this.documents.close(key);if(this.activeDoc?.key===key)this.activeDoc=this.docs[Math.max(0,index-1)]||null;this.renderDocument();this.renderProjectTree();this.inspector.render();this.autosave();}
  renderDocument(){this.documents.sync();this.updateLayoutMini();this.updateCommandState();}
  renderAll(){this.visualRevision++;this.renderDocument();this.renderProjectTree();this.inspector.render();this.renderToolbox();this.updateTitle();this.renderDebug();}
  renderToolbox(){let types=this.toolboxMode==='extended'?['Pointer',...EXTENDED_CONTROL_TYPES]:this.toolboxMode==='all'?[...BASIC_CONTROL_TYPES,...EXTENDED_CONTROL_TYPES]:BASIC_CONTROL_TYPES;this.toolboxGrid.replaceChildren(...types.map(type=>el('button',{class:type===this.designer.tool?'active':'',title:type,'aria-label':type,'data-control-type':type,disabled:this.runState!=='design',onclick:()=>{if(!this.activeModule?.form){this.status('Open a form to use the toolbox.');return;}if(this.activeDoc.view!=='form')this.openDocument(this.activeModule.id,'form');this.designer.setTool(type);},ondblclick:()=>{if(type!=='Pointer'&&this.activeModule?.form)this.addControl(type);}},controlIcon(type))));}
  addControl(type){if(this.runState!=='design'||!this.activeModule?.form)return;const module=this.activeModule,before=clone(this.project),name=uniqueName(this.project,type,module),control=createControl(type,name,360,360);module.form.controls.push(control);this.record(before,'Add '+type);this.designer.select([control.id]);this.designer.setTool('Pointer');}
  renderProjectTree(){if(!this.project)return;this.projectCaption.querySelector('strong').textContent='Project - '+this.project.name;this.projectTree.replaceChildren();const root=el('div',{class:'tree-row',role:'treeitem','aria-expanded':'true'},el('span',{class:'tree-toggle'},'−'),icon('project'),el('span',{class:'tree-label'},this.project.name+' ('+this.project.name+'.vbp)'));root.addEventListener('contextmenu',e=>{e.preventDefault();showMenu(this.projectMenu(),e.clientX,e.clientY,id=>this.command(id));});this.projectTree.append(root);for(const kind of ['form','module','class']){const modules=this.project.modules.filter(m=>m.kind===kind);if(!modules.length)continue;const label={form:'Forms',module:'Modules',class:'Class Modules'}[kind];if(!this.noFolders){const group=el('div',{class:'tree-row',role:'treeitem','aria-expanded':this.expandedFolders.has(kind)},el('span',{class:'tree-indent'}),el('span',{class:'tree-toggle'},this.expandedFolders.has(kind)?'−':'+'),icon('folder'),el('span',{class:'tree-label'},label));group.addEventListener('click',()=>{if(this.expandedFolders.has(kind))this.expandedFolders.delete(kind);else this.expandedFolders.add(kind);this.renderProjectTree();});this.projectTree.append(group);}if(!this.noFolders&&!this.expandedFolders.has(kind))continue;for(const module of modules){const row=el('div',{class:'tree-row'+(this.activeModule?.id===module.id?' selected':''),role:'treeitem',tabindex:0,'data-module':module.name,style:{paddingLeft:this.noFolders?'18px':'36px'}},icon(kind==='form'?'form':kind),el('span',{class:'tree-label'},module.name+' ('+module.name+'.'+(kind==='form'?'frm':kind==='class'?'cls':'bas')+')'));row.addEventListener('click',()=>this.openDocument(module.id,module.form?'form':'code'));row.addEventListener('dblclick',()=>this.openDocument(module.id,module.form?'form':'code'));row.addEventListener('keydown',e=>{if(e.key==='Enter')this.openDocument(module.id,module.form?'form':'code');if(e.key==='F7')this.openDocument(module.id,'code');});row.addEventListener('contextmenu',e=>{e.preventDefault();this.openDocument(module.id,this.activeModule?.id===module.id?this.activeDoc.view:module.form?'form':'code');showMenu([{label:'View Code',id:'viewCode',icon:'code',shortcut:'F7'},module.form?{label:'View Object',id:'viewForm',icon:'form',shortcut:'Shift+F7'}:null,null,{label:'Save '+module.name+' As…',id:'saveModule',icon:'save'},{label:'Rename…',id:'renameModule'},{label:'Remove '+module.name,id:'removeModule',icon:'delete'},null,...this.projectMenu().slice(0,3)],e.clientX,e.clientY,id=>this.command(id));});this.projectTree.append(row);}}}
  record(before,label,render=true,mapSourceBookmarks=true){if(mapSourceBookmarks)for(const module of this.project.modules){const old=before.modules.find(m=>m.id===module.id);if(old&&old.code!==module.code)module.bookmarks=mapBookmarks(old.code,module.code,old.bookmarks);}this.visualRevision++;this.history.record(before,this.project,label);this.markDirty();if(render)this.renderAll();}
  markDirty(fast=false){this.dirty=fast||JSON.stringify(this.project)!==this.savedJSON;this.updateTitle();this.updateCommandState();this.autosave();}
  updateTitle(){if(!this.project)return;const mode=this.runState==='design'?'design':this.runState==='paused'?'break':'run';this.titleText.textContent=this.project.name+(this.dirty?' *':'')+' - Microsoft Visual Basic ['+mode+']';document.title=this.project.name+' — VB6 Studio Web';this.statusMode.textContent=mode==='design'?'Design':mode==='break'?'Break':'Run';}
  status(text){this.statusMessage.textContent=text;}
  updateCommandState(){const running=this.runState!=='design',paused=this.runState==='paused';const state={undo:!running&&!!this.history.undoStack.length,redo:!running&&!!this.history.redoStack.length,pause:running&&!paused,stop:running,viewForm:!!this.activeModule?.form,viewCode:!!this.activeModule,exportHTML:!running,cut:!running,copy:true,paste:!running};for(const button of this.toolbar?.querySelectorAll('[data-command]')||[])button.disabled=state[button.dataset.command]===false;this.statusMode&&(this.statusMode.textContent=paused?'Break':running?'Run':'Design');}
  persist(){if(!this.project)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify({project:this.project,breakpoints:this.breakpoints,watches:this.watches,layout:this.layoutSnapshot()}));this.storageAvailable=true;}catch{this.storageAvailable=false;}this.emit('persist',{available:this.storageAvailable});}
  applyAppearance(){this.tooltips?.hide();this.appearance=normalizeAppearance(this.appearance);applyTheme(document.documentElement,this.appearance.theme);this.root.classList.toggle('show-document-tabs',this.appearance.documentTabs);this.root.classList.toggle('show-debug-tabs',this.appearance.debugTabs);this.root.classList.toggle('hide-tooltips',!this.appearance.tooltips);for(const editor of this.documents.editors.values()){editor.setAppearance?.(this.appearance);editor.showLineNumbers=!!this.project?.settings.lineNumbers;editor.paint();}this.autosave();}
  updateDockVisibility(){const visible=[this.projectPanel,this.propertiesPanel,this.layoutPanel].some(p=>!p.hidden&&!p.classList.contains('panel-floating'));this.root.classList.toggle('hidden-right',!visible);this.projectResizer.hidden=this.projectPanel.hidden||this.propertiesPanel.hidden;this.right.classList.toggle('no-properties',this.propertiesPanel.hidden);}
  restoreDocuments(){const saved=this.savedDocumentLayout;this.savedDocumentLayout=null;if(!saved?.docs?.length)return;for(const doc of saved.docs.slice(0,24))if(doc&&['code','form'].includes(doc.view)&&findModule(this.project,doc.id))this.openDocument(doc.id,doc.view);this.documents.mdi.restoreSnapshot(saved.windows);const active=this.docs.find(d=>d.key===saved.activeDoc);if(active)this.documents.activate(active);}
  installMenuBar(){this.menubar.setAttribute('role','menubar');const keys={File:'F',Edit:'E',View:'V',Project:'P',Format:'o',Debug:'D',Run:'R',Tools:'T',Window:'W',Help:'H'};for(const button of this.menubar.children){const name=button.dataset.menu;button.setAttribute('role','menuitem');button.setAttribute('aria-haspopup','menu');button.setAttribute('aria-expanded','false');button.tabIndex=-1;mnemonicText(button,name,keys[name]);button.addEventListener('pointerenter',()=>{if(menuIsOpen()&&button.getAttribute('aria-expanded')!=='true')this.openMenu(name,button);});button.addEventListener('keydown',e=>{if(['ArrowDown','Enter',' '].includes(e.key)){e.preventDefault();this.openMenu(name,button);}if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const list=[...this.menubar.children],i=list.indexOf(button);list[(i+(e.key==='ArrowRight'?1:-1)+list.length)%list.length].focus();}if(e.key==='Escape'){e.preventDefault();closeMenu();this.menuReturnFocus?.focus();}});}}
  installWorkspaceNavigation(){this.root.addEventListener('focusin',e=>{for(const p of [this.projectPanel,this.propertiesPanel,this.layoutPanel,this.toolbox,this.debugDock])p.classList.toggle('dock-active',p.contains(e.target));});this.projectTree.tabIndex=0;this.projectTree.addEventListener('keydown',e=>{const rows=[...this.projectTree.querySelectorAll('[role=treeitem]')],active=e.target.closest('[role=treeitem]')||rows.find(r=>r.classList.contains('selected'))||rows[0],index=rows.indexOf(active);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?rows.length-1:Math.max(0,Math.min(rows.length-1,index+(e.key==='ArrowDown'?1:-1)));rows[next].tabIndex=0;rows[next].focus();}else if(e.key==='Enter'){e.preventDefault();active?.click();}else if(['ArrowLeft','ArrowRight'].includes(e.key)&&active?.hasAttribute('aria-expanded')){e.preventDefault();if(active.getAttribute('aria-expanded')!==String(e.key==='ArrowRight'))active.click();}});}
  setProperties(changes){if(this.runState!=='design')return;const module=this.activeModule;if(!module)return;const targets=module.form?(this.designer.selected().length?this.designer.selected():[module.form]):[module],before=clone(this.project);for(const [key,value] of Object.entries(changes))for(const target of targets){target.properties||={};target.properties[key]=value;}this.record(before,'Set properties');}
  layoutSnapshot(){return {right:this.root.style.getPropertyValue('--right-width'),bottom:this.root.style.getPropertyValue('--bottom-height'),project:this.root.style.getPropertyValue('--project-height'),hideToolbox:this.root.classList.contains('hidden-toolbox'),hideProject:this.projectPanel.hidden,hideProperties:this.propertiesPanel.hidden,hideLayout:this.layoutPanel.hidden,hideDebug:this.root.classList.contains('hidden-debug'),appearance:this.appearance,docs:this.docs,activeDoc:this.activeDoc?.key,windows:this.documents.mdi.snapshot(),floating:['project','properties','layout'].map(name=>{const panel=this[name+'Panel'];return {name,floating:panel.classList.contains('panel-floating'),left:panel.style.left,top:panel.style.top,width:panel.style.width,height:panel.style.height};})};}
  restoreLayout(layout){if(!layout)return;this.appearance=normalizeAppearance(layout.appearance);this.savedDocumentLayout=layout;for(const [key,css]of [['right','--right-width'],['bottom','--bottom-height'],['project','--project-height']])if(/^\d+(\.\d+)?px$/.test(layout[key]||''))this.root.style.setProperty(css,layout[key]);this.root.classList.toggle('hidden-toolbox',!!layout.hideToolbox);this.root.classList.toggle('hidden-debug',layout.hideDebug!==false);this.projectPanel.hidden=!!layout.hideProject;this.propertiesPanel.hidden=!!layout.hideProperties;this.layoutPanel.hidden=!!layout.hideLayout;for(const entry of layout.floating||[]){if(!['project','properties','layout'].includes(entry.name))continue;const panel=this[entry.name+'Panel'];panel.classList.toggle('panel-floating',!!entry.floating);if(entry.floating){for(const key of ['left','top','width','height'])if(/^\d+(\.\d+)?px$/.test(entry[key]||''))panel.style[key]=entry[key];}}this.updateDockVisibility();}
  togglePanel(panel,show){if(['properties','project','layout'].includes(panel)){const node=this[panel+'Panel'];node.hidden=show===undefined?!node.hidden:!show;this.updateDockVisibility();if(innerWidth<760&&show!==false)this.root.classList.toggle('show-mobile-properties',!node.hidden);}else this.root.classList.toggle('hidden-'+panel,show===undefined?!this.root.classList.contains('hidden-'+panel):!show);this.autosave();}
  setProperty(key,value){if(this.runState!=='design')return;const module=this.activeModule;if(!module)return;const targets=module.form?(this.designer.selected().length?this.designer.selected():[module.form]):[module],before=clone(this.project);if(key==='Name'){if(targets.length!==1)throw new Error('Select one object to rename.');if(!/^[A-Za-z][A-Za-z0-9_]*$/.test(value)||value.length>40)throw new Error('Use a letter followed by letters, numbers or underscores (maximum 40 characters).');const target=targets[0],old=target.name;if(target===module.form||target===module){if(this.project.modules.some(m=>m.id!==module.id&&lower(m.name)===lower(value)))throw new Error('A module already has that name.');module.name=value;if(module.form){module.form.name=value;module.form.properties.Name=value;}if(lower(this.project.startup)===lower(old))this.project.startup=value;}else{const conflicts=module.form.controls.filter(c=>c.id!==target.id&&lower(c.name)===lower(value));if(conflicts.some(c=>c.properties.Index===undefined||target.properties.Index===undefined||c.properties.Index===target.properties.Index))throw new Error('Duplicate control name. Use distinct Index values to create a control array.');for(const c of module.form.controls)if(c.parent===old)c.parent=value;target.name=value;target.properties.Name=value;}for(const m of this.project.modules)m.code=renameSymbol(m.code,old,value);}
    else {for(const target of targets){target.properties ||= {};if(['Width','Height','ClientWidth','ClientHeight'].includes(key)&&(value<15||value>300000))throw new Error('Size must be between 15 and 300000 twips.');if(value===undefined)delete target.properties[key];else target.properties[key]=value;if(target===module.form){if(key==='Width')target.properties.ClientWidth=Math.max(15,value-120);if(key==='Height')target.properties.ClientHeight=Math.max(15,value-450);if(key==='ClientWidth')target.properties.Width=value+120;if(key==='ClientHeight')target.properties.Height=value+450;}}}this.record(before,'Set '+key);}
  bindLayoutMini(){this.layoutMini.addEventListener('pointerdown',event=>{if(!this.activeModule?.form||this.runState!=='design')return;event.preventDefault();const before=clone(this.project),r=this.layoutScreen.getBoundingClientRect();this.layoutMini.setPointerCapture(event.pointerId);const move=e=>{const x=Math.max(0,Math.min(r.width-15,e.clientX-r.left-15)),y=Math.max(0,Math.min(r.height-12,e.clientY-r.top-7));this.layoutMini.style.left=x+'px';this.layoutMini.style.top=y+'px';Object.assign(this.activeModule.form.properties,{Left:Math.round(x/r.width*15360),Top:Math.round(y/r.height*11520),StartUpPosition:0});};const up=()=>{this.layoutMini.removeEventListener('pointermove',move);this.layoutMini.removeEventListener('pointerup',up);this.record(before,'Set form startup position',false);this.inspector.render();};this.layoutMini.addEventListener('pointermove',move);this.layoutMini.addEventListener('pointerup',up);});}
  updateLayoutMini(){const form=this.activeModule?.form;this.layoutMini.hidden=!form;if(!form)return;const p=form.properties,r=this.layoutScreen;this.layoutMini.style.width=Math.max(16,Math.min(95,p.ClientWidth/15360*r.clientWidth))+'px';this.layoutMini.style.height=Math.max(12,Math.min(55,p.ClientHeight/11520*r.clientHeight))+'px';this.layoutMini.style.left=(p.StartUpPosition?Math.max(2,(r.clientWidth-this.layoutMini.offsetWidth)/2):Math.min(r.clientWidth-20,p.Left/15360*r.clientWidth))+'px';this.layoutMini.style.top=(p.StartUpPosition?Math.max(2,(r.clientHeight-this.layoutMini.offsetHeight)/2):Math.min(r.clientHeight-12,p.Top/11520*r.clientHeight))+'px';}
  async ensureEvent(object,event){if(this.runState!=='design'){this.status('End the running program before editing event handlers.');return;}const module=this.activeModule;if(!module?.form)return;if(object==='Form'&&module.form.type==='MDIForm')object='MDIForm';const control=['Form','MDIForm'].includes(object)?null:module.form.controls.find(c=>c.name===object),name=object+'_'+event;let proc=procedures(module.code).find(p=>lower(p.name)===lower(name));if(!proc){let args=defaultEventSignature(control?.type||'Form',event);if(control?.properties.Index!==undefined)args='Index As Integer'+(args?', '+args:'');const before=clone(this.project);module.code=module.code.trimEnd()+`\n\nPrivate Sub ${name}(${args})\n    \nEnd Sub\n`;this.record(before,'Add '+name,false);proc=procedures(module.code).find(p=>lower(p.name)===lower(name));}this.openDocument(module.id,'code',proc.line+1);this.editor.input.focus();this.editor.goToLine(proc.line+1,5);this.status(name);}
  async eventDialog(object){const c=this.activeModule?.form?.controls.find(c=>c.name===object),events=EVENT_LIST[c?.type||'Form']||[DEFAULT_EVENTS[c?.type]||'Click',...CONTROL_EVENTS],select=el('select',{'aria-label':'Event',size:Math.min(events.length,12),style:{width:'100%'}},...[...new Set(events)].map(event=>el('option',{value:event},event)));select.value=events[0];const accepted=await modal(object+' — Events',{width:300,content:select,buttons:[{label:'View Code',value:true,primary:true},{label:'Cancel',value:false}],onReady:({finish})=>select.addEventListener('dblclick',()=>finish(true))});if(accepted)this.ensureEvent(object,select.value);}
  menu(name){const design=this.runState==='design',hasForm=!!this.activeModule?.form,hasModule=!!this.activeModule,can=(id,label,extra={})=>({id,label,...extra});switch(name){
    case 'File':return [can('new','New Project…',{icon:'new',shortcut:'Ctrl+N',enabled:design}),can('open','Open Project…',{icon:'open',shortcut:'Ctrl+O',enabled:design}),can('openFolder','Open Project Folder…',{enabled:design}),null,can('save','Save Project',{icon:'save',shortcut:'Ctrl+S'}),can('saveAs','Save Project As…'),can('saveModule','Save '+(this.activeModule?.name||'Module')+' As…',{enabled:hasModule}),null,can('exportHTML','Make '+this.project.name+'.html…',{icon:'export',enabled:design}),can('exportSources','Export Source Project (.zip)…'),can('virtualFiles','Project Virtual Files…'),null,can('projectProperties','Project Properties…',{enabled:design}),can('closeProject','Close Project',{enabled:design})];
    case 'Edit':return [can('undo','Undo'+(this.history.undoStack.at(-1)?' '+this.history.undoStack.at(-1).label:''),{icon:'undo',shortcut:'Ctrl+Z',enabled:design&&!!this.history.undoStack.length}),can('redo','Redo',{icon:'redo',shortcut:'Ctrl+Shift+Z',enabled:design&&!!this.history.redoStack.length}),null,can('cut','Cut',{icon:'cut',shortcut:'Ctrl+X',enabled:design}),can('copy','Copy',{icon:'copy',shortcut:'Ctrl+C'}),can('paste','Paste',{icon:'paste',shortcut:'Ctrl+V',enabled:design}),can('delete','Delete',{shortcut:'Del',enabled:design}),can('selectAll','Select All',{shortcut:'Ctrl+A'}),null,can('find','Find…',{icon:'find',shortcut:'Ctrl+F'}),can('replace','Replace…',{shortcut:'Ctrl+H',enabled:design}),can('findNext','Find Next',{shortcut:'F3'}),can('findProject','Find in Project…',{shortcut:'Ctrl+Shift+F'}),can('replaceProject','Replace in Project…',{shortcut:'Ctrl+Shift+H',enabled:design}),{label:'Bookmarks',items:[can('toggleBookmark','Toggle Bookmark',{shortcut:'Ctrl+F2',enabled:hasModule}),can('nextBookmark','Next Bookmark',{shortcut:'Shift+F2'}),can('previousBookmark','Previous Bookmark',{shortcut:'Ctrl+Shift+F2'}),can('clearBookmarks','Clear All Bookmarks')]},can('goTo','Go To Line…',{shortcut:'Ctrl+Shift+G'}),null,can('comment','Comment Block',{enabled:design}),can('uncomment','Uncomment Block',{enabled:design}),can('formatCode','Format Code',{enabled:design}),can('renameSymbol','Rename Symbol…',{enabled:design})];
    case 'View':return [can('viewCode','Code',{icon:'code',shortcut:'F7',enabled:hasModule}),can('viewForm','Object',{icon:'form',shortcut:'Shift+F7',enabled:hasForm}),null,can('objectBrowser','Object Browser',{icon:'object',shortcut:'F2'}),can('immediate','Immediate Window',{shortcut:'Ctrl+G'}),can('locals','Locals Window'),can('watch','Watch Window'),can('callStack','Call Stack',{shortcut:'Ctrl+L'}),can('errors','Error List'),can('output','Output'),null,can('projectExplorer','Project Explorer',{icon:'project',shortcut:'Ctrl+R'}),can('properties','Properties Window',{icon:'properties',shortcut:'F4'}),can('toolbox','Toolbox',{checked:!this.root.classList.contains('hidden-toolbox')}),can('formLayout','Form Layout Window'),null,can('tabOrder','Tab Order',{enabled:hasForm&&design,checked:this.designer.showTabOrder})];
    case 'Project':return this.projectMenu();
    case 'Format':return [{label:'Align',enabled:hasForm&&design,items:[can('align:left','Lefts'),can('align:centerHorizontal','Centers'),can('align:right','Rights'),null,can('align:top','Tops'),can('align:centerVertical','Middles'),can('align:bottom','Bottoms')]},{label:'Make Same Size',enabled:hasForm&&design,items:[can('align:sameWidth','Width'),can('align:sameHeight','Height'),can('align:sameSize','Both')]},can('align:distributeHorizontal','Distribute Horizontally',{enabled:hasForm&&design}),can('align:distributeVertical','Distribute Vertically',{enabled:hasForm&&design}),can('align:centerInForm','Center in Form',{enabled:hasForm&&design}),null,can('align:front','Bring to Front',{enabled:hasForm&&design}),can('align:back','Send to Back',{enabled:hasForm&&design}),null,can('align:snap','Align to Grid',{enabled:hasForm&&design}),can('lockControls','Lock Controls',{checked:this.designer.locked,enabled:hasForm}),can('showGrid','Show Grid',{checked:this.project.settings.showGrid!==false}),can('snapToGrid','Snap to Grid',{checked:this.project.settings.snapToGrid!==false})];
    case 'Debug':return [can('applyEdits','Apply Code Changes',{enabled:this.runState==='paused'}),can('setNextStatement','Set Next Statement',{enabled:this.runState==='paused',shortcut:'Ctrl+F9'}),null,can('stepInto','Step Into',{icon:'step',shortcut:'F8'}),can('stepOver','Step Over',{shortcut:'Shift+F8'}),can('stepOut','Step Out',{shortcut:'Ctrl+Shift+F8',enabled:this.runState==='paused'}),null,can('breakpoint','Toggle Breakpoint',{icon:'breakpoint',shortcut:'F9',enabled:hasModule}),can('conditionalBreakpoint','Breakpoint Condition…',{enabled:hasModule}),can('clearBreakpoints','Clear All Breakpoints',{shortcut:'Ctrl+Shift+F9',enabled:!!this.breakpoints.length}),null,can('addWatch','Add Watch…'),can('quickWatch','Quick Watch…',{shortcut:'Shift+F9',enabled:!design}),can('breakpoints','Breakpoints Window'),null,can('checkSyntax','Check Project Syntax',{enabled:design})];
    case 'Run':return [can('run',this.runState==='paused'?'Continue':'Start',{icon:'run',shortcut:'F5'}),can('startWithBreak','Start with Break',{enabled:design}),can('pause','Break',{icon:'pause',shortcut:'Ctrl+Break',enabled:this.runState==='running'}),can('stop','End',{icon:'stop',shortcut:'Shift+F5',enabled:!design}),null,can('showRuntime','Bring Application to Front',{enabled:!design})];
    case 'Tools':return [can('menuEditor','Menu Editor…',{enabled:hasForm&&design}),can('components','Components…'),can('references','References…'),null,can('options','Options…'),can('virtualFiles','Virtual File System…')];
    case 'Window':return [can('cascade','&Cascade'),can('tileHorizontal','Tile &Horizontally'),can('tileVertical','Tile &Vertically'),can('tile','Tile Code and Designer',{enabled:hasForm}),can('closeAll','Close All Windows',{enabled:!!this.documents.mdi.windows.size}),null,can('resetLayout','Reset Window Layout'),can('fullScreen','Full Screen'),null,...this.docs.map(d=>({label:(findModule(this.project,d.id)?.name||'Document')+(d.view==='form'?' (Form)':' (Code)'),checked:d.key===this.activeDoc?.key,action:()=>this.openDocument(d.id,d.view)})),...Array.from(this.documents.tools.values(),t=>({label:t.title,checked:this.documents.mdi.active===t.key,action:()=>this.documents.openTool(t)}))];
    case 'Help':return [can('help','Contents and Keyboard Reference',{icon:'help',shortcut:'F1'}),can('samples','Sample Projects…'),can('compatibility','Language and Runtime Support'),null,can('about','About Visual Basic Browser Studio…')];default:return [];}}
  projectMenu(){const design=this.runState==='design';return [{label:'Add Form',id:'addForm',icon:'form',enabled:design},{label:'Add MDI Form',id:'addMDIForm',icon:'form',enabled:design&&!this.project.modules.some(m=>m.form?.type==='MDIForm')},{label:'Add Module',id:'addModule',icon:'module',enabled:design},{label:'Add Class Module',id:'addClass',icon:'class',enabled:design},{label:'Add Existing Files…',id:'addFiles',enabled:design},null,{label:'Components…',id:'components'},{label:'References…',id:'references'},null,{label:this.project.name+' Properties…',id:'projectProperties',enabled:design}];}
  designerMenu(){return [{label:'View Code',id:'viewCode',icon:'code',shortcut:'F7'},{label:'Edit Default Event',id:'defaultEvent'},{label:'Properties',id:'properties',icon:'properties',shortcut:'F4'},null,{label:'Cut',id:'cut',icon:'cut'},{label:'Copy',id:'copy',icon:'copy'},{label:'Paste',id:'paste',icon:'paste'},{label:'Delete',id:'delete',icon:'delete'},null,{label:'Bring to Front',id:'align:front'},{label:'Send to Back',id:'align:back'},null,{label:'Menu Editor…',id:'menuEditor'}];}
  openMenu(name,button){const r=button.getBoundingClientRect();showMenu(this.menu(name),r.left,r.bottom,id=>this.command(id),{opener:button,focusFirst:true,onSwitch:direction=>{const buttons=[...this.menubar.children],index=buttons.indexOf(button),next=buttons[(index+direction+buttons.length)%buttons.length];this.openMenu(next.dataset.menu,next);}});}
  async command(id){try{closeMenu();if(id.startsWith('align:')){if(this.runState==='design')this.designer.align(id.slice(6));return;}switch(id){
    case 'new':case 'samples':return this.newProjectDialog();case 'open':if(await this.confirmDiscard()){this.addingFiles=false;this.fileInput.click();}return;case 'openFolder':return this.openFolder();case 'addFiles':this.addingFiles=true;this.fileInput.click();return;
    case 'save':return this.saveProject();case 'saveAs':{const name=await promptDialog('Save Project As','Project name:',this.project.name);if(name!==null){const before=clone(this.project);this.project.name=safeName(name);this.record(before,'Rename project');this.saveProject();}return;}
    case 'saveModule':{const module=this.activeModule;if(!module)return;const files=sourceFiles({...this.project,modules:[module],assets:{}}),name=module.name+'.'+(module.kind==='form'?'frm':module.kind==='class'?'cls':'bas');download(name,files[name],'text/plain');this.status('Saved '+name);return;}
    case 'exportHTML':{const start=performance.now(),html=exportApplication(this.project);download(safeName(this.project.name)+'.html',html,'text/html');this.status('Made '+this.project.name+'.html — '+Math.round(new Blob([html]).size/1024)+' KB, '+Math.round(performance.now()-start)+' ms.');this.emit('export',{kind:'html',html});return;}
    case 'exportSources':{const files=sourceFiles(this.project);files[this.project.name+'.vb6web']=JSON.stringify(this.project,null,2);files['README.txt']='VB6 Studio Web source export\n\nOpen the .vb6web file for lossless browser-project restoration.\nThe .vbp/.frm/.bas/.cls files are source interchange, not a Windows binary build.\nFRX binary resources and OCX state are not reconstructed.\n';download(safeName(this.project.name)+'-sources.zip',writeZip(files),'application/zip');this.status('Exported native-style source and lossless browser project.');return;}
    case 'closeProject':if(await this.confirmDiscard())this.loadProject(newProject());return;
    case 'undo':case 'redo':if(this.runState==='design'){const result=this.history[id](this.project);if(result){this.project=normalizeProject(result);this.docs=this.docs.filter(d=>findModule(this.project,d.id));if(!this.docs.length&&this.project.modules.length)this.openDocument(this.project.modules[0].id,this.project.modules[0].form?'form':'code');else if(!this.docs.some(d=>d.key===this.activeDoc?.key))this.activeDoc=this.docs[0];this.markDirty();this.renderAll();}}return;
    case 'cut':case 'copy':case 'paste':case 'delete':case 'selectAll':if(this.activeDoc?.view==='code'){this.editor.edit(id);}else if(this.activeModule?.form){if(id==='delete')this.designer.deleteSelected();else if(id==='selectAll')this.designer.select(this.activeModule.form.controls.map(c=>c.id));else this.designer[id]();}return;
    case 'viewCode':if(this.activeModule)this.openDocument(this.activeModule.id,'code');return;case 'viewForm':if(this.activeModule?.form)this.openDocument(this.activeModule.id,'form');return;
    case 'findProject':return this.projectSearch();case 'replaceProject':return this.projectSearch(true);case 'toggleBookmark':return this.toggleBookmark();case 'nextBookmark':return this.nextBookmark(1);case 'previousBookmark':return this.nextBookmark(-1);case 'clearBookmarks':return this.clearBookmarks();
    case 'find':case 'replace':if(this.activeModule){this.openDocument(this.activeModule.id,'code');this.editor.showFind(id==='replace');}return;case 'findNext':this.editor.find(1);return;
    case 'goTo':{const result=await promptDialog('Go To Line','Line number:',String(this.editor.cursor().line));if(result!==null&&Number.isFinite(Number(result))){this.openDocument(this.activeModule.id,'code');this.editor.goToLine(Number(result));}return;}
    case 'comment':case 'uncomment':case 'formatCode':if(this.activeModule){this.openDocument(this.activeModule.id,'code');this.editor.edit(id==='formatCode'?'format':id);}return;
    case 'renameSymbol':{const a=this.editor.input.selectionStart,oldWord=this.editor.input.value.slice(0,a).match(/[A-Za-z_]\w*$/)?.[0]||'',old=await promptDialog('Rename Symbol','Existing identifier:',oldWord);if(!old||!/^\w+$/.test(old))return;const name=await promptDialog('Rename Symbol','New identifier:',old);if(!name)return;if(!/^[A-Za-z_]\w*$/.test(name))throw new Error('Invalid identifier.');const before=clone(this.project);for(const module of this.project.modules)module.code=renameSymbol(module.code,old,name);this.record(before,'Rename symbol '+old);this.status('Renamed source identifiers; strings and comments were preserved.');return;}
    case 'addMDIForm':{if(this.runState!=='design'||this.project.modules.some(m=>m.form?.type==='MDIForm'))return;const before=clone(this.project),module=createForm(uniqueName(this.project,'MDIForm'));module.form.type='MDIForm';module.form.originalType='VB.MDIForm';module.form.properties.ClientWidth=12600;module.form.properties.ClientHeight=8400;module.code=module.code.replace(/Form_Load/g,'MDIForm_Load');this.project.modules.push(module);this.record(before,'Add MDI Form',false);this.openDocument(module.id,'form');return;}
    case 'addForm':case 'addModule':case 'addClass':{if(this.runState!=='design')return;const kind=id==='addForm'?'form':id==='addClass'?'class':'module',base=kind==='form'?'Form':kind==='class'?'Class':'Module',name=uniqueName(this.project,base),before=clone(this.project),module=kind==='form'?createForm(name):{id:newId(),name,kind,code:this.appearance.requireVariableDeclaration?'Option Explicit\n\n':'\n'};if(kind==='form'&&!this.appearance.requireVariableDeclaration)module.code=module.code.replace(/^Option Explicit\n+/i,'');this.project.modules.push(module);this.record(before,'Add '+name,false);this.openDocument(module.id,kind==='form'?'form':'code');return;}
    case 'removeModule':{const module=this.activeModule;if(!module)return;if(this.project.modules.length===1)throw new Error('A project must contain at least one module.');const yes=await modal('Remove '+module.name,{content:el('p',{},'Remove this module from the project? This operation can be undone.'),buttons:[{label:'Remove',value:true,primary:true},{label:'Cancel',value:false}]});if(!yes)return;const before=clone(this.project);this.project.modules=this.project.modules.filter(m=>m.id!==module.id);this.docs=this.docs.filter(d=>d.id!==module.id);this.activeDoc=this.docs[0];if(this.project.startup===module.name)this.project.startup=this.project.modules.find(m=>m.form)?.name||'Sub Main';this.record(before,'Remove '+module.name,false);if(!this.activeDoc)this.openDocument(this.project.modules[0].id,this.project.modules[0].form?'form':'code');this.renderAll();return;}
    case 'renameModule':{const name=await promptDialog('Rename Module','Name:',this.activeModule?.name||'');if(name!==null){this.designer.selection.clear();this.setProperty('Name',name);}return;}
    case 'defaultEvent':{const control=this.designer.selected()[0];return this.ensureEvent(control?.name||'Form',DEFAULT_EVENTS[control?.type||'Form']||'Click');}
    case 'projectProperties':return this.projectProperties();case 'menuEditor':return this.menuEditor();case 'components':return this.componentsDialog();case 'references':return this.referencesDialog();case 'options':return this.optionsDialog();case 'objectBrowser':return this.objectBrowser();case 'virtualFiles':return this.virtualFiles();
    case 'projectExplorer':this.togglePanel('project',true);this.projectTree.focus();return;case 'properties':this.togglePanel('properties',true);this.inspector.object.focus();return;case 'toolbox':this.togglePanel('toolbox');return;case 'formLayout':this.togglePanel('layout',true);return;case 'toggleFolders':this.noFolders=!this.noFolders;this.renderProjectTree();return;
    case 'immediate':this.showDebug('Immediate');this.immediateInput?.focus();return;case 'locals':this.showDebug('Locals');return;case 'watch':this.showDebug('Watch');return;case 'callStack':this.showDebug('Call Stack');return;case 'errors':this.showDebug('Errors');return;case 'output':this.showDebug('Output');return;case 'breakpoints':this.showDebug('Breakpoints');return;
    case 'showGrid':case 'snapToGrid':{const before=clone(this.project);this.project.settings[id]=!this.project.settings[id];this.record(before,id);return;}
    case 'lockControls':this.designer.locked=!this.designer.locked;this.status(this.designer.locked?'Controls locked.':'Controls unlocked.');return;case 'tabOrder':if(this.activeModule?.form){this.openDocument(this.activeModule.id,'form');this.designer.showTabOrder=!this.designer.showTabOrder;this.designer.tabOrderIndex=0;this.designer.renderSelection();this.status('Click controls in the desired Tab order. Press Escape to finish.');}return;
    case 'tile':if(this.activeModule?.form){const id=this.activeModule.id;this.openDocument(id,'form');this.openDocument(id,'code');}this.documents.mdi.arrange('vertical');return;case 'cascade':this.documents.mdi.arrange('cascade');return;case 'tileHorizontal':this.documents.mdi.arrange('horizontal');return;case 'tileVertical':this.documents.mdi.arrange('vertical');return;case 'closeAll':for(const key of [...this.documents.mdi.windows.keys()])this.closeDocument(key);return;case 'resetLayout':this.root.removeAttribute('style');this.root.className='ide-shell hidden-debug';for(const panel of [this.projectPanel,this.propertiesPanel,this.layoutPanel]){panel.hidden=false;panel.classList.remove('panel-floating');panel.removeAttribute('style');}this.updateDockVisibility();this.documents.mdi.arrange('cascade');this.applyAppearance();this.autosave();return;
    case 'fullScreen':if(document.fullscreenElement)await document.exitFullscreen();else await this.root.requestFullscreen();return;
    case 'applyEdits':await this.applyCodeChanges();return;
    case 'setNextStatement':if(this.runState==='paused'){const target={module:this.activeModule.name,line:this.editor.cursor().line};await this.applyCodeChanges();await this.requestRuntime('setNextStatement',target);}return;
    case 'run':if(this.runState==='paused'){await this.applyCodeChanges();this.sendRuntime('resume');this.editor.setExecution(null);this.runtimeWindow?.classList.remove('minimized');}else if(this.runState==='design')this.run();else this.runtimeWindow?.classList.remove('minimized');return;
    case 'startWithBreak':return this.run(true);case 'pause':this.sendRuntime('pause');return;case 'stop':return this.stop();case 'showRuntime':this.runtimeWindow?.classList.remove('minimized');return;
    case 'stepInto':case 'stepOver':case 'stepOut':if(this.runState==='design')this.run(true);else if(this.runState==='paused'){await this.applyCodeChanges();this.sendRuntime('resume',{mode:id==='stepInto'?'into':id==='stepOver'?'over':'out'});this.editor.setExecution(null);}return;
    case 'breakpoint':if(this.activeModule){this.toggleBreakpoint(this.activeModule.name,this.editor.cursor().line);this.openDocument(this.activeModule.id,'code');}return;
    case 'conditionalBreakpoint':{const module=this.activeModule?.name,line=this.editor.cursor().line;if(!module)return;const current=this.breakpoints.find(b=>lower(b.module)===lower(module)&&b.line===line),condition=await promptDialog('Breakpoint Condition','Break when this expression is True. Leave blank to break unconditionally.',current?.condition||'');if(condition!==null){if(current)current.condition=condition;else this.breakpoints.push({module,line,condition});this.syncBreakpoints();}return;}
    case 'clearBreakpoints':this.breakpoints=[];this.syncBreakpoints();return;case 'addWatch':{const text=await promptDialog('Add Watch','Expression:','');if(text?.trim()){this.watches.push(text.trim());this.updateWatches();this.showDebug('Watch');this.autosave();}return;}
    case 'quickWatch':{const text=await promptDialog('Quick Watch','Expression:',this.editor.input.value.slice(this.editor.input.selectionStart,this.editor.input.selectionEnd));if(text?.trim()){this.watches.push(text.trim());this.updateWatches();this.showDebug('Watch');}return;}
    case 'checkSyntax':{const compiled=this.checkSyntax();if(compiled.valid)this.status('Syntax check passed — '+compiled.modules.size+' modules. Runtime-dependent behavior is checked when executed.');return;}
    case 'help':return this.helpDialog();case 'about':return this.aboutDialog();case 'compatibility':return this.compatibilityDialog();
    default:this.status('Command not available: '+id);}
  }catch(error){this.status('Error: '+error.message);await alertDialog(error.message,'Visual Basic Browser Studio');}}
  keydown(event){if(event.key!=='Alt')this.altCandidate=false;if(event.defaultPrevented)return;const modalOpen=hasUIDialog();if(modalOpen)return;const ctrl=event.ctrlKey||event.metaKey,key=event.key.toLowerCase();let command=null;if(ctrl&&['z','y'].includes(key)&&event.target.closest('.classic-object-browser input,.project-search-window input'))return;if(ctrl&&event.key==='F4'){event.preventDefault();this.closeDocument();return;}if(ctrl&&['F6','Tab'].includes(event.key)){event.preventDefault();this.documents.mdi.cycle(event.shiftKey?-1:1);return;}if(ctrl&&event.key==='F10'){event.preventDefault();const w=this.documents.mdi.windows.get(this.documents.mdi.active||this.activeDoc?.key);if(w)this.documents.mdi.maximize(w.key);return;}if(event.key==='Alt'){this.altCandidate=true;event.preventDefault();return;}if(event.key==='F10'){event.preventDefault();this.menuReturnFocus=document.activeElement;this.menubar.firstElementChild.focus();return;}if(event.altKey&&!ctrl&&key.length===1){const names={f:'File',e:'Edit',v:'View',p:'Project',o:'Format',d:'Debug',r:'Run',t:'Tools',w:'Window',h:'Help'},name=names[key];if(name){event.preventDefault();this.openMenu(name,this.menubar.querySelector('[data-menu="'+name+'"]'));return;}}
    if(event.key==='F1')command='help';if(event.key==='F2')command=ctrl&&event.shiftKey?'previousBookmark':ctrl?'toggleBookmark':event.shiftKey?'nextBookmark':'objectBrowser';if(event.key==='F4')command='properties';if(event.key==='F5')command=event.shiftKey?'stop':'run';if(event.key==='F7')command=event.shiftKey?'viewForm':'viewCode';if(event.key==='F8')command=ctrl&&event.shiftKey?'stepOut':event.shiftKey?'stepOver':'stepInto';if(event.key==='F9')command=ctrl&&event.shiftKey?'clearBreakpoints':ctrl?'setNextStatement':event.shiftKey?'quickWatch':'breakpoint';if(ctrl&&event.key==='Pause')command='pause';if(ctrl){const map={n:'new',o:'open',s:event.shiftKey?'saveAs':'save',r:'projectExplorer',g:event.shiftKey?'goTo':'immediate',l:'callStack',z:event.shiftKey?'redo':'undo',y:'redo'};command ||= map[key];if(['f','h'].includes(key)&&!event.target.closest('.editor-find'))command=event.shiftKey?(key==='f'?'findProject':'replaceProject'):(key==='f'?'find':'replace');}if(command){event.preventDefault();this.command(command);}}
  async confirmDiscard(){if(!this.dirty)return true;const result=await modal('Visual Basic',{content:el('p',{},'Save changes to '+this.project.name+'?'),buttons:[{label:'Save',value:'save',primary:true},{label:'Discard',value:'discard'},{label:'Cancel',value:false}]});if(result==='save')this.saveProject();return !!result;}
  saveProject(){this.rememberProject();download(safeName(this.project.name)+'.vb6web',JSON.stringify(this.project,null,2),'application/json');this.savedJSON=JSON.stringify(this.project);this.dirty=false;this.persist();this.updateTitle();this.status('Saved '+this.project.name+'.vb6web');}
  async importBrowserFiles(files,{add=false}={}){if(!files.length)return;try{if(!add&&this.dirty&&!await this.confirmDiscard())return;const entries=new Map();for(const file of files){if(file.size>50*1024*1024)throw new Error('File exceeds the 50 MiB import limit.');const bytes=new Uint8Array(await file.arrayBuffer());if(/\.zip$/i.test(file.name)){for(const entry of await readZip(bytes))entries.set(...entry);}else entries.set(file.webkitRelativePath||file.name,bytes);}const result=await importFiles(entries);if(add){const before=clone(this.project);for(const module of result.project.modules){if(this.project.modules.some(m=>lower(m.name)===lower(module.name)))throw new Error('A module named '+module.name+' already exists.');}this.project.modules.push(...result.project.modules);Object.assign(this.project.assets,result.project.assets);this.record(before,'Add existing source files');}else this.loadProject(result.project);this.diagnostics=result.diagnostics;this.editor.setDiagnostics(this.diagnostics);if(this.diagnostics.length)this.showDebug('Errors');this.status('Opened '+this.project.name+(this.diagnostics.length?' — review import diagnostics.':'.'));}catch(error){await alertDialog(error.message,'Open Project');}}
  async openFolder(){const document=uiDocument(),window=document.defaultView;if('showDirectoryPicker' in window){try{const handle=await window.showDirectoryPicker({mode:'read'}),files=[];const walk=async(dir,depth=0,prefix='')=>{if(depth>8)throw new Error('Folder nesting limit exceeded.');for await(const item of dir.values()){if(files.length>2000)throw new Error('Folder contains too many files.');if(item.kind==='directory'&&!['node_modules','.git','dist'].includes(item.name))await walk(item,depth+1,prefix+item.name+'/');else if(item.kind==='file'&&/\.(vb6web|vbp|frm|bas|cls|frx|png|jpg|bmp|gif|ico)$/i.test(item.name)){const file=await item.getFile();files.push({name:file.name,size:file.size,webkitRelativePath:prefix+file.name,arrayBuffer:()=>file.arrayBuffer()});}}};await walk(handle);return this.importBrowserFiles(files);}catch(error){if(error.name==='AbortError')return;throw error;}}const input=el('input',{type:'file',webkitdirectory:true,multiple:true,hidden:true});document.body.append(input);input.addEventListener('change',()=>{this.importBrowserFiles([...input.files]);input.remove();});input.click();}
  rememberProject(){try{const json=JSON.stringify(this.project);if(json.length>500000)return;const previous=JSON.parse(localStorage.getItem('vb6-studio-web.recent.v1')||'[]').filter(p=>p&&p.id!==this.project.id);localStorage.setItem('vb6-studio-web.recent.v1',JSON.stringify([this.project,...previous].slice(0,5)));}catch{}}
  async newProjectDialog(){if(!await this.confirmDiscard())return;const options=[{id:'blank',name:'Standard EXE',description:'A blank form-based browser application.',create:()=>newProject()},...EXAMPLES],grid=el('div',{class:'template-grid',role:'listbox','aria-label':'New project templates'}),description=el('div',{class:'template-description'});let chosen=options[0],finish;
    const select=option=>{chosen=option;grid.querySelectorAll('button').forEach(b=>{const yes=b.dataset.template===option.id;b.classList.toggle('selected',yes);b.setAttribute('aria-selected',String(yes));b.tabIndex=yes?0:-1;});description.textContent=option.description;};for(const option of options)grid.append(el('button',{class:'template-option',role:'option','data-template':option.id,onclick:()=>select(option),ondblclick:()=>finish?.('new')},icon(option.id==='language'?'module':'form',32),option.name));select(chosen);grid.addEventListener('keydown',e=>{const i=options.indexOf(chosen),delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-3,ArrowDown:3}[e.key];if(delta){e.preventDefault();select(options[Math.max(0,Math.min(options.length-1,i+delta))]);grid.querySelector('[aria-selected=true]').focus();}if(e.key==='Enter'){e.preventDefault();e.stopPropagation();finish?.('new');}});
    let recent=[];try{recent=JSON.parse(localStorage.getItem('vb6-studio-web.recent.v1')||'[]').filter(p=>p&&p.modules&&p.name).slice(0,5);}catch{}const recentList=el('div',{class:'recent-projects',role:'listbox','aria-label':'Recent browser snapshots'});recent.forEach((project,i)=>recentList.append(el('button',{class:'recent-project',ondblclick:()=>finish?.({recent:i}),onclick:()=>{for(const row of recentList.children)row.classList.remove('selected');recentList.children[i].classList.add('selected');recentList.dataset.index=String(i);}},icon('project'),project.name,el('small',{},'Browser snapshot'))));if(!recent.length)recentList.append(el('p',{},'No recent browser snapshots.'));
    let contentTab='new';const content=tabbedPages([{id:'new',label:'New',node:el('div',{},grid,description)},{id:'existing',label:'Existing',node:el('div',{class:'existing-project'},el('p',{},'Open a saved .vb6web project, a source ZIP, or a .vbp with its companion source and resource files.'),el('button',{onclick:()=>finish?.('browse')},'Browse…'))},{id:'recent',label:'Recent',node:el('div',{},recentList,el('p',{class:'option-note'},'These are saved browser snapshots, not live links to files on your computer.'))}],{onSelect:id=>contentTab=id});
    const result=await modal('New Project',{width:540,content,onReady:context=>finish=context.finish,buttons:[{label:'Open',value:'new',primary:true,action:()=>{if(contentTab==='existing'){finish('browse');return false;}if(contentTab==='recent'){const i=Number(recentList.dataset.index);if(!Number.isInteger(i)||!recent[i])return false;finish({recent:i});return false;}}},{label:'Cancel',value:false}]});if(result==='browse')this.fileInput.click();else if(result?.recent!==undefined)this.loadProject(recent[result.recent]);else if(result)this.loadProject(chosen.create());}

  async projectProperties(){const project=this.project,name=el('input',{value:project.name}),description=el('input',{value:project.description||''}),startup=el('select',{},el('option',{value:'Sub Main'},'Sub Main'),...project.modules.filter(m=>m.form).map(m=>el('option',{value:m.name},m.name)));startup.value=project.startup;const body=el('div',{class:'dialog-grid'},el('label',{},'Project Name:'),name,el('label',{},'Project Description:'),description,el('label',{},'Startup Object:'),startup,el('label',{},'Project Type:'),el('span',{},'Browser application (standalone HTML)'));const yes=await modal(project.name+' — Project Properties',{width:540,content:body});if(yes){const before=clone(project);project.name=safeName(name.value);project.description=description.value;project.startup=startup.value;this.record(before,'Project properties');}}
  async menuEditor(){const module=this.activeModule;if(!module?.form)return;const original=clone(module.form.menus||[]),menus=clone(original),list=el('div',{class:'menu-editor-list'}),fields=el('div',{class:'menu-editor-fields'}),name=el('input',{'aria-label':'Menu name'}),caption=el('input',{'aria-label':'Menu caption'}),parent=el('select',{'aria-label':'Parent menu'}),enabled=el('input',{type:'checkbox'}),checked=el('input',{type:'checkbox'}),visible=el('input',{type:'checkbox'}),windowList=el('input',{type:'checkbox','aria-label':'WindowList'});let selected=menus[0]||null;fields.append(el('label',{},'Caption:',caption),el('label',{},'Name:',name),el('label',{},'Parent:',parent),el('label',{},enabled,'Enabled'),el('label',{},checked,'Checked'),el('label',{},visible,'Visible'),el('label',{},windowList,'WindowList'));const depth=item=>{let n=0,current=item;const seen=new Set();while(current.parent&&n<10){if(seen.has(current.parent))break;seen.add(current.parent);current=menus.find(m=>m.name===current.parent)||{};n++;}return n;};
    const render=()=>{list.replaceChildren(...menus.map(item=>el('div',{class:'menu-editor-row'+(selected?.id===item.id?' selected':''),style:{paddingLeft:5+depth(item)*16+'px'},onclick:()=>{try{commit();selected=item;render();}catch(error){alertDialog(error.message,'Menu Editor');}}},item.properties.Caption||item.name)));name.value=selected?.name||'';caption.value=selected?.properties.Caption||'';parent.replaceChildren(el('option',{value:''},'(Top level)'),...menus.filter(m=>m.id!==selected?.id).map(m=>el('option',{value:m.name},m.name)));parent.value=selected?.parent||'';enabled.checked=selected?.properties.Enabled!==0;checked.checked=!!selected?.properties.Checked;visible.checked=selected?.properties.Visible!==0;windowList.checked=!!selected?.properties.WindowList;for(const input of fields.querySelectorAll('input,select'))input.disabled=!selected;};
    const commit=()=>{if(!selected)return;const proposed=name.value.trim();if(!/^[A-Za-z_]\w*$/.test(proposed)||menus.some(m=>m.id!==selected.id&&lower(m.name)===lower(proposed)))throw new Error('Menu names must be valid, unique identifiers.');const old=selected.name;for(const item of menus)if(item.parent===old)item.parent=proposed;selected.name=proposed;selected.parent=parent.value===old?proposed:parent.value||null;Object.assign(selected.properties,{Caption:caption.value,Enabled:enabled.checked?-1:0,Checked:checked.checked?-1:0,Visible:visible.checked?-1:0,WindowList:windowList.checked?-1:0});let current=selected;const seen=new Set([current.name]);while(current.parent){if(seen.has(current.parent))throw new Error('A menu cannot be its own ancestor.');seen.add(current.parent);current=menus.find(m=>m.name===current.parent)||{};}};
    const actions=el('div',{class:'menu-editor-actions'});for(const [label,action]of [['Add',()=>{commit();let index=1;while(menus.some(m=>m.name==='mnuItem'+index))index++;const item={id:newId(),name:'mnuItem'+index,type:'Menu',parent:selected?.parent||null,properties:{Caption:'New item',Enabled:-1,Visible:-1}};menus.push(item);selected=item;render();}],['Child',()=>{commit();let index=1;while(menus.some(m=>m.name==='mnuItem'+index))index++;const item={id:newId(),name:'mnuItem'+index,type:'Menu',parent:selected?.name||null,properties:{Caption:'New item',Enabled:-1,Visible:-1}};menus.splice(selected?menus.indexOf(selected)+1:menus.length,0,item);selected=item;render();}],['Delete',()=>{if(!selected)return;const names=new Set([selected.name]);for(let i=0;i<menus.length;i++)for(const item of menus)if(names.has(item.parent))names.add(item.name);for(let i=menus.length-1;i>=0;i--)if(names.has(menus[i].name))menus.splice(i,1);selected=menus[0]||null;render();}],['↑',()=>{commit();const i=menus.indexOf(selected);if(i>0)[menus[i],menus[i-1]]=[menus[i-1],menus[i]];render();}],['↓',()=>{commit();const i=menus.indexOf(selected);if(i>=0&&i<menus.length-1)[menus[i],menus[i+1]]=[menus[i+1],menus[i]];render();}]])actions.append(el('button',{onclick:()=>{try{action();}catch(error){alertDialog(error.message,'Menu Editor');}}},label));render();const yes=await modal('Menu Editor — '+module.name,{width:650,content:el('div',{},el('div',{class:'menu-editor-grid'},el('div',{},list,actions),fields),el('p',{},'Use & for a mnemonic and a single hyphen for a separator. Menu events use Name_Click.')),buttons:[{label:'OK',value:true,primary:true,action:async()=>{try{commit();return true;}catch(error){await alertDialog(error.message,'Menu Editor');return false;}}},{label:'Cancel',value:false}]});if(yes){const before=clone(this.project);module.form.menus=menus;for(const item of menus){const old=original.find(m=>m.id===item.id);if(old&&old.name!==item.name)module.code=renameSymbol(module.code,old.name,item.name);}this.record(before,'Edit menus');}}
  async componentsDialog(){const list=el('div',{class:'dialog-list'});for(const type of EXTENDED_CONTROL_TYPES)list.append(el('label',{},controlIcon(type),el('span',{},type+' — browser implementation')));await modal('Components',{width:515,content:el('div',{},el('p',{},'The following source-based control adapters are included. They do not load or register Windows OCX binaries.'),list),buttons:[{label:'Show Controls',value:true,primary:true,action:()=>{this.toolboxMode='extended';this.toolboxFilter.value='extended';this.renderToolbox();this.togglePanel('toolbox',true);}},{label:'Close',value:false}]});}
  async referencesDialog(){const body=el('div',{},el('p',{},'Available browser libraries'),el('div',{class:'dialog-list'},...['Visual Basic runtime library — implemented subset','Scripting.Dictionary — in-memory dictionary','Scripting.FileSystemObject — project-private text files','ADODB.Recordset — in-memory fields and records'].map(text=>el('label',{},el('input',{type:'checkbox',checked:true,disabled:true}),text))));if(this.project.references.length){body.append(el('p',{},'Retained native project references (not loaded in the browser):'),el('div',{class:'dialog-list'},...this.project.references.map(r=>el('p',{style:{overflowWrap:'anywhere'}},r.value))));}body.append(el('p',{},'COM servers, arbitrary DLL calls, native database drivers and Windows ActiveX binaries are not provided by these adapters.'));await modal('References — '+this.project.name,{width:600,content:body,buttons:[{label:'Close',value:true,primary:true}]});}
  async optionsDialog(){
    const setting=this.project.settings,check=(label,value)=>{const input=el('input',{type:'checkbox',checked:value});return {input,node:el('label',{class:'option-check'},input,label)};},field=(text,input)=>el('label',{class:'option-field'},el('span',{},text),input);
    const indent=check('Auto Indent',this.appearance.autoIndent),complete=check('Auto List Members',this.appearance.autoListMembers),separators=check('Procedure Separator',this.appearance.procedureSeparators),numbers=check('Show line numbers (browser extension)',setting.lineNumbers),snap=check('Align Controls to Grid',setting.snapToGrid!==false),show=check('Show Grid',setting.showGrid!==false),tips=check('Show ToolTips',this.appearance.tooltips),docTabs=check('Show document tabs (browser extension)',this.appearance.documentTabs),debugTabs=check('Show debug-window tabs (browser extension)',this.appearance.debugTabs);
    const tab=el('select',{'aria-label':'Tab Width'},...[2,4,8].map(n=>el('option',{value:n},String(n)))),font=el('select',{'aria-label':'Editor Font'},...['Courier New','Consolas','monospace'].map(n=>el('option',{value:n},n))),size=el('select',{'aria-label':'Editor Size'},...[11,12,13,14,16,18,20].map(n=>el('option',{value:n},n+' px'))),theme=el('select',{'aria-label':'IDE theme'},...Object.entries(THEMES).map(([id,t])=>el('option',{value:id},t.name))),appTheme=el('select',{'aria-label':'Application theme'},...Object.entries(THEMES).map(([id,t])=>el('option',{value:id},t.name))),grid=el('input',{type:'number','aria-label':'Grid size in twips',value:setting.gridSize||120,min:15,max:1200,step:15}),backend=el('select',{'aria-label':'Graphics renderer'},el('option',{value:'auto'},'WebGPU with Canvas2D fallback'),el('option',{value:'canvas2d'},'Canvas2D'));
    tab.value=setting.tabWidth||4;font.value=this.appearance.editorFont;size.value=this.appearance.editorSize;theme.value=this.appearance.theme;appTheme.value=setting.theme||'classic';backend.value=setting.renderer||'auto';
    const sample=el('pre',{class:'editor-format-sample'},el('span',{class:'tok-keyword'},'Private Sub '),'Command1_Click()\n',el('span',{class:'tok-comment'},"    ' Sample text"),'\n    MsgBox "Hello"\n',el('span',{class:'tok-keyword'},'End Sub'));
    const refresh=()=>{applyTheme(sample,theme.value);sample.style.fontFamily='"'+font.value+'", monospace';sample.style.fontSize=size.value+'px';sample.style.lineHeight=(Number(size.value)+4)+'px';};for(const node of [font,size,theme])node.addEventListener('change',refresh);refresh();
    const group=(name,...nodes)=>el('fieldset',{class:'options-group'},el('legend',{},name),...nodes),editor=el('div',{},group('Code Settings',complete.node,indent.node,field('Tab Width:',tab)),group('Window Settings',separators.node,numbers.node)),format=el('div',{},field('Font:',font),field('Size:',size),el('fieldset',{class:'options-group'},el('legend',{},'Sample'),sample),el('p',{class:'option-note'},'Fonts use local system installations. No Microsoft font files are embedded or downloaded.')),general=el('div',{},group('Form Grid Settings',show.node,snap.node,field('Width / Height (twips):',grid)),group('Display',field('IDE theme:',theme),field('Application theme:',appTheme),tips.node,el('p',{class:'option-note'},'System colors follow the selected theme. Authored RGB colors are preserved.')),group('Rendering',field('Graphics renderer:',backend)));
    const visibility=[['project','Project Explorer'],['properties','Properties Window'],['layout','Form Layout Window'],['toolbox','Toolbox'],['debug','Immediate / Debug Window']].map(([id,label])=>{const visible=['project','properties','layout'].includes(id)?!this[id+'Panel'].hidden:!this.root.classList.contains('hidden-'+id);return {id,...check(label,visible)};});const docking=el('div',{},group('Visible Windows',...visibility.map(v=>v.node)),el('p',{class:'option-note'},'Double-click a docked title bar to float a window. Double-click again to dock it. Use the splitters or their arrow keys to resize panes.'),group('Browser Workspace',docTabs.node,debugTabs.node));
    const content=tabbedPages([{id:'editor',label:'Editor',node:editor},{id:'format',label:'Editor Format',node:format},{id:'general',label:'General',node:general},{id:'docking',label:'Docking',node:docking}]);
    const apply=()=>{const value=Number(grid.value);if(!Number.isFinite(value)||value<15||value>1200)throw new Error('Grid size must be between 15 and 1200 twips.');const before=clone(this.project);Object.assign(setting,{snapToGrid:snap.input.checked,showGrid:show.input.checked,gridSize:value,tabWidth:Number(tab.value),renderer:backend.value,lineNumbers:numbers.input.checked,theme:appTheme.value});this.appearance=normalizeAppearance({theme:theme.value,editorFont:font.value,editorSize:Number(size.value),tooltips:tips.input.checked,autoIndent:indent.input.checked,autoListMembers:complete.input.checked,procedureSeparators:separators.input.checked,documentTabs:docTabs.input.checked,debugTabs:debugTabs.input.checked});for(const v of visibility)this.togglePanel(v.id,v.input.checked);this.applyAppearance();if(JSON.stringify(before)!==JSON.stringify(this.project))this.record(before,'Options');else this.renderAll();return true;};
    await modal('Options',{width:515,content,buttons:[{label:'OK',value:true,primary:true,action:apply},{label:'Cancel',value:false}]});
  }
  objectBrowser(){return this.documents.openTool(this.documents.tools.get('tool:object-browser')||new ObjectBrowser(this));}
  projectSearch(replace=false){const tool=this.documents.openTool(this.documents.tools.get('tool:project-search')||new ProjectSearch(this));tool.show(replace);return tool;}
  toggleBookmark(id=this.activeModule?.id,line=this.editor.cursor().line){const module=findModule(this.project,id);if(!module)return;const before=clone(this.project),marks=normalizeBookmarks(module.bookmarks,module.code);module.bookmarks=marks.includes(line)?marks.filter(n=>n!==line):normalizeBookmarks([...marks,line],module.code);this.record(before,'Toggle bookmark');}
  nextBookmark(direction){const hit=navigateBookmark(this.project,this.activeModule?.id,this.editor.cursor().line,direction);if(hit)this.openDocument(hit.moduleId,'code',hit.line);else this.status('No bookmarks in this project.');}
  clearBookmarks(){const before=clone(this.project);for(const m of this.project.modules)delete m.bookmarks;this.record(before,'Clear all bookmarks');}

  async snapshotRuntime(){if(!this.runtimeFrame)return;return new Promise(resolve=>{this.snapshotCallback=resolve;this.sendRuntime('snapshot');setTimeout(()=>{if(this.snapshotCallback===resolve)this.snapshotCallback=null;resolve();},250);});}
  async virtualFiles(){
    await this.snapshotRuntime();const body=el('div');
    const dataOf=entry=>entry?.encoding==='base64'?fromBase64(entry.data):String(entry??'');
    const render=()=>{body.replaceChildren(el('p',{},'Files are private to this project. Binary downloads preserve every byte.'));const table=el('table',{class:'virtual-files-table'});
      for(const [path,entry]of Object.entries(this.project.vfs.files||{})){const data=dataOf(entry),binary=data instanceof Uint8Array;
        table.append(el('tr',{},el('td',{},path),el('td',{},new Blob([data]).size+' bytes · '+(binary?'binary':'text')),el('td',{},
          el('button',{onclick:()=>download(path.split('/').at(-1),data,binary?'application/octet-stream':'text/plain')},'Save'),
          el('button',{onclick:async()=>{const input=el('textarea',{style:{width:'100%',height:'260px',font:'12px monospace'},'aria-label':binary?'Hex bytes':'File text'});input.value=binary?[...data.slice(0,65536)].map(b=>b.toString(16).padStart(2,'0')).join(' '):data;
            if(binary&&data.length>65536){input.readOnly=true;await modal(path+' — first 64 KiB (read-only)',{width:650,content:input,buttons:[{label:'Close',value:true}]});return;}
            const yes=await modal(path+(binary?' — hexadecimal bytes':''),{width:650,content:input});if(yes){let value=input.value;if(binary){if(!/^(?:[0-9a-f]{2}\s*)*$/i.test(value.trim())){await alertDialog('Enter pairs of hexadecimal digits separated by whitespace.');return;}value={encoding:'base64',data:toBase64(Uint8Array.from(value.match(/[0-9a-f]{2}/gi)||[],h=>parseInt(h,16)))};}const before=clone(this.project);this.project.vfs.files[path]=value;this.record(before,'Edit virtual file',false);render();}}},binary?'Hex…':'Edit'),
          el('button',{onclick:()=>{const before=clone(this.project);delete this.project.vfs.files[path];this.record(before,'Delete virtual file',false);render();}},'Delete'))));
      }if(!table.children.length)table.append(el('tr',{},el('td',{},'No virtual files in this project.')));body.append(table);
    };
    const importFiles=binary=>{const input=el('input',{type:'file',multiple:true,hidden:true});document.body.append(input);input.addEventListener('change',async()=>{try{const before=clone(this.project);this.project.vfs.files ||= {};for(const file of input.files){if(file.size>20*1024*1024){await alertDialog('File exceeds 20 MiB.');continue;}this.project.vfs.files['/'+file.name]=binary?{encoding:'base64',data:toBase64(new Uint8Array(await file.arrayBuffer()))}:await file.text();}this.record(before,'Import virtual files',false);render();}finally{input.remove();}});input.addEventListener('cancel',()=>input.remove());input.click();return false;};
    render();await modal('Virtual File System',{width:720,content:body,buttons:[{label:'Import Text…',value:false,action:()=>importFiles(false)},{label:'Import Binary…',value:false,action:()=>importFiles(true)},{label:'Export ZIP',value:false,action:()=>{const files=Object.fromEntries(Object.entries(this.project.vfs.files||{}).map(([name,entry])=>[name.replace(/^\//,''),dataOf(entry)]));download(this.project.name+'-files.zip',writeZip(files),'application/zip');return false;}},{label:'Close',value:true,primary:true}]});
  }
  checkSyntax(){const compiled=compileProject(this.project);this.diagnostics=compiled.diagnostics;this.editor.setDiagnostics(this.diagnostics);if(this.diagnostics.length)this.showDebug('Errors');return compiled;}
  run(breakOnEntry=false){if(this.runState!=='design')return;const compiled=this.checkSyntax();if(!compiled.valid){const d=compiled.diagnostics.find(d=>d.severity==='error')||compiled.diagnostics[0];if(d){const module=findModule(this.project,d.source);if(module)this.openDocument(module.id,'code',d.line);}this.status('Build failed. Correct the reported syntax errors before running.');return;}this.pendingEdits=false;this.runState='running';this.output=[];this.immediateOutput=[];this.locals=[];this.stack=[];this.watchValues=[];this.bridgeToken=globalThis.crypto?.randomUUID?.()||newId()+Math.random().toString(36);this.runtimeFrame=el('iframe',{title:'Running Visual Basic application',sandbox:'allow-scripts allow-downloads allow-modals',referrerpolicy:'no-referrer'});this.runtimeWindow=el('div',{class:'runtime-window'});const header=el('div',{class:'tool-caption'},icon('run'),el('strong',{},this.project.name+' — Running'),el('button',{class:'runtime-caption-button',title:'Minimize application window',onclick:()=>this.runtimeWindow.classList.toggle('minimized')},icon('minimize',12)),el('button',{class:'runtime-caption-button',title:'End application',onclick:()=>this.stop()},icon('close',12)));this.runtimeWindow.append(header,this.runtimeFrame);this.root.append(this.runtimeWindow);header.addEventListener('pointerdown',e=>{if(e.target.closest('button')||this.runtimeWindow.classList.contains('minimized'))return;const r=this.runtimeWindow.getBoundingClientRect();this.runtimeWindow.classList.add('moved');this.runtimeWindow.style.left=r.left+'px';this.runtimeWindow.style.top=r.top+'px';});makeDraggable(header,this.runtimeWindow);this.runtimeFrame.srcdoc=exportApplication(this.project,{persist:false,bridgeToken:this.bridgeToken,breakpoints:this.breakpoints,breakOnEntry});this.documents.readOnly();this.inspector.setReadOnly(true);this.renderToolbox();this.updateTitle();this.updateCommandState();this.showDebug('Immediate');this.status('Running '+this.project.name+' in an isolated application frame.');this.emit('run',{project:this.project});}
  requestRuntime(command,values={}){return new Promise((resolve,reject)=>{if(!this.runtimeFrame){reject(new Error('Runtime is not active'));return;}this.runtimeRequests ||= new Map();const id=newId(),timer=setTimeout(()=>{this.runtimeRequests.delete(id);reject(new Error('Runtime command did not respond'));},command==='debugEvaluate'?Math.max(5000,Math.min(60000,Number(values.timeLimit)||5000)+3000):5000);this.runtimeRequests.set(id,{resolve,reject,timer});this.sendRuntime(command,{...values,id});});}
  async applyCodeChanges(){
    if(this.applyingEdits)return this.applyingEdits;
    if(!this.pendingEdits)return;
    if(this.runState!=='paused')throw new Error('Pause the program before applying code changes.');
    this.applyingEdits=(async()=>{let result;while(this.pendingEdits){const revision=this.editRevision;result=await this.requestRuntime('applyEdits',{project:this.project});this.pendingEdits=this.editRevision!==revision;this.breakpoints=result.breakpoints;this.syncBreakpoints();this.status('Applied code revision '+result.revision+(result.invalidatedBreakpoints.length?' — '+result.invalidatedBreakpoints.length+' unresolved breakpoints removed.':'.'));}return result;})();
    try{return await this.applyingEdits;}finally{this.applyingEdits=null;}
  }
  sendRuntime(command,values={}){this.runtimeFrame?.contentWindow?.postMessage({channel:'vb6-ide',token:this.bridgeToken,command,...values},'*');}
  async stop(capture=true){if(!this.runtimeFrame){this.runState='design';return;}if(this.stopping)return;this.stopping=true;if(capture)await this.snapshotRuntime();this.sendRuntime('stop');this.runtimeWindow?.remove();this.runtimeWindow=null;this.runtimeFrame=null;this.runState='design';this.pendingEdits=false;for(const request of this.runtimeRequests?.values()||[]){clearTimeout(request.timer);request.reject(new Error('Runtime stopped'));}this.runtimeRequests?.clear();this.stopping=false;this.documents.readOnly();for(const editor of this.documents.editors.values())editor.setExecution(null);this.inspector.setReadOnly(false);this.renderToolbox();this.updateTitle();this.updateCommandState();this.status('Ready');this.emit('stop');}
  onRuntimeMessage(event){const data=event.data;if(!this.runtimeFrame||event.source!==this.runtimeFrame.contentWindow||data?.channel!=='vb6-runtime'||data.token!==this.bridgeToken)return;switch(data.type){case 'state':if(data.state==='paused'||data.state==='running')this.runState=data.state;this.documents.readOnly();this.updateTitle();this.updateCommandState();break;case 'ready':this.status('Running — '+data.instructions+' startup instructions.');this.statusBackend.textContent=data.backend;this.updateWatches();break;case 'backend':this.statusBackend.textContent=data.backend;break;case 'output':this.output.push(String(data.text));this.immediateOutput.push(String(data.text));if(this.output.length>2000)this.output.shift();if(this.immediateOutput.length>2000)this.immediateOutput.shift();if(['Immediate','Output'].includes(this.debugTab))this.renderDebug();break;
      case 'pause':{this.runState='paused';this.locals=data.locals||[];this.stack=data.stack||[];this.runtimeWindow?.classList.add('minimized');const module=findModule(this.project,data.source);if(module)this.openDocument(module.id,'code',data.line);this.editor.setExecution({module:data.source,line:data.line});this.updateWatches();this.renderDebug();this.updateTitle();this.status('Break: '+data.source+'.'+data.procedure+' — line '+data.line);this.emit('pause',data);break;}
      case 'commandResult':{const request=this.runtimeRequests?.get(data.id);if(request){clearTimeout(request.timer);this.runtimeRequests.delete(data.id);data.ok?request.resolve(data.result):request.reject(new Error(data.error?.message||'Runtime command failed'));}break;}
      case 'immediate':if(data.locals)this.locals=data.locals;if(['Locals','Immediate'].includes(this.debugTab))this.renderDebug();this.updateWatches();break;
      case 'watches':this.watchValues=data.values||[];if(this.debugTab==='Watch')this.renderDebug();break;
      case 'error':{const error=data.error||{};this.diagnostics.push({severity:'error',source:error.source||this.project.name,line:error.line||0,message:'Runtime error '+(error.number||'')+': '+error.message});this.editor.setDiagnostics(this.diagnostics);this.showDebug('Errors');this.status(error.message||'Runtime error');break;}
      case 'snapshot':{const old=JSON.stringify(this.project.vfs);this.project.vfs=data.vfs||this.project.vfs;this.project.appSettings=data.settings||this.project.appSettings;if(JSON.stringify(this.project.vfs)!==old)this.markDirty();const callback=this.snapshotCallback;this.snapshotCallback=null;callback?.();break;}
      case 'stopped':if(!this.stopping)this.stop();break;case 'storage':this.status(data.message);break;
    }}
  toggleBreakpoint(module,line){const index=this.breakpoints.findIndex(b=>lower(b.module)===lower(module)&&b.line===line);if(index>=0)this.breakpoints.splice(index,1);else this.breakpoints.push({module,line,condition:''});this.syncBreakpoints();}
  syncBreakpoints(){for(const editor of this.documents.editors.values())editor.setBreakpoints(this.breakpoints);this.sendRuntime('breakpoints',{breakpoints:this.breakpoints});if(this.debugTab==='Breakpoints')this.renderDebug();this.autosave();}
  updateWatches(){if(this.runtimeFrame)this.sendRuntime('watch',{expressions:this.watches});else this.watchValues=this.watches.map(expression=>({expression,value:'<not running>'}));}
  showDebug(tab){this.debugTab=tab;this.togglePanel('debug',true);this.debugCaption.querySelector('strong').textContent=tab;for(const button of this.debugTabs.children){button.classList.toggle('active',button.dataset.debugTab===tab);button.setAttribute('aria-selected',String(button.dataset.debugTab===tab));}this.renderDebug();}
  debugTable(headers,rows){const table=el('table',{class:'debug-table'},el('thead',{},el('tr',{},...headers.map(h=>el('th',{},h))))),body=el('tbody');for(const row of rows){const tr=el('tr',{},...row.values.map(v=>el('td',{},v??'')));if(row.action){tr.dataset.line='1';tr.addEventListener('dblclick',row.action);}body.append(tr);}table.append(body);return table;}
  renderDebug(){if(!this.project)return;const old=this.immediateInput,focused=old&&old.ownerDocument.activeElement===old,inputValue=old?.value||'';this.debugBody.replaceChildren();switch(this.debugTab){
    case 'Immediate':{const log=el('pre',{class:'output-text immediate-output'},this.immediateOutput.join('\n'));this.immediateInput=el('input',{class:'immediate-input','aria-label':'Immediate expression',spellcheck:'false',autocomplete:'off'});this.immediateInput.value=inputValue;this.immediateInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const text=this.immediateInput.value.trim();if(!text)return;this.immediateOutput.push(text);this.immediateInput.value='';this.immediateHistory ||= [];this.immediateHistory.push(text);this.immediateHistoryIndex=this.immediateHistory.length;if(this.runtimeFrame)this.sendRuntime('immediate',{text,id:newId(),frameIndex:this.debuggerWindows?.frameIndex??null,pauseId:this.debuggerWindows?.pauseId});else this.immediateOutput.push('Start the project with F5, or pause it to inspect local variables.');this.renderDebug();this.immediateInput.focus();}if(e.key==='ArrowUp'&&this.immediateHistory?.length){e.preventDefault();this.immediateHistoryIndex=Math.max(0,(this.immediateHistoryIndex??this.immediateHistory.length)-1);this.immediateInput.value=this.immediateHistory[this.immediateHistoryIndex];}if(e.key==='ArrowDown'&&this.immediateHistory?.length){e.preventDefault();this.immediateHistoryIndex=Math.min(this.immediateHistory.length,this.immediateHistoryIndex+1);this.immediateInput.value=this.immediateHistory[this.immediateHistoryIndex]||'';}});this.debugBody.append(el('div',{class:'immediate-view'},log,el('div',{class:'immediate-input-row'},el('span',{},'>'),this.immediateInput)));log.scrollTop=log.scrollHeight;if(focused)this.immediateInput.focus();break;}
    case 'Output':this.debugBody.append(el('pre',{class:'output-text'},this.output.join('\n')));this.debugBody.scrollTop=this.debugBody.scrollHeight;break;
    case 'Locals':this.debugBody.append(this.debugTable(['Expression','Value','Type'],this.locals.map(v=>({values:[v.name,v.value,v.type]}))));break;
    case 'Call Stack':this.debugBody.append(this.debugTable(['Procedure','Module','Line'],[...this.stack].reverse().map(frame=>({values:[frame.procedure,frame.module,frame.line],action:()=>{const module=findModule(this.project,frame.module);if(module)this.openDocument(module.id,'code',frame.line);}}))));break;
    case 'Watch':{const input=el('input',{'aria-label':'Watch expression',placeholder:'Expression'}),add=()=>{if(input.value.trim()){this.watches.push(input.value.trim());input.value='';this.updateWatches();this.autosave();this.renderDebug();}};input.addEventListener('keydown',e=>{if(e.key==='Enter')add();});this.debugBody.append(el('div',{class:'watch-entry'},input,el('button',{onclick:add},'Add')));const values=this.watches.map((expression,index)=>({values:[expression,this.watchValues.find(v=>v.expression===expression)?.value||'<not evaluated>',el('button',{title:'Remove watch',style:{minHeight:'17px',height:'17px',padding:'0 5px'},onclick:()=>{this.watches.splice(index,1);this.updateWatches();this.renderDebug();this.autosave();}},'×')]}));this.debugBody.append(this.debugTable(['Expression','Value',''],values));break;}
    case 'Breakpoints':this.debugBody.append(this.debugTable(['Module','Line','Condition',''],this.breakpoints.map(bp=>({values:[bp.module,bp.line,bp.condition||'(always)',el('button',{style:{minHeight:'17px',height:'17px',padding:'0 5px'},onclick:()=>this.toggleBreakpoint(bp.module,bp.line)},'×')],action:()=>{const module=findModule(this.project,bp.module);if(module)this.openDocument(module.id,'code',bp.line);}}))));break;
    case 'Errors':this.debugBody.append(this.debugTable(['Severity','Description','Module','Line'],this.diagnostics.map(d=>({values:[d.severity||'error',d.message,d.source,d.line||''],action:()=>{const module=findModule(this.project,d.source);if(module)this.openDocument(module.id,'code',d.line||1);}}))));break;
  }}
  async helpDialog(){await modal('Visual Basic Browser Studio — Help',{width:740,content:el('div',{class:'dialog-message'},'PROJECTS\nFile → New Project creates an empty application or opens one of eleven examples. File → Open imports .vb6web, .zip, or .vbp plus its .frm/.bas/.cls source files. Save Project writes a lossless .vb6web project.\n\nDESIGN\nChoose a toolbox control and drag on a form. Double-click a toolbox icon for a default-sized control. Drag selection handles to resize. Ctrl-click selects multiple controls. Arrow keys move, Shift+arrow resizes, and Ctrl+arrow uses a one-pixel step. Double-click a control to edit its default event.\n\nCODE\nF7 shows source; Shift+F7 shows the form. Ctrl+Space opens completion. Ctrl+F and Ctrl+H find and replace. Use the object selector to create event handlers. Edit → Format Code indents the current module. F2 opens the modeless Object Browser. Ctrl+Shift+F/H searches or replaces across the project with reviewed results and atomic undo. Ctrl+F2 toggles bookmarks; Shift+F2 and Ctrl+Shift+F2 navigate them.\n\nDEBUG\nF5 starts or continues. F8 steps into; Shift+F8 steps over; Ctrl+Shift+F8 steps out. F9 toggles a source breakpoint. Shift+F5 ends execution. Conditions, watches, locals and call stacks are under Debug. The Immediate window evaluates ? expressions, calls procedures, and assigns variables.\n\nBUILD\nFile → Make Project.html exports a single-file application containing the same language runtime and controls used by the IDE. The application does not require this editor, npm or an external CDN. Browser-origin policies may require a local static server.\n\nWINDOWS\nResize docked areas using their divider bars. Double-click a right-hand tool-window title to float or dock it. Window → Tile Code and Designer shows both views. Window → Reset Window Layout restores the default.\n\nSTORAGE\nWorkspace autosave is best-effort browser storage. Keep downloaded .vb6web backups. Application files use a private virtual disk; File → Virtual File System imports and exports text files.\n\nTouch: use toolbox buttons and selection handles. On narrow screens, F4 or the Properties toolbar button opens the inspector.'),buttons:[{label:'Close',value:true,primary:true}]});}
  async compatibilityDialog(){await modal('Language and Runtime Support',{width:730,content:el('div',{class:'dialog-message'},'This is an independent browser-native implementation, version '+VERSION+'. It is not Microsoft Visual Basic 6.0 and is not a complete compatibility replacement.\n\nIMPLEMENTED\nSource parser and instruction VM; modules and classes; Subs, Functions and Property procedures; ByRef, ByVal, Optional and ParamArray; arrays and ReDim Preserve; loops, Select Case and With; On Error, Resume, labels and GoSub; common string, math, date and file functions; project-private sequential text files; dictionaries and collections; in-memory Recordset; form and control events; source breakpoints, stepping, locals, watches and Immediate; editable forms; common browser control adapters; native-style text project interchange; standalone HTML export.\n\nNOT IMPLEMENTED AS FULL VB6 COMPATIBILITY\nNative x86 EXE/DLL/OCX execution, COM/OLE binary interoperability, arbitrary ActiveX hosting, Windows API Declare calls, native VB6 binary compilation, exact Windows font metrics, complete Variant coercion/subtype rules, full Currency arithmetic, complete RTF/FRX/OCX property persistence, native database connections, UserControl design projects, native/control WithEvents binding beyond custom class events, native COM interface interoperability, native printer integration, complete VB6 type libraries, or full debugger Edit and Continue.\n\nThe graphics path batches triangles through WebGPU where available and falls back to Canvas2D. Native HTML controls and accessible text inputs handle the UI. Platform-dependent native widgets and font substitution mean this is a classic-style recreation, not a certified pixel-identical rendering.\n\nUnsupported native facilities are reported rather than downloaded or silently executed.'),buttons:[{label:'Close',value:true,primary:true}]});}
  async aboutDialog(){const stats=projectStats(this.project);await modal('About Visual Basic Browser Studio',{width:540,content:el('div',{},el('div',{style:{display:'flex',alignItems:'center',gap:'16px',marginBottom:'14px'}},el('span',{class:'brand-icon',style:{width:'50px',height:'50px',fontSize:'33px',lineHeight:'48px'}},'VB'),el('div',{},el('strong',{style:{fontSize:'16px'}},'Visual Basic Browser Studio'),el('div',{},'Version '+VERSION+' · Independent implementation'))),el('p',{},'HTML · CSS · JavaScript · WebGPU / Canvas2D'),el('p',{},stats.forms+' forms, '+stats.controls+' controls, '+stats.modules+' modules, '+stats.lines+' source lines in this project.'),el('p',{},'MIT-licensed implementation. No Microsoft runtime binaries, OCX files, proprietary fonts, or original artwork are included. Visual Basic and Microsoft are trademarks of their respective owner. This application is not affiliated with or endorsed by Microsoft.')),buttons:[{label:'OK',value:true,primary:true}]});}
}
export const StudioAPI={readRES,writeRES,setResource,setResourceString,VB6Studio,compileProject,normalizeProject,newProject,createForm,createControl,exportApplication,readZip,writeZip,importFiles,EXAMPLES};
const container=document.getElementById('studio');if(container){const studio=new VB6Studio(container);globalThis.vb6Studio=studio;globalThis.VB6StudioAPI=StudioAPI;}
