from pathlib import Path
root=Path('.')
import hashlib
before={'src/native/arrays.js': '80aa4fbe96df9afb60fbdc5dadaf0e5cf67cf5a89ca7f75475c471a85a60af6e', 'src/native/bindings.js': 'f021b581bad4edc26a77ce947e741a99e1902dc62ed42922e5c773c484ba7c12', 'src/native/compiler.js': '698add03b407500c0e406b272575e56f388639b45b3aa6b394314ae7a249bb2a', 'src/native/currency.js': '64aa06a030506b52e5a873e3129dbdd807238a65138d3eb195ca48ccb7d51a09', 'src/native/numeric.js': '4b2ea8bbc34a22bdadee7bd85398b67a23dc3ad20cbd89d169ef28cf630b64a1', 'src/native/storage.js': '8d3e57bba645c52ae07629e1b8c3b519b26bb10126bc0be97d7bccbafd7533e2', 'tests/win32-aot.test.mjs': '53739cd99d2dd536fd6dd0d558326ea2dddb8d9125fdbcc535948b919747159b', 'tests/win32-bindings.test.mjs': '96f866efdd1b149f56eafdfd817c507fe133b065b13b0bf82fda864bf4fad7a0', 'tools/browser-native-build-tests.py': '7d57cfb4209a414e3039cc928935f794ee9edad2794661ee70541240005b6291', 'tools/build-win32.mjs': '2041c4d5d22d5e4aef116e8a8f3bd33ec3bcf6767773e738c689f5945dbee74e'}
for f,h in before.items():
 assert hashlib.sha256((root/f).read_bytes()).hexdigest()==h, "Unexpected source: "+f
def change(name,old,new):
 p=root/name;s=p.read_text();assert old in s,(name,old);p.write_text(s.replace(old,new))
change('src/native/compiler.js',"import {FLOAT_TYPES,", "import {nativeDateMethods,emitNativeDateHelpers} from './dates.js';\nimport {REAL_TYPES,")
change('src/native/compiler.js','FLOAT_TYPES.has','REAL_TYPES.has')
change('src/native/compiler.js','Byte/Integer/Long/Boolean/Single/Double/Currency parameters','Byte/Integer/Long/Boolean/Single/Double/Currency/Date parameters')
change('src/native/compiler.js',"    if(key(variable.type)==='currency')return this.storeCurrency(variable);", "    if(key(variable.type)==='date')return this.storeDate(variable);\n    if(key(variable.type)==='currency')return this.storeCurrency(variable);")
change('src/native/compiler.js',"    const bound=this.nativeConstant(node);if(bound)return bound.type;", "    const bound=this.nativeConstant(node);if(bound)return bound.type;\n    const dateType=this.dateType(node);if(dateType)return dateType;")
change('src/native/compiler.js',"this.expression(node); if(this.type(node)==='currency'){", "this.expression(node); if(this.type(node)==='date'){this.dateToString();}else if(this.type(node)==='currency'){")
change('src/native/compiler.js',"    if(this.currencyOperation(node))return;", "    if(this.dateOperation(node))return;\n    if(this.currencyOperation(node))return;")
change('src/native/compiler.js',"    if(this.currencyBuiltin(node,name))return;", "    if(this.dateBuiltin(node,name))return;\n    if(this.currencyBuiltin(node,name))return;")
change('src/native/compiler.js',"emitNativeNumericHelpers(this);emitNativeCurrencyHelpers(this);", "emitNativeNumericHelpers(this);emitNativeCurrencyHelpers(this);emitNativeDateHelpers(this);")
change('src/native/compiler.js',"nativeControlArrayMethods,nativeCurrencyMethods);", "nativeControlArrayMethods,nativeCurrencyMethods,nativeDateMethods);")
change('src/native/compiler.js',"Typed integer/Single/Double/Currency/String storage", "Typed integer/Single/Double/Currency/Date/String storage")
# Physical representation is separate from numeric promotion order.
change('src/native/numeric.js',"export const FLOAT_TYPES = new Set(['single','double']);", "export const FLOAT_TYPES = new Set(['single','double']);\nexport const REAL_TYPES = new Set([...FLOAT_TYPES,'date']);")
change('src/native/numeric.js',"['double','currency'].includes(key(p.type))", "['double','currency','date'].includes(key(p.type))")
# In numericType, leave the precision-order decision to dateType. Everywhere else
# an 8-byte Date expression is a real snapshot, not a pointer-valued Long.
p=root/'src/native/numeric.js';s=p.read_text();idx=s.index('  floatExpression(');s=s[:idx]+s[idx:].replace('FLOAT_TYPES.has','REAL_TYPES.has');p.write_text(s)
change('src/native/numeric.js',"      else if(REAL_TYPES.has(key(p.type)))", "      else if(key(p.type)==='date'){slot.type=p.type;this.dateExpression(node);this.storeDate(slot);slots.push(slot);return;}\n      else if(REAL_TYPES.has(key(p.type)))")
change('src/native/numeric.js',"      if(key(signature.returnType)==='single')this.roundSingle();", "      if(key(signature.returnType)==='single')this.roundSingle();\n      if(key(signature.returnType)==='date')x.call('native:date:validate');")
change('src/native/storage.js',"'double', 'currency'", "'double', 'currency', 'date'")
change('src/native/storage.js',"Double, Currency or String", "Double, Currency, Date or String")
change('src/native/storage.js',"['double','currency'].includes(key(decl.type))", "['double','currency','date'].includes(key(decl.type))")
change('src/native/storage.js',"if(key(variable.type)==='currency')this.currencyExpression(node);", "if(key(variable.type)==='date')this.dateExpression(node);else if(key(variable.type)==='currency')this.currencyExpression(node);")
change('src/native/storage.js',"double:8,currency:8}", "double:8,currency:8,date:8}")
change('src/native/arrays.js',"double:5, currency:6}", "double:5, currency:6, date:7}")
change('src/native/arrays.js',".compare(6).branch('e',doubleLimit)", ".compare(6).branch('e',doubleLimit).compare(7).branch('e',doubleLimit)")
change('src/native/bindings.js',"'currency','string']);", "'currency','date','string']);")
change('src/native/bindings.js',"type = value instanceof VBCurrency ?", "type = value instanceof Date ? 'date' : value instanceof VBCurrency ?")
change('src/native/bindings.js',"if (type === 'currency')", "if (type === 'date') this.x.value(this.dateLiteral(value));\n    else if (type === 'currency')")
change('src/native/currency.js',"const floats=new Set(['single','double']);", "const floats=new Set(['single','double','date']);")
change('src/native/currency.js',"double:[5,'Double'],currency:[6,'Currency']", "double:[5,'Double'],date:[7,'Date'],currency:[6,'Currency']")
change('tools/build-win32.mjs',"Single/Double, Currency, Strings", "Single/Double, Currency, Date, Strings")

change('src/native/compiler.js',"    if(key(variable.type)==='currency')return this.loadCurrency(variable);", "    if(key(variable.type)==='date'){this.loadFloat(variable);this.x.call('native:date:validate');return;}\n    if(key(variable.type)==='currency')return this.loadCurrency(variable);")
change('src/native/numeric.js',"this.floatUnary(name);if(type==='single'&&name!=='sqr')this.roundSingle();return true;", "this.floatUnary(name);if(type==='single'&&name!=='sqr')this.roundSingle();if(type==='date'&&name!=='sqr')x.call('native:date:validate');return true;")
change('tests/win32-aot.test.mjs',"  ['unsupported record storage','Private Type Point\\n x As Long\\nEnd Type\\nDim n As Point'],['ByVal array parameters','Private Sub F(ByVal n() As Long)\\nEnd Sub'],\n  ['unsupported date storage','Private Sub Form_Load()\\n Dim n As Date\\nEnd Sub'],\n\n","  ['unsupported record storage','Private Type Point\\n x As Long\\nEnd Type\\nDim n As Point'],['ByVal array parameters','Private Sub F(ByVal n() As Long)\\nEnd Sub'],\n  ['unsupported Decimal storage','Private Sub Form_Load()\\n Dim n As Decimal\\nEnd Sub'],\n\n")
change('tests/win32-bindings.test.mjs',"});\ntest('native constant use rejects unsupported Date values without lowering a pointer as an integer',()=>{\n  assert.throws(()=>compileWin32(project('Dim s As String\\ns = CStr(Day)','Private Const Day As Date = #2020-01-01#')),/constant type.*date/i);\n});\n","});\ntest('native Date constants use DATE storage and formatting rather than pointer integers',()=>{\n  const result=compileWin32(project('Dim s As String\\ns = CStr(Day)','Private Const Day As Date = #2020-01-01#'));\n  assert.ok(result.report.imports.some(i=>i.symbol==='VarBstrFromDate'));\n});\n")
change('tools/browser-native-build-tests.py',"            check('Currency export has no network requests or page errors', not errors and not requests)\n        page.close()\n",'            check(\'Currency export has no network requests or page errors\', not errors and not requests)\n        date_dir = ROOT / \'validation/dates\'\n        if date_dir.exists():\n            dates = json.loads((date_dir / \'AotDates.vb6web\').read_text())\n            page.evaluate(\'p => vb6Studio.loadProject(p)\', dates)\n            before = page.evaluate(\'JSON.stringify(vb6Studio.project.modules)\')\n            with page.expect_download() as pending:\n                page.evaluate(\'vb6Studio.command("exportWin32")\')\n            downloaded = pending.value\n            downloaded.save_as(OUT / \'AotDates.exe\')\n            check(\'Date File Make EXE preserves original source\', before == page.evaluate(\'JSON.stringify(vb6Studio.project.modules)\'))\n            check(\'Date File Make EXE output equals Node\', downloaded.suggested_filename == \'AotDates.exe\' and (OUT / \'AotDates.exe\').read_bytes() == (date_dir / \'AotDates.exe\').read_bytes())\n            check(\'Date export has no page or network errors\', not errors and not requests)\n        page.close()\n')
change('tools/browser-native-build-tests.py',"                fixtures.append((currency_dir, 'AotCurrencyBindings'))\n        for fixture_dir, fixture_name in fixtures:\n","                fixtures.append((currency_dir, 'AotCurrencyBindings'))\n        if date_dir.exists():\n            fixtures.extend((date_dir, name) for name in ('AotDates', 'AotDateABI') if (date_dir / f'{name}.vb6web').exists())\n        for fixture_dir, fixture_name in fixtures:\n")

after={'src/native/arrays.js': 'db7a5f103024f9b039823e1c58cf699d2b4c77f5e004c0c8d29da414409f4b28', 'src/native/bindings.js': 'a95fe74012b3cb08fe6b112dc47f9c3190baec4c7413e3ce7c15897b2d24f1a0', 'src/native/compiler.js': '268caeddb41f639b9f663485052ed335ab42ac1419aa1ab181651cf687b09e78', 'src/native/currency.js': 'e017c186a5c9d64cdafb76c4c5dfab9e93dce984cd3742f9c6ffcf844ae1a955', 'src/native/numeric.js': '19503fa885ebdc24cea80c1918990a3e37befa624d8a8c327a5bcc871bfc01fd', 'src/native/storage.js': 'ccb9e1508c2f3d13a92eb8120165a0eef9daff126f11a5afa4ff7834eb1e30b8', 'tests/win32-aot.test.mjs': '8f50168622f71fd60304f6fab1f2a491a15e2cef525b5275dab5f04a18eb7990', 'tests/win32-bindings.test.mjs': '1beabc910c2cde450a6dceaf6235564f180f9fa6b24565f5e41497de57ce7a81', 'tools/browser-native-build-tests.py': '713ce6f8716284db87c749077e912d1c18ea76edcf29dd37412ed4ea04ccce9a', 'tools/build-win32.mjs': 'bf74641a47bbe5d95cc3f6fff0164a2ec2ba5bc8c2147027f1446f5071747c54'}
for f,h in after.items():
 assert hashlib.sha256((root/f).read_bytes()).hexdigest()==h, "Incorrect edit: "+f
new={'src/native/dates.js': '6a7abb76e8b0e7c2c57e2b94f9708343b31a0c750fe501cc61e15e23f04ec459', 'tests/fixtures/native/date-abi.c': 'e4383f89a8245454461469ef5fbfe5dcb99012df80285f06df53325aa18b373b', 'tests/fixtures/native/date-abi.def': 'e35214e7fa3dd5e744982694fb16f56ab6e1e07a681156ff0d4298a65346c7d8', 'tests/win32-date.test.mjs': '2a0da5f0f3cfbbdb11e1ae9d45dea2c4b466a0058fcb50b6a07bd5fa6b4913db', 'tools/test-win32-date-abi.ps1': '95feadb6b52f44cd2849b9fd0ec9f449fc3bb8726744b0f2f7f4bd0e9ba6b4a6', 'tools/test-win32-dates.ps1': 'd97f62fcfbdfa8a212fdbed121efd94714aa6a355f1406f7f634321ce0fbd748', 'tools/win32-date-abi-fixtures.mjs': 'b0a1ebe3a0f9ad135b27cef655fbebfcdc70a7f5962b429142ff21d68f473b36', 'tools/win32-date-fixtures.mjs': 'ec38a440a5f1777e7a15c5fd873083fcc2a21493b592bd3e02f4191c35585582'}
for f,h in new.items():
 assert hashlib.sha256((root/f).read_bytes()).hexdigest()==h, "Incorrect new source: "+f
print("Verified Date source fingerprints")
