import './theme-css.mjs';
import fs from 'node:fs';import path from 'node:path';import {bundle} from './bundle.mjs';
const root=path.resolve(import.meta.dirname,'..');process.chdir(root);fs.mkdirSync('dist',{recursive:true});
const win32=bundle(path.resolve('packages/win32-browser/src/index.js'),'Win32Compat');fs.mkdirSync('packages/win32-browser/dist',{recursive:true});fs.writeFileSync('packages/win32-browser/dist/win32-browser.js',win32);fs.writeFileSync('dist/win32-browser.js',win32);
const runtime=bundle(path.resolve('src/runtime/entry.js'),'VB6Runtime'),css=fs.readFileSync('src/theme/palette.css','utf8')+'\n'+fs.readFileSync('src/theme/common.css','utf8')+'\n'+fs.readFileSync('src/controls/controls.css','utf8');fs.writeFileSync('dist/vb6-runtime.js',runtime);fs.writeFileSync('dist/vb6-controls.css',css);fs.writeFileSync('src/exporter/runtime-payload.js',`// Generated by tools/build.mjs.\nexport const RUNTIME_SOURCE=${JSON.stringify(runtime)};\nexport const RUNTIME_CSS=${JSON.stringify(css)};\n`);
fs.writeFileSync('dist/vb6-native.js',bundle(path.resolve('src/native/entry.js'),'VB6Native'));
const diagnostics=bundle(path.resolve('src/editor/diagnostics-worker.js'),'VB6Diagnostics');
fs.writeFileSync('src/editor/diagnostics-payload.js', '// Generated by tools/build.mjs.\nexport const DIAGNOSTICS_WORKER_SOURCE='+JSON.stringify(diagnostics)+';\n');
const {EXAMPLES}=await import('../src/project/examples.js');const {exportApplication}=await import('../src/exporter/exporter.js');fs.mkdirSync('dist/examples',{recursive:true});
// Stable build-time example IDs; interactive new projects still receive fresh IDs.
function stableExampleIds(project,prefix){
  const map=new Map();let count=0;
  function collect(value){if(!value||typeof value!=='object')return;if(typeof value.id==='string'&&!map.has(value.id))map.set(value.id,`example_${prefix}_${++count}`);for(const child of Object.values(value))collect(child);}
  function replace(value){if(typeof value==='string')return map.get(value)??value;if(Array.isArray(value))return value.map(replace);if(value&&typeof value==='object')for(const key of Object.keys(value))value[key]=replace(value[key]);return value;}
  collect(project);return replace(project);
}
for(const example of EXAMPLES){const p=stableExampleIds(example.create(),example.id);fs.writeFileSync(`examples/${example.id}.vb6web`,JSON.stringify(p,null,2));fs.writeFileSync(`dist/examples/${example.id}.html`,exportApplication(p));}
if(fs.existsSync('src/ide/main.js')){const ide=bundle(path.resolve('src/mcp/studio-entry.js'),'VB6Studio'),ideCSS=css+'\n'+fs.readFileSync('src/ide/ide.css','utf8')+'\n'+['src/editor/editor-advanced.css','src/ide/docking.css','src/ide/command-bars.css','src/ide/debug-windows.css','src/ide/ide-tools.css','src/ide/data-environment.css','src/ide/browser-windows.css','src/mcp/mcp.css','src/agents/agents.css'].filter(p=>fs.existsSync(p)).map(p=>fs.readFileSync(p,'utf8')).join('\n');const template=fs.readFileSync('src/ide/index.html','utf8');fs.writeFileSync('dist/studio.js',ide);fs.writeFileSync('dist/studio.css',ideCSS);fs.writeFileSync('dist/index.html',template.replace('<!--STYLE-->','<link rel="stylesheet" href="studio.css">').replace('<!--SCRIPT-->','<script src="studio.js"></script>'));const standalone=template.replace('<!--STYLE-->',()=>'<style>'+ideCSS+'</style>').replace('<!--SCRIPT-->',()=>'<script>'+ide.replace(/<\/script/gi,'<\\/script')+'</script>');fs.writeFileSync('dist/VB6-Studio-Web.html',standalone);}
console.log(`Built runtime (${runtime.length.toLocaleString()} bytes) and ${EXAMPLES.length} standalone applications.`);
