import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..'),pkg=path.join(root,'packages/auto-layout'),release=path.join(root,'release');
if(!fs.existsSync(path.join(pkg,'dist/auto-layout.js')))throw new Error('Run npm run build before packaging');fs.mkdirSync(release,{recursive:true});
const npm=process.platform==='win32'?'npm.cmd':'npm',packed=JSON.parse(execFileSync(npm,['pack','--json','--ignore-scripts','--pack-destination',release],{cwd:pkg,encoding:'utf8'}))[0],archive=path.join(release,packed.filename),temp=fs.mkdtempSync(path.join(os.tmpdir(),'vb6-layout-pack-'));
try{execFileSync('tar',['-xzf',archive,'-C',temp]);const dir=path.join(temp,'package'),metadata=JSON.parse(fs.readFileSync(path.join(dir,'package.json'),'utf8'));if(metadata.dependencies||metadata.devDependencies)throw new Error('Standalone package acquired external dependencies');
 for(const file of ['src/index.js','src/index.d.ts','dist/auto-layout.js','README.md','LICENSE'])if(!fs.existsSync(path.join(dir,file)))throw new Error('Missing package file '+file);
 execFileSync(process.execPath,['--input-type=module','-e',`import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {LayoutEngine} from './src/index.js';const e=new LayoutEngine([{id:1,bounds:{x:10,y:20,width:50,height:20},anchor:10}],{width:100,height:100});e.arrange(200,150);assert.deepEqual(e.getBounds(1),{x:110,y:70,width:50,height:20});const c={};vm.runInNewContext(fs.readFileSync('./dist/auto-layout.js','utf8'),c);assert.equal(c.VB6AutoLayout.parseAnchor('Right, Bottom'),10);`],{cwd:dir,stdio:'inherit'});
 console.log('Packed and independently tested '+archive);
}finally{fs.rmSync(temp,{recursive:true,force:true});}
