/** Reproduce the offline SQLite module from the pinned npm package with a committed-snapshot bridge. */
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..');
const source=process.argv[2];
if(!source)throw new Error('Usage: node tools/vendor-sqlite.mjs <extracted sql.js package>');
const metadata=JSON.parse(fs.readFileSync(path.join(source,'package.json'),'utf8'));
if(metadata.name!=='sql.js'||metadata.version!=='1.14.2')throw new Error('Expected sql.js 1.14.2');
const originalJS=fs.readFileSync(path.join(source,'dist/sql-wasm-browser.js'),'utf8');
// sql.js export() closes/reopens the connection. Expose a committed MEMFS copy
// instead, preserving temp tables, functions, last_insert_rowid and pragmas.
// The source is pinned: fail closed when the minified helper changes.
if(!originalJS.includes('var f=sa(this.filename);'))throw new Error('SQLite snapshot adapter needs review');
const marker='        // The shell-pre.js and emcc-generated code goes above';
if(!originalJS.includes(marker))throw new Error('SQLite wrapper marker not found');
const js=originalJS.replace(marker, '        Module["vb6Snapshot"] = function(db) { if(!db || !db.db) throw new Error("Closed SQLite database"); return sa(db.filename).slice(); };\n'+marker);
const wasm=fs.readFileSync(path.join(source,'dist/sql-wasm-browser.wasm'));
const sha=b=>createHash('sha256').update(b).digest('hex');
if(sha(originalJS)!=='35e39a73b2e0bc1c2202a4cadb23bcf7a3a77071a39c270f014402968785b95f'||sha(wasm)!=='38c14f6e379210bc942bdc4ebca44e7bfdb4318ecc1c72ca666a28fdce96670a')throw new Error('Pinned sql.js engine integrity mismatch');
fs.mkdirSync(path.join(root,'src/data/vendor'),{recursive:true});
fs.writeFileSync(path.join(root,'src/data/vendor/sqlite.js'),`// Generated by tools/vendor-sqlite.mjs. sql.js 1.14.2 (MIT); SQLite public domain.\n// JavaScript SHA256 ${sha(originalJS)}; WASM SHA256 ${sha(wasm)}.\nvar module;\n${js}\nconst embeddedSQLite=${JSON.stringify(wasm.toString('base64'))};\nexport function initializeSQLite(){return initSqlJs({wasmBinary:Uint8Array.from(atob(embeddedSQLite),c=>c.charCodeAt(0))});}\n`);
fs.copyFileSync(path.join(source,'LICENSE'),path.join(root,'src/data/vendor/LICENSE.sql.js'));
console.log('Vendored offline SQLite 1.14.2:',sha(wasm));
